swagger-api/swagger-ui

src/main/template/main.handlebars
This corrects the terms of service link to match the [2.0 spec](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#infoObject)
=> Fixed terms of service link

lib/marked.js, src/main/coffeescript/SwaggerUi.coffee, src/main/html/index.html, src/main/template/main.handlebars, src/main/template/operation.handlebars, src/main/template/param.handlebars, src/main/template/param_list.handlebars, src/main/template/param_readonly.handlebars, src/main/template/param_readonly_required.handlebars, src/main/template/param_required.handlebars
This is to address issue #634 “Markdown not rendered”
=> Added Markdown rendering

src/test/e2e/index.js
`it` inside another `it` will not get executed.
=> Take out `checkConsoleErrors` from inside title check

lib/swagger-oauth.js
When no scope is defined OAuth2 key name is not registered. This patch fixes the problem moving the assignment before scopes handling.
=> Fix OAuth2 login when no scope is defined

lib/swagger-oauth.js
From [RFC6749 section-3.3](http://tools.ietf.org/html/rfc6749#section-3.3):
The value of the scope parameter is expressed as a list of **space-delimited**, case-sensitive strings.
Current code use comma as delimiter:
> encodeURIComponent(["foo", "bar"])
'foo%2Cbar'
> decodeURIComponent(encodeURIComponent(["foo", "bar"]))
'foo,bar'
=> Oauth 2.0: use space as delimiter for scopes.

src/main/javascript/view/OperationView.js, src/main/template/operation.handlebars
This removes substitution of \r\n, \r, \n to `<br>`, since the subsequent set of
renderGFM() gets confused by them. Furthermore, the marked module already does a
decent job of substituting \n with proper HTML (`<p>`, if I'm not mistaken).
Fixes issue #1049.
=> OperationView.js: fix rendering of Markdown (GFM) in description fields.

src/main/javascript/view/MainView.js
Original code didn't work because of a mix between the use of 'apisSorters' and 'apisSorter' references. Changed all 'apisSorters' refs to 'apisSorter'.
=> Fixing sorter typo

lib/swagger-oauth.js
Correcting: https://github.com/swagger-api/swagger-ui/issues/1134 in branch develop_2.0
=> Fix - Swagger/Swashbuckle OAuth2 Authorizations not set #1134

src/main/javascript/view/MainView.js
Current code defaults to http protocol, but when package is installed in a https environment, the default validator should be securely available.
=> Update default validator with correct protocol

dist/index.html
Using addApiKeyAuthorization function, needs to be done after swaggerUi is loaded, otherwise calling ``window.swaggerUi.api.clientAuthorizations.add`` will fail, and the authorization headers will not be aded.
=> Call to swaggerUi.load before possible use.

.gitattributes
This was breaking an automated build process in drupal via drush: No longer able to automatically change branches because the LF was inserted in place of CRLF in binary files? Screenshot is from my fork, but it was without modification (until this PR). Our project is temporarily building from my fork until we find a better resolution.
mac osx git version 2.3.2 (Apple Git-55) (same issue on centos box however)
=> Forcing old images to not be CRLF conformed due to new gitattributes file

src/main/javascript/view/OperationView.js
As in subject, ```Operation#execute``` from swagger-js expects ```swaggerOptions``` by the look of this code: https://github.com/swagger-api/swagger-js/blob/develop_2.0/lib/types/operation.js#L542-L544 and swagger-js tests.
=> Pass swagger options to swagger-js Operation#execute method

src/main/javascript/helpers/handlebars.js, src/main/javascript/view/OperationView.js, src/main/javascript/view/ParameterView.js, src/main/template/param.handlebars, src/main/template/param_list.handlebars, src/main/template/param_required.handlebars
Hi,
This addresses eg. the #982 and #987 and likely some others around the subject.
Except of the multi-line text area for the array type params, I've also got a rid of the 'required' and 'default' attributes of the array type parameters.
Please check the use cases here: https://swagger-test-valdemon.c9.io
The above sample UC additionally cover aspects of required parameters and/or default values in a context of the array type.
The validation error (shown in Swagger UI bottom right) is related to declaring the default value as array for the array type parameter, which doesn't sound like wrong I'd say, according to: http://json-schema.org/latest/json-schema-validation.html#anchor101.
Checking the sample 'swagger.json' against any JSON schema validator succeeds btw.
@webron: this is the …
=> Multiple values for array type parameters as separated lines in the textarea

src/main/javascript/view/OperationView.js
Hi there,
we're currently investigating using swagger as the primary means to document our APIs at XING. We really like swagger so far and see a lot of potential in it for us. You guys do an awesome job.
During our tests with swagger we bumped into little things here and there. I just wanted to contribute a little bit back :-)
Our APIs are mostly Rails based and Rails seems to return responses body containing whitespace on 201s, which results in a parser error. I've already send a pull request for swagger-js to make it more robust against that (https://github.com/swagger-api/swagger-js/pull/370)
This little change prevents another UI glitch caused by trying to parse whitespace as json.
Like I said in the other PR, sorry for not including tests. I'm not a javascript crack and failed to …
=> Prevent the OperationView to display an error in case the response contains a whitespace only body with content type application/json

gulpfile.js, package.json
fixes #1221 
Not much too it, there is already a .jshintignore file. I thought of adding a .jshinrc but the weight of those pedantic details got to me.
At least no more missing semi-colons breaking the travis build :D
PS: using same styler as swagger-js
=> add jshint to gulp..lint and dist

dist/index.html, src/main/html/index.html
I'd been wondering why my APIs were showing up in a seemingly random order every time; then I noticed that the parameter name had been changed, but `index.html` hadn't been updated. :)
=> Use the correct new sorting parameter name

src/main/javascript/view/ParameterView.js, src/main/template/param_list.handlebars
Linked to https://github.com/swagger-api/swagger-ui/issues/1191#issuecomment-97450141
And code from https://github.com/swagger-api/swagger-js/pull/397
Allow for this.model.default (param.default) to be false
If not param.required, then add empty <option/> to list in para_list. Redo the logic there.
=> allow default to be false, tweak "required" in param_list

package.json
This fixes the warning issued at `npm install` time.
=> Use a SPDX-compatible identifier for the 'license' value

lib/swagger-oauth.js, src/main/html/index.html
This adds the 'client_secret' parameter to token requests.
=> Add support for oauth client secret when calling the token URL. Fixes #1384. Fixes #1324.

src/main/javascript/view/MainView.js
This will make the URL's protocol correct, but it does not fix the issue that ```https://online.swagger.io/validator``` redirects to ```http://online.swagger.io/validator``` which returns an insecure image, breaking the nice green ```https``` logo in chrome.
=> Fix validator's https detection

src/main/javascript/view/OperationView.js
Responses containing references to definitions were not being fully resolved when the spec was pulled in over AJAX but was working locally. OperationView.render()'s parsing of the responses was just checking if the ref _started_ with '#/definitions/', not whether it contained it, and when pulled in over AJAX the refs have the URL prepended to them
=> Issue #1423: $ref schema objects in Responses Definitions Object don't seem to be displayed correctly

test/e2e/servers.js, test/e2e/v1.js, test/e2e/v2.js
Using a hard-coded delay 200ms when waiting for the page to load is a recipe for intermittent test failures. A better solution is to use `webdriver.until` and actively wait until the page is loaded (the title is set).
Also the delay 3000ms is not always enough for the selenium webdriver to initialise the browser, I am proposing to increase this delay a bit.
=> Fix timing issues in unit-tests

dist/swagger-ui.js
In current code when 
1) content-type:application/x-www-urlencoded and 
2) In swagger spec we have in: body
The generated curl statement doesn't have -d as part of the request and sends empty body to API backend.
Sample gist: https://gist.githubusercontent.com/VinayBhalerao/fe84395595777db0ffb1/raw/511fa8c3df4cf5fb1116dc413311bd2394a9d602/petstore-example
Use sample json to send in body : https://gist.github.com/VinayBhalerao/ad23a69299146551a0d3
As part of solution, we ask to use in:formData in spec and in code we urlencoded the whole body and then send to API backend. The generated curl statement has the body in -d parameters in urlencoded format, but this doesn't work since some backend only accept json array as part of body.
Fix:
1) Generate -d as part of curl request and send body …
=> Send POST body with content-type: application/x-www-form-urlencoded

dist/swagger-ui.js
File was not showing properly in the DataType for formData. There was a ticket about it as well #1478
=> Fix file displayed as undefined

src/main/template/content_type.handlebars, src/main/template/parameter_content_type.handlebars, src/main/template/response_content_type.handlebars
We are using a content-type which contains a URL, that needs to be quoted.  This causes some sad HTML rendering since the urls aren't endocded when being rendered.
Our content-type is application/hal+json; charset=utf-8; version=1.0; profile="http://donate-api.justgiving.com/profiles"
=> Add support for content-types which contain a quote symbol.

dist/index.html, dist/lib/swagger-oauth.js, lib/swagger-oauth.js, src/main/html/index.html
Hi, while trying to integrate an Azure Active Directory (AAD) protected API with Swagger-UI I encountered the issue where it is required to specify the "Resource" parameter but there was no way of easily providing it. This problem is covered in the open issue https://github.com/swagger-api/swagger-ui/issues/1302.
I made a generic mechanism for passing custom parameters (instead of adding a specific "Resource" parameter) since I also really needed a custom parameter "domain_hint" as explained here - http://www.cloudidentity.com/blog/2014/11/17/skipping-the-home-realm-discovery-page-in-azure-ad/.
I'd appreciate it if this addition can be merged into Swagger-UI. Thanks!
=> Support additional query parameters during OAuth2 authorization process

package.json
http-server dependency was changed to git master version by commit bdb181cb08749b230adc2ea78d2eac3fbf4ffa06 because it required https://github.com/indexzero/http-server/commit/30f4d1e008b3d707a764eb06ad4c1ac2becd9e96, which is now included in http-server v0.8.0.
This avoids a dependency on github, which was unavailable yesterday (see [Github Status](https://status.github.com/messages/2015-08-25)).
=> Go back to released http-server versions dependency now that they released CORS support in 0.8.0

src/main/javascript/helpers/handlebars.js
fix error "defaultValue.replace is not a function" when defaultValue is Integer
=> check 'defaultValue' before calling 'replace'

dist/lib/swagger-oauth.js, lib/swagger-oauth.js
Added support for client credentials (application) flow
Added support for multiple authentication schemes
To use the client credentials, index.html needs to have
1. input boxes to receive client id and client secret
2. handlers that intitialise OAuth correctly on change.
For example, you could replace the explore and apikey inputs in the header with:
<div class='input'><input placeholder="client id" id="input_clientId" name="clientId" type="text" autocomplete="off"/></div>
<div class='input'><input placeholder="client secret" id="input_clientSecret" name="clientSecret" type="text" autocomplete="off"/></div>
and add the following javascript to handle updates within the initialisation block (replacing the apikey javascript):
function updateOauth(){
initOAuth({
clientId: …
=> Client credential flow and multiple schemes

dist/css/print.css, dist/css/screen.css, src/main/html/css/print.css, src/main/html/css/screen.css, src/main/less/specs.less
=> Reapply changes in PR 1740, but fix properly in .less files

README.md
This makes it so people don't think they need a global `gulp` install to create a build or run the dev server.
=> Document use without a global gulp install

README.md
Guidelines  will be useful for people who install Swagger ui in windows. error is below.
=> Added Window Specific Guidelines

.gitattributes
Because of it ttf files are marked as modified after we git clone master with git 1.7.9.5.
=> set ttf files as binary in gitattributes

dist/swagger-ui.js, src/main/javascript/view/partials/signature.js
When sample XML results are generated, the code looking up a `$ref` attempts to read the property `type` from `model`, which does not exist. As a result, the type defaults to `object` and only `$refs` to `object` definitions work properly.
Minimal example:
`{  
"swagger":"2.0",
"schemes":[  
"http"
],
"paths":{
"/pet":{  
"get":{
"summary":"Get pet",
"description":"Returns a single pet",
"operationId":"getPet",
"produces":[  
"application/xml"
],
"responses":{  
"200":{  
"description":"successful operation",
"schema":{  
"$ref":"#/definitions/Pet"
}
}
},
"security":[  
{  
"api_key":[]
}
]
}
}
},
"definitions":{  
"Primitive": {
"type": "integer"
},
"Pet":{  
"type":"object",
"properties":{  
"id":{ 
"$ref":"#/definitions/Primitive"
}
}
}
}
}`
Before: 
`
<?xml version="1.0"?>
<Pet> …
=> Fix generated XML when property definitions reference primitive types

gulpfile.js
Less errors were crashing Gulp-watch, this will allow you to fix your error and continue without having to reset gulp
=> added a stream end to gulp-less to prevent less errors stopping watch

dist/css/print.css, dist/css/screen.css, src/main/html/css/print.css, src/main/html/css/screen.css
Hello there. This tiny PR fixes CSS for the markdown box when given a code example that's larger than the width.
Before:
After:
Thanks for considering!
=> Fixes overflow issue for markdown code examples

dist/css/typography.css, src/main/html/css/typography.css
Hi there, this problem was reported to our Matrix swagger docs - I tested this fix and it works across browsers, including Safari.
See https://github.com/matrix-org/matrix-doc/issues/270
=> Without this "," Safari fails to load the font

src/main/less/specs.less
In ceb6655663278f548637da2b1150f11e50aad2e9 (#2130), CSS code has been changed in `src/main/html/csss/{print,screen}.css` instead of LESS source.
This commit resynchronize the source with the generated code.
This fixes #1710.
=> Sync specs.less with {print,screen}.css (#1710)

src/main/javascript/view/Oauth2Model.js
This implements the fix in https://github.com/swagger-api/swagger-ui/issues/2150.
I have tested it and can authorize without any scopes defined in path and securityDefinition.
=> Make oauth2 scopes optional

src/main/javascript/view/AuthButtonView.js
This pull request fixes #2238. 
I encountered this issue as well, when doing changes related to authorization schemes.
The cause of the issue is in the PopupView 'cancel' button click event handler. It will invoke 'this.remove()', which removes all the child elements of the popup and will also unbind all the events bound to the child elements. By re-rendering the AuthButtonView before creating a new PopupView object, we rebind all the unbound button events.
=> Fix issue #2238

README.md
The documentation around headers makes it seem like any client authorizations are applied to every request though they are not. The Swagger-JS `README.md` specifies this clearly though.
=> Clarify auth header documentation

src/main/javascript/utils/utils.js, src/main/javascript/view/Oauth2Model.js
This pull request includes two Oauth2 scope related fixes.
The first commit fixes so the global scopes object is not mutated when a path does not require all valid scopes. Without this fix the Oauth2 security method is basically broken if you are using more than one path with different scopes.
The second commit changes the valid behavior for the Oauth2 security method so it is valid even if no scopes is specified. There might be valid api calls that does not require a scope. Eg. a `debug_token` endpoint.
=> Oauth2 scope fixes

dist/index.html
=> Set default oauth scope separator to whitespace

src/main/javascript/view/MainView.js
Explanation: http://stackoverflow.com/questions/9646407/two-forward-slashes-in-a-url-src-href-attribute/9646435#9646435
=> Simplify online validator URL building (HTTP[S]?)

package.json
npm "run scripts" resolves executable file path with PATH includes ./node_modules/.bin
fixes #2411, #2367, #2348
=> Fix handlerbars script in package.json

src/main/html/css/typography.css
The `format('truetype')` bit should not be preceded by a comma. It breaks in Chrome (at least).
See https://css-tricks.com/snippets/css/using-font-face/ for an example.
=> Fix font src attribute

README.md
The repo's tag names don't start with a `.`.
=> Fix tag names in README

gulpfile.js, package.json
Chrome gets very confused by the sourceMappingURL from swagger-client.js. Use
gulp-sourcemaps to generate our own sourcemap which it is happier with (and
means that the other bits of swagger-ui.js are also correctly sourcemapped).
=> Use gulp-sourcemaps to generate a sourcemap

src/main/html/o2c.html
Facebook adds a nonsense fragment to all redirect URIs when returning a code, to stop fragments being surreptitiously passed through the authorization flow.
See http://stackoverflow.com/questions/7131909/facebook-callback-appends-to-return-url
Before this change to o2c.html, the presence of Facebook's garbage fragment would break the Swagger UI complete page, as having any fragment value at all will cause the complete page to ignore the query string. This change avoids using the fragment if it looks to be useless.
=> Avoid using Facebook garbage fragment to complete login

gulpfile.js, package.json
When working with the generated dist, I noticed the some of the libs in the JS libs folder and all the CSS are not minimized.  Local testing showed this removes over 11,000 lines from dist 😄 
This PR adds tasks to the gulpfile to ensure that everything gets minimized, which should help perf.
I've tested this locally and am happy the dist still functions as expected.  It's not the most beautiful solution to the problem, but it works :-) I'll create a seperate PR containing the new minimzed Dist.
=> Add tasks to gulpfile to minify all CSS and JS libs when building dist, removes 11000 lines from dist

src/main/html/o2c.html
Auth providers like Facebook and Google tend to add garbage fragments onto OAuth 2.0 redirect URIs to stop malicious fragments being maintained through the flow. This change ensures that those fragments aren't mistakenly used to attempt to complete login.
If the fragment contains a code, token or error, it is assumed to be the correct place to find data provided by the auth provider.
As discussed in #2489, this change provides a more complete solution to the problem.
=> On complete, ignore fragments that don't contain useful information

src/main/javascript/view/ResourceView.js
JsonEditor parameters aren't part of a "Try it out" request on operation having multiple tags.
Not sure this fix is ideal but it resolve the bug.
Json definition exemple:
```
{
"swagger": "2.0",
"info": {
"description": "This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.",
"version": "1.0.0",
"title": "Swagger Petstore",
"termsOfService": "http://swagger.io/terms/",
"contact": {
"email": "apiteam@swagger.io"
},
"license": {
"name": "Apache 2.0",
"url": "http://www.apache.org/licenses/LICENSE-2.0.html"
}
},
"host": "petstore.swagger.io",
"basePath": "/v2",
"tags": [
{ …
```
=> Fix jsonEditor parameters when an operation is on multiple tags

nginx.conf
Enable CORS in the nginx file used by Docker. I followed [this guide](http://enable-cors.org/server_nginx.html) to configure it.
I have already tested the docker image generation with these changes and it worked fine.
=> Enable CORS by default in the nginx file

Dockerfile, nginx.conf
- Upgraded to alpine:3.4 from alpine:3.3.
- Bug fix: create required directory for nginx pid. Otherwise, the "no such file or directory" error will occur.
- Bug fix: the default root directory is determined by --prefix argument of nginx. It is not same as current "/usr/share/nginx/html". So we need use absolute root directory in nginx.conf.
=> Upgrade to alpine:3.4 and fix issues

src/main/less/style.less
Apparently, `logo.png` and `shield.png` got deleted at some point from this repo, but styles weren't updated, which in turn causes problems with static files versioning mechanisms provided by Python's Django (`django.contrib.staticfiles.storage.CachedStaticFilesStorage` and friends).
=> [CSS] Remove refs to images that don't exist anymore.

src/main/javascript/view/AuthView.js, src/main/javascript/view/Oauth2Model.js, src/main/javascript/view/Oauth2View.js, src/main/less/auth.less, src/main/template/oauth2.handlebars
This PR is an OAuth2 password flow implementation works with #2014 
This PR updates #1853 and #1574
And this closes #807
=> Implement OAuth2 password flow

lib/swagger-oauth.js, src/main/javascript/view/AuthView.js
This pull request adds support for using a *vendor property* to set the name of the *OAuth2 access token name* read from the server.
The current code contains a means of specifying the name of the access token passed from the server by adding `tokenName` to `swagger.json` for an *OAuth2 security definition*. These commits slightly modify this behaviour to prefer `x-tokenName` before falling back to `tokenName`.
According to [the swagger spec](http://swagger.io/specification/#securityDefinitionsObject), `tokenName` is not a recognised attribute of `securityDefinitions` items. The definition does support custom attributes however, as long as their names are prefixed with `x-`.
When generating `swagger.json` programmatically, many tools support adding custom vendor properties, but generally …
=> OAuth2 access token name as vendor property

src/main/html/index.html, src/main/javascript/view/OperationView.js, src/main/less/specs.less, src/main/template/operation.handlebars
When swagger-codegen is used, the operation-Ids are used to generate method names for the target language. At the moment those operation-Id are not visible in swagger-ui. Displaying the operation-Id would ease development a lot.
This patch displays the operation Id on the right side of the operation summary. 
The variable "showRequestHeaders" in index.html must be set to true to enable this feature.
=> Add option "showOperationIds"

src/main/javascript/view/MainView.js
This pull request is related to issue #2372.
When resource name has special characters (forward slash in my case), it is not properly escaped.
This causes problems while expanding operations under a resource. More details are provided in the issue.
=> Fix escaping resource name.

src/main/javascript/view/OperationView.js
Add a `responseHooks` option that allows the user to process the response of an API call.
The `responseHooks` option is an object where key is an `operationId` (`nickname`) and value is a function that receives the XHR response object and the `OperationView` object.
Use case: process authentication requests done with the "Try out!" button to inject apiKey in the AuthView and the router on success. I've been able to successfully implement this.
=> Feature: add responseHooks option for callbacks on responses

Dockerfile
When running
```
docker build -t swagger-ui-builder .
docker run -p 80:8080 swagger-ui-builder
```
you can't currently stop the process by pressing `Ctrl + C`.
This PR fixes that.
=> Attach nginx process to PID 1 so the container can be stopped properly.

src/main/less/specs.less, src/main/template/operation.handlebars, src/main/template/param.handlebars, src/main/template/param_list.handlebars, src/main/template/param_readonly.handlebars, src/main/template/param_readonly_required.handlebars, src/main/template/param_required.handlebars
The new behavior is that the long content just spills into the adjacent column.
Before:
After:
This patch addresses swagger-ui [Issue 2676](https://github.com/swagger-api/swagger-ui/issues/2676)
=> Prevent long words in parameter descriptions from stretching table

src/core/components/operations.jsx, src/style/_errors.scss, src/style/_layout.scss
- removed Expand all methods icon (no functionality implemented yet)
- updated error wrapper once again
- added missing operation colors
=> Error styling updates / added missing operation colors

Dockerfile
When adding all the files contained in public directory into the nginx server, the destination path MUST be a directory.
=> Added missing slash in Dockerfile on ADD section

src/core/plugins/spec/reducers.js, test/core/plugins/spec-reducer.js
Fixes #2918.
Includes a control and test case for the reducer in the tests.
=> Add deep access guard to operation update reducer

README.md
The npmjs.com/package/swagger-ui-dist url in the readme is wrong as it tries to load within github domain
=> Correct url in README file

src/core/oauth2-authorize.js
In swagger-ui 3.0.10 OAuth2 authorizations don't work.
swagger-ui doesn't send client_id and more parameters because there was misplaced semicolon.
I rewrite code assembles querystring instead of fixing a typo since similar problem shall occur again.
=> fix OAuth2 authorize issue + remove redundant parameters

src/core/index.js
Fixes #3061 
Unblocks #3103 
Allows users to provide custom config values via the `custom` namespace.
=> Add custom namespace to config whitelist

swagger-ui-dist-package/README.md, swagger-ui-dist-package/deploy.sh, swagger-ui-dist-package/index.js, swagger-ui-dist-package/package.json
Entry point was missing. This change allows importing SwaggerUIBundle
and SwaggerUIStandalonePreset directly from package. Correct entry point
is also needed for module bundlers like webpack to perform tree-shaking.
=> packaging: fix swagger-ui-dist entry point

src/core/components/layout-utils.jsx
This PR simply removes the `clear` class from the `<Col>` component, since it is no longer used.
It reduces the chance of a conflict when Swagger UI is embedded into a larger page/site that may already define it's own `clear` class.
=> Remove unused legacy clear class (Fixes #3167)

src/style/_buttons.scss
This PR simply renames the `pulse` animation to a less generic name (`swagger-ui-pulse`).
It reduces the chance of a conflict when Swagger UI is embedded into a larger page/site that may already define it's own `pulse` animation.
=> Use less generic pulse animation name (Fixes #3169)

src/core/components/operation.jsx, src/style/_layout.scss
Succeeds #3152.
Gives operation summaries 16px font size, except for operationIds, which get 14px.
=> CSS fixes for operationId display

src/core/components/models.jsx
Show a more compressed view if docExpansion is set to "none"
With this change, if docExpansion is "none", the initial view appears thus:
=> Add support for docExpansion flag to models

src/core/components/response.jsx
Adds the necessary arguments to indent the JSON examples. Addresses issue #2928.
=> Indent JSON examples.

swagger-ui-dist-package/index.js
Path should be "./absolute-path.js" not "./.absolute-path.js". This caused webpack to throw an error "/node-modules/swagger-ui-dist/.absolute-path.js doesn't exist"
=> Fix wrong path to absolute-path.js

swagger-ui-dist-package/absolute-path.js
using ES6 syntax will cause trouble unless you transpile before use (which is something you should not be required to do in a dist package)
=> don't use ES6 syntax in a dist package

package.json
This takes advantage of the changes made in https://github.com/connec/yaml-js/issues/37#issuecomment-310246279, which resolves issues with Webpack throwing warnings about the yaml-js package.
May also solve Webpack 2 problems in https://github.com/swagger-api/swagger-ui/issues/3046 and in a user's codebase https://github.com/openfisca/legislation-explorer/pull/94, since the yaml-js change no longer leans on the `fs` module by default.
=> Update and pin yaml-js version

src/core/components/models.jsx, src/style/_models.scss
Fixes #3110 
This is a ridiculous 13 yr old bug in Firefox (which they've just resolved 7 days ago): https://stackoverflow.com/questions/35407415/firefox-svg-symbol-transform and https://bugzilla.mozilla.org/show_bug.cgi?id=265894
TLDR: You can't use a `svg { }` selector to apply transforms. Instead, you must use another selector (such as class or id, etc) to select the `<svg>` element.
I changed our code to not rely on CSS and instead use a separate icon to display the down arrow (like the operations do). I believe this approach is more pure, regardless of the Firefox bug.
=> #3110 - Fix Models down arrow icon in firefox

src/core/components/schemes.jsx
Fixes #3166.
Causes the default scheme to be updated when a new spec loads.
=> Trigger setScheme when a new set of schemes come in

src/core/utils.js, test/core/utils.js
Fixes #3299 
Export validateNumber and validateInteger for easy reuse and testing.
Broke validateParam required check onto multiple lines. 
Added tests for validateNumber, validateInteger, and validateParam.
=> Fixes #3299 - default required integer validation

src/core/components/parameter-row.jsx, src/style/_layout.scss
Fixed to LATIN SMALL LETTER A because class name contained CYRILLIC
SMALL LETTER A.
ref issue #3104
=> fixing Non-ascii character class name

src/core/components/param-body.jsx
Fixes #3271 
Only trim parameter values if the parameter's content type is JSON. Change default value of parameter inputs to be '{}' only if the parameter's content type is JSON.
=> Fixes #3271 - Trimming parameter values

README.md, src/core/components/layouts/base.jsx, src/core/components/operations.jsx, src/core/index.js, src/core/plugins/layout/actions.js, src/core/plugins/layout/reducers.js, src/core/plugins/layout/selectors.js, src/plugins/topbar/topbar.jsx, src/standalone/layout.jsx, src/style/_layout.scss, src/style/_topbar.scss
Useful for the display of very large swagger specs. Can limit the number of operations to a smaller value and search.
For example:
```
const ui = SwaggerUIBundle({
url: "http://petstore.swagger.io/v2/swagger.json",
dom_id: '#swagger-ui',
docExpansion: 'none',
maxRows: 100,
filter: '',
presets: [
SwaggerUIBundle.presets.apis,
SwaggerUIStandalonePreset
],
plugins: [
SwaggerUIBundle.plugins.DownloadUrl
],
layout: "StandaloneLayout"
})
```
Appears as:
We can filter the list:
=> Added maxRows and filter support

src/core/plugins/spec/selectors.js, test/core/plugins/spec/selectors.js
Fixes #3375 
Change order of logic for selecting `requestContentType` to prioritize `consumes_value` first and then fallback to parameter values.
=> Fixes #3375 - Change order of logic for selecting requestContentType

src/core/components/array-model.jsx, src/core/components/model-collapse.jsx, src/core/components/model.jsx, src/core/components/object-model.jsx
Fixes #2926 
- Add optional `title` prop to `Collapse` so collapse elements can render titles to be clickable
- ObjectModel and ArrayModel pass the new `title` to `Collapse`
=> Fixes #2926 - Click name of model to collapse/expand

src/core/components/operation.jsx, src/style/_layout.scss
Fixes #3384 (both points in the ticket).
=> Render external documentation descriptions as Markdown

swagger-ui-dist-package/index.js
There was a small bug that I noticed in this PR: #3218. If you follow the example usage in the [Readme for swagger-ui-dist-package](https://github.com/swagger-api/swagger-ui/tree/master/swagger-ui-dist-package), you will notice that calling `require("swagger-ui-dist").getAbsoluteFSPath()` does not work, but `require("swagger-ui-dist").absolutePath()` does.
This PR simply renames the export to fix this issue.
=> Fixed bug in module export name for absolute path in swagger-ui-dist

src/core/components/models.jsx
Fixes #3422 
Fixed regression bug on models.jsx expand/collapse arrows due to bad merge
=> Fixes #3422 - Expand/collapse arrows fix

src/style/_layout.scss
=> Fixes #3434 - Change link style color

src/core/components/layout-utils.jsx, src/core/json-schema-components.js, src/core/utils.js, src/style/_buttons.scss, src/style/_form.scss, src/style/_mixins.scss, src/style/_table.scss, test/core/utils.js
Fixes #3414, #3407, 
Update parameter <select> elements to render 'invalid' classes. Add invalid' CSS for <select> elements. Rework validateParam() function. Added .btn-sm class for "Add item" and "Remove item" buttons in array parameters. Reduce border-width on <select> elements inside parameters. Update tests for utils.validateParam().
CSS changes:
=> validateParam() fixes

src/core/utils.js, test/core/utils.js
Previously, a definiton with a 'length' property with numeric value
would result in an OrderedMap of that length.
This is now fixed and covered by tests
This is the failing test case before this fix:
```
1) utils fromJSOrdered should not use an object's length property for Map size:
Error: Expected { 0: undefined, 1: undefined, 2: undefined, 3: undefined, 4: undefined } to equal { length: 5 }
+ expected - actual
{
-  "0": [undefined]
-  "1": [undefined]
-  "2": [undefined]
-  "3": [undefined]
-  "4": [undefined]
+  "length": 5
}
```
=> Fix length issue in OrderedMaps

src/core/components/array-model.jsx
In `<ArrayModel>`, removes the fallback to `name` when no title is specified.
This fixes an issue where the name of the parent `<iframe>` is incorrectly displayed when swagger-ui is embedded in an iframe.
See #3424 for a full description of the issue and the fix.
=> Remove fallback to name for array model title (Fixes #3424)

src/core/components/response-body.jsx
Fixes #3435 
When rendering a response with content-type "image/*" we were just inserting the URL of the request into the `<img>` element. This would cause the browser to make a `GET` request to the URL.
Now, instead of inserting the URL into the `<img>` element, we take the returned response, assume it is an image (JS [Blob](https://developer.mozilla.org/en/docs/Web/API/Blob) because of the returned content-type), and then insert a [`URL.createObjectURL()`](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL). 
Also added the `max-width` style to ensure rendered images to do not extend past the edge of their parent.
=> Fixes #3435 - Fix rendering of image/* content types

src/core/index.js, src/core/utils.js
This PR makes arbitrary config items possible without nesting under the `custom` key.
=> Remove config filtering

src/core/components/object-model.jsx
=> Support oneOf, anyOf, not

README.md, src/core/index.js, src/core/plugins/view/root-injects.js
Fixes #3492
Deep extend mangles a dom element reference, but since it only can come from the config passed to `SwaggerUIBundle` an easy fix is to just manually set the value of the merged config.
=> Fixes #3492 - Add domNode parameter

src/core/components/layouts/base.jsx, src/core/components/operation.jsx, src/core/components/schemes.jsx, test/components/schemes.js
Fixes #3541, fixes #3470.
Supersedes #3548.
Adds one previously-failing test.
---
The problem here was twofold:
1) The global `<Schemes>` component was not getting an `operationScheme` prop.
2) the comparator in `componentWillReceiveProps` was using `ImmutableList.has` (for keys) instead of `ImmutableList.includes` (for values).
---
Confirmed working:
- Global scheme switcher
- Operation-specific scheme switcher
- Example in #3541
- No regressions from #3166
=> Fix global state issues with Schemes component

src/core/index.js
Fixes #3589. `domNode` should be removed from `opts` before merging, as it may contain circular references or be extremely large.
=> Fixes #3589 - Remove domNode from deepExtend

src/core/components/operation.jsx, src/core/components/operations.jsx, src/style/_layout.scss
Fixes #3610 
If deeplinking is disabled, removed the href attribute from the anchor tag fix because empty href points to the base location of the website which causes problems in any SPA.
A side effect is that when an anchor tag has no href it is no longer a hyperlink hence browsers do not show the hand pointer when we hover over it, so setting the pointer to default explicitly.
=> Bugfix for #3610

src/polyfills.js
Fixes #3586.
Adding this conditional overrides the test in core-js that overwrites `window.Promise` if the Promise implementation isn't standard (discussion: https://github.com/zloirock/core-js/issues/283, https://github.com/angular/zone.js/issues/783).
This _may_ open us up to issues with non-standard browsers, and applications that use funky Promise implementations, but the risk isn't widespread.
TODO:
=> Only polyfill `Promise` if it doesn't exist at all

src/core/components/parameter-row.jsx, src/core/components/response.jsx, test/components/response.js
Fixes #3032 
`fromJS` does not maintain the order of the properties in the object. Instead, we use the optional [`reviver` function](https://facebook.github.io/immutable-js/docs/#/fromJS) to parse each property in the original `schema` object as an `OrderedMap`.
=> Fixes #3032 - Wrong property order

package.json, src/core/components/operations.jsx, src/core/plugins/deep-linking/layout-wrap-actions.js, src/core/plugins/deep-linking/spec-wrap-actions.js, src/core/utils.js
Fixes #3596 
Wrapped tags and operationIds in function that will replace spaces with underscores. I chose this approach because `swagger-js` is already replacing spaces with underscores for operationIds in the `opId` function.
=> Fixes #3596 - Deep linking issue with spaces

src/core/utils.js, test/core/utils.js
=> Deep link path util tests

package.json, src/core/components/operation.jsx, src/core/components/operations.jsx, src/core/components/response.jsx, src/core/components/responses.jsx, src/core/plugins/oas3/actions.js, src/core/plugins/oas3/reducers.js, src/core/plugins/oas3/selectors.js, src/core/plugins/spec/actions.js, src/core/utils.js, src/style/_layout.scss, test/core/utils.js
Fixes #3654.
CC #3641.
Adds ability to control `Accept` header.
Introduces the concept of a "blessed" response that dictates the Accept header value.
Logic is as follows:
```
if responses has a 2xx response code with media types defined
use first 2xx response's media types as Accept options
else if responses has a default response with media types defined
use default response's media types as Accept options
else
use `*/*` as Accept value
```
Looks like:
=> OAS3: Accept header control

src/core/components/array-model.jsx, src/core/components/primitive-model.jsx, src/style/_models.scss, test/components/primitive-model.js, test/core/utils.js
Fixes #3633 
- Fix alignment in array-model for properties
- Increase fix width in property names and change units to `em`
- Fix fallback to `name` prop in PrimitiveModel and add enzyme test
=> Fixes #3633 - PrimitiveModel titles

src/core/components/parameter-row.jsx
Remove `shouldComponentUpdate` from `parameter-row` component. It will be put back in eventually as part of the performance optimizations once the parameter components are converted to the smart/dumb approach.
=> Fixes #3511 - 2nd attempt - Query & formData parameters together 

src/core/components/response-body.jsx
Invalid application of AND/OR statements prevented file downloads of other types than application/octet-stream from generating a download link
=> Fixes #3694: Apply conditions for generating download link correctly

src/core/components/operation.jsx, src/core/components/parameter-row.jsx
Fixes #3706 
Add missing "in" argument to `getParameter`. Also added check for `responses` variable in `operation.jsx` before accessing it.
I also checked the other calls to `getParameter`, and they all look good.
=> Fixes #3706

src/core/plugins/oas3/auth-extensions/wrap-selectors.js, src/core/plugins/oas3/components/request-body.jsx
Fixes #3718!
Adds a missing `getConfigs` prop to an invocation of `<ModelExample>`, and modifies one of the OAS3 authorization overrides to return an empty Immutable List instead of `null`.
=> Fix problems regarding request body display

src/core/components/providers/markdown.jsx
Fies #3734 
Add `<h1>` and `<h2>` elements to sanitizer options.
I have a test structure setup for XSS/markdown in this branch: https://github.com/owenconti/swagger-ui/commits/test/3715-xss-unit-tests so I will add a test for these heading elements to those tests.
=> Fixes #3734 - Markdown headings

src/core/plugins/download-url.js
CC: #2793.
This PR modifies the DownloadURL plugin to use the `requestInterceptor` and `responseInterceptor` configuration options for spec fetches, which will allow users to handle access of API definitions protected by HTTP Basic authentication.
=> Pass configuration interceptors to spec download fetch

src/core/plugins/spec/actions.js, src/core/plugins/spec/reducers.js, src/core/plugins/spec/wrap-actions.js, src/core/utils.js, test/core/utils.js
Fixes #3747 
Add flag for `isOAS3` on `validateParam` function. Access parameter details from OAS3's `schema` object.
Add a couple tests for new `isOAS3` flag.
=> Fixes #3747 OAS3 validate param

README.md
GitHub suggested that `Good first issue` is now a blessed label name:
I've renamed the label itself as well.
=> `Good first contribution` -> `Good first issue`

src/core/plugins/auth/selectors.js, src/core/plugins/oas3/auth-extensions/wrap-selectors.js
CC @webron, we discussed this earlier today.
This PR fixes a problem with our authSelector wrapActions in the OAS3 plugin, which was causing bleed into Swagger2 usage.
This has to do with interaction between complex action creators (with the signature `(...args) => (system) => action`) and wrapActions. State is being provided to these original actions based on their signature, which creates an undocumented function signature in the wrapAction that sits atop it.
I've made a TODO for myself in #3754 to document the correct way to go about this before shipping our new docs.
=> Fix auth icon display regression

src/core/components/providers/markdown.jsx, test/components/markdown.js
Previously, sections of Markdown that included links would be rendered correctly in the generated API documentation. A recent change broke this as we aren't picking up the sanitise default allowed attributes. This puts the defaults back in place and also adds to the unit tests.
=> Fix regression with rendering links in Markdown.

make-webpack-config.js, webpack-dist-bundle.config.js, webpack-dist-standalone.config.js, webpack-dist.config.js, webpack-hot-dev-server.config.js
Fixes #3263.
Prior art: #3296.
CC: #3592.
CC: @scottohara (you were working on this a couple months back), @heldersepu (we chatted about this last month), & @webron (you pointed out the Docker source map issue this week).
This PR:
- Switches static builds to `nosource-source-map`, a lightweight source map that does not include code visibility, but provides line-accurate stack traces.
- Switches dev server to `eval-source-map`, a heavy but high-accuracy source map.
I built the Docker image locally, and the new source map settings are working as expected.
---
I tested every [devtool option that Webpack has](https://webpack.js.org/configuration/devtool/). Here are my findings:
=> Sourcemaps

src/core/components/parameter-row.jsx
Fixes https://github.com/swagger-api/swagger-editor/issues/1530.
Parameters were restructured in OAS 3.0; schemas are no longer at the top level of parameters. Adjusting to account for the change. EZ.
=> Pass `parameter.schema` as schema in OAS 3.0

.eslintrc, package.json, test/core/plugins/oas3/wrap-auth-selectors.js
CC: @heldersepu, @owenconti 
I'll make a note to add this rule to Swagger-Client and Swagger-Editor, but if anyone reading this wants to handle it, I wouldn't complain 😄
=> Add ESLint rule that catches `describe.only`, `it.only`

docker-run.sh
If swagger-ui is run behind reverse proxy in path other than /, accessing
bundled swagger json configured in SWAGGER_JSON env variable will fail.
Fix that by changing REL_PATH prefix from `/` to `./`
=> Fix accessing bundled swagger json behind reverse proxy

src/core/plugins/spec/actions.js
This PR provides UI's `requestInterceptor` and `responseInterceptor` options to Swagger-Client's resolver, so remote $ref fetches pass through the interceptors.
This fixes #3763 (again). 
With this, we have the interception trifecta: root document, remote $refs, and Try-It-Out.
I created a version of the Petstore that contains a remote $ref, for the purpose of testing this PR: https://gist.github.com/shockey/12d6c48969e0e9e3723b08a7419b0580
- I confirmed that a remote $ref fetch would be intercepted when providing a requestInterceptor to Swagger-UI.
- I confirmed that a remote $ref fetch would execute normally when a requestInterceptor is not provided.
- I confirmed that a remote $ref fetch would be intercepted when providing a responseInterceptor to Swagger-UI.
- I confirmed that a …
=> Provide interceptors to SwaggerClient.resolve

src/core/plugins/oas3/spec-extensions/wrap-selectors.js
This PR changes the `specSelectors.securityDefinitions` selector in OAS3 to return `null` instead of `Immutable.Map()`.
Returning a falsy value allows existing logic that uses the selector to work correctly - for example, the AuthorizeBtn show/hide logic:
https://github.com/swagger-api/swagger-ui/blob/3f9b999e902dcd2cf3e2873e35f7f0dad075925d/src/core/components/layouts/base.jsx#L89-L91
Fixes #3816.
See the screenshots below - I tested this with two OpenAPI definitions, one with authorizations and one without.
No authorization:
Yes authorization:
=> Return null instead of empty ImmutableMap in OAS3 securityDefinitions selector

src/core/components/parameter-row.jsx
I modified ParameterRow's `componentWillReceiveProps` method to tech into `parameter.schema` to grab enums for OAS 3 parameters.
Fixes #3811.
- I confirmed that the first enum value is being used by default for the request.
- I confirmed that selecting an enum value is reflected in the request.
- I confirmed that Swagger 2 enums are continuing to function as before.
=> Pass correct schema values to parameter state builder for OAS3

src/core/plugins/oas3/auth-extensions/wrap-selectors.js
This change avoids a snag in the OAS 3 wrapSelector for `authSelectors.definitionsToAuthorize`, wherein we were reaching into the system for a specSelector value but not watching for changes to it for Reselect's memoization flow.
Fixes #3818.
- I used the test definitions in #3818 to confirm that my fix is working as intended.
=> memoize definitionsToAuthorize based on securityDefinitons value

package.json, src/core/components/info.jsx, src/core/components/online-validator-badge.jsx, src/core/components/operation.jsx, src/core/components/operations.jsx, src/core/utils.js, test/core/utils.js
This PR uses Braintree's `@braintree/sanitize-url` module to strip `javascript:` and `data:` URLs from user-influenced href fields in Swagger-UI.
Fixes security issue #3847.
I tested this PR using the API definition provided in #3847, available as a Gist here: https://gist.github.com/shockey/bace8c2554da6b61193dbeb727dac079
=> Add URL sanitizer to avoid `href` XSS attack vector

src/core/components/content-type.jsx, src/core/containers/OperationContainer.jsx, src/core/plugins/oas3/components/callbacks.jsx, src/core/plugins/oas3/components/request-body-editor.jsx, src/core/plugins/oas3/components/request-body.jsx, src/core/plugins/view/root-injects.js, test/core/system/system.js
**This PR restores the Callback display to its original glory.**
Freebies included:
- `ContentType` now uses its `onChange` callback to reset to the first available value if the value isn't in the next set of available content types.
- This prevents the RequestBody component crashing when changing the name of a currently-selected content type.
- Container components now enjoy render try/catch protection.
Fixes https://github.com/swagger-api/swagger-editor/issues/1565.
- Manually tested with OAS3 callback example definition
- Manually tested integration with Editor - confirmed that all values update when changed
=> Callback expansion issues

src/core/components/auth/api-key-auth.jsx
EZ
Fixes https://github.com/swagger-api/swagger-ui/issues/3907
=> Display `name` security scheme property for apiKey type

src/polyfills.js
Fixes #3571 
Tested with https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml in IE 11
=> Fixes #3571 - add polyfill for startsWith function for IE11.

src/core/components/model.jsx, src/core/components/object-model.jsx
This fixes Swagger-UI's incorrect parsing of Schema object `not `values. It looks like I introduced this problem - looking back at the RC1 definitions I wrote to implement against, the Schema Object definition had an invalid array under the `not `key (presumably a result of copy-pasting `anyOf`/`oneOf`). Mea culpa!
Per JSON Schema (emphasis mine):
> The value of this keyword MUST be an array. This array MUST have at least one element.
> 
> Each element of this array MUST be an object, and each object MUST be a valid JSON Schema.
> The value of this keyword MUST be an array. This array MUST have at least one element.
> 
> Each element of this array MUST be an object, and each object MUST be a valid JSON Schema.
> The value of this keyword MUST be an array. This array MUST have at least one …
=> Don't treat `not` as an array (in contrast to `allOf`, `anyOf`, `oneOf`)

src/core/components/auth/oauth2.jsx
This PR fixes issue #3925. In case we have two flows for the same security scheme and those flows define the same scopes, it is not possible to select a scope from the lower flow since both checkboxes have the same id.
This PR simply adds the flow name to the id so that the checkbox id is unqiue across all flows.
=> Add flow to make scope checkbox id unqiue

src/core/utils.js, test/core/utils.js
This PR changes `validateParam` to tolerate OAS3 parameters that lack a `schema` property entirely.
I bumped into this while fixing a different bug 😄
The OpenAPI 3.0.0 specification [indicates that `schema` is not required](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#parameter-object), therefore we should not rely on it being present.
I modified an existing unit test in order to create a failing test, then made source changes.
=> Correctly validate OAS3 parameters that lack a `schema`

src/core/index.js, src/core/utils.js, src/polyfills.js
Allow swagger-ui to be loaded into nodejs.
At this point for testing only ( no server side rendering magic yet )
=> Be more nodejs friendly

make-webpack-config.js
devtool is accept `string | false` but passed `null`
Specify `false` as `sourcemaps` in webpack-dist.config.js, and do `npm run build`.
It will be failed before this modifications.
=> Pass `false` webpack devtool option instead of `null`

docs/usage/configuration.md
=> Fix link in configuration.md

src/core/components/operations.jsx, src/core/plugins/spec/selectors.js, test/components/operations.js
This PR allows OAS3 definitions to display operations defined as `TRACE` methods, which are legal in OAS3 but not Swagger 2.0.
Method filtering logic was moved from the spec selectors to the Operations component. This is _okay_, but the proper place for such logic is in a selector.
The problem was that it was that the Operations component was using the `operationsWithTags` selector, but the `operations` selector was doing the filtering. The data flow looked like this:
`operations => operationsWithRootInherited => operationsWithTags`
Because of the tight coupling of low-level selectors like `operations` within `/plugins/spec/selectors.js`, it was impossible to override the filtering logic from outside the file... so I compromised and moved the filtering logic to the component, which is …
=> OAS3 `TRACE` method operation display

src/core/components/operation.jsx
From the documentation about Default response:
> Sometimes, an operation can return multiple errors with different HTTP status codes, but all of them have the same response structure. You can use the default response to describe these errors collectively, not individually. “default” means this response is used for all HTTP codes that are not covered individually for this operation.
However, when default is used and a status is returned which is not specifically defined - the "undocumented" warning appears - although it is defined with the default.
When default exists no such warning should appear.
=> Do not display undocumenetd when there is a default response

src/core/plugins/spec/selectors.js
Fixes https://github.com/swagger-api/swagger-ui/issues/4040 🎉
=> Don't parse non-method path keys as operations

docker-run.sh, nginx.conf
Change nginx configuration based on BASE_URL, instead of moving actual files.
Following to #4072 
Since moving static files around is too complex (because the files may be moved before), so in this change, will changing `location` directive in nginx.conf. To make it works, `alias` directive is required instead of `root`.
```bash
docker build -t swagger-ui .
docker run -p 8080:8080 -e "BASE_URL=/api/docs" swagger-ui
docker run -p 8080:8080 -e "BASE_URL=/api/docs" swagger-ui
docker run -p 8080:8080 swagger-ui
```
None
=> Change nginx configuration in Docker container based on BASE_URL, instead of moving actual files

src/style/_table.scss
Remove ".swagger-ui .parameters-col_description p" formatting from _table.scss.
Descriptions for request parameters are bold and a larger font (14px) than they are for response descriptions (12px, normal weight). This proposed change makes the font display consistent.
We noticed this while making some updates to our company's swagger doc and wanted to share. It can also be seen in the [Swagger Petstore](http://petstore.swagger.io/) example (screenshots below).
We made the changes locally and it fixed the issue.
See the request parameter description ([POST /pet](http://petstore.swagger.io/#/pet/addPet)):
The font for a response property description is different ([GET /pet/{petId}](http://petstore.swagger.io/#/pet/getPetById)):
=> Make parameter description styles consistent

src/core/plugins/download-url.js, src/core/plugins/err/actions.js, src/core/system.js, src/core/utils.js, src/standalone/layout.jsx, src/style/_layout.scss
The newThrownErr action distpatcher in the error plugin parsed the error in the wrong format. The result of this was the reducer not understanding the payload and always storing the default error.
I wanted to display the error message when fetching the spec returns a HTTP response with error status >400. 
See screenshot
[Displaying error screenshot](https://screenshots.firefox.com/MThfNgQA9B7dFCa3/localhost)
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] My code follows the code style of this project.
=> fix error action dispatcher and display spec last error

.github/issue_template.md
This PR fixes a broken link to the version-detection.md doc in the issue template.
The link got broken after the docs were reorganized in PR https://github.com/swagger-api/swagger-ui/pull/3754.
I verified that the new link works and opens the "Version Detection" doc.
N/a
=> Fix broken link in the issue template

.npmignore
Fixes swagger-api/swagger-ui#3978.
Usage:
```js
import StandalonePreset from 'swagger-ui/dist/swagger-ui-standalone-preset'
SwaggerUI({
dom_id: '#swagger',
url:'http://petstore.swagger.io/v2/swagger.json',
plugins: [StandalonePreset],
layout: 'StandaloneLayout'
});
```
=> improve(npm-module): include standalone preset in `swagger-ui`

src/core/utils.js, test/core/utils.js
Makes validation for parameters of format uuid case-insensitive so that valid guids are no longer rejected.
Fixes #4099 
- Added test for uuid validation containing uppercase letters
- Ran the swagger ui locally and tested entering a guid containing upper case letters for a parameter with a uuid format
=> Fixes #4099 - uuid format parameter validation should be case insensitive

.dockerignore, Dockerfile, docker-run.sh
@shockey 
Adding the ability to use a custom port for Nginx within the docker container.
In some environments, it can be desirable to specify a custom port to use within the container. Specifically, I'm referring to Kubernetes, where all pods within a deployment are addressable (to each other) via `localhost`. This means that within a deployment, we can't have multiple side car pods/containers listening on the same port.
Normally, this isn't an issue. But when there are multiple hardcoded ports it can be difficult to get things working without having to create services to map ports and separate deployments.
* `docker build -t swaggertest .`
* `docker run --rm -it -p 8900:8709 -e PORT=8709 swaggertest`
* `open http://localhost:8900`
* 🎆  🍾 
I also added a _.dockerignore_ file to decrease …
=> Allow Custom Nginx Port in Docker

docs/usage/installation.md
Fixes a typo in the documentation
=> Fix typo: tranditional -> traditional

docs/usage/installation.md
Fix readme example
installation.md provides an example with 'swagger-ui' but the example fails whereas 'swagger-ui-dist' works
Helps people following examples from documentation
Manually created a new project and tried the example
=> Fix example

src/core/components/operation.jsx, src/core/containers/OperationContainer.jsx, src/core/plugins/spec/actions.js, src/core/plugins/spec/reducers.js, src/core/plugins/spec/selectors.js, test/core/plugins/spec-reducer.js, test/core/plugins/spec/reducer.js, test/core/plugins/spec/selectors.js
Fixes https://github.com/swagger-api/swagger-ui/issues/3998.
This is a 90% solution. The ContentType select components still transmit their default values, but the consumes/produces logic was removed from OperationContainer, so that logic only runs when it has to.
=> Streamline management of user-selected `produces` and `consumes` values (WIP)

src/core/plugins/auth/reducers.js
Fixes a weird IE11 edge case, potentially related to IE11 handling of object references that traverse frames.
In IE11 we were unable to execute requests after authenticating. After authenticating and attempting to execute a request in IE, the below error was logged to the console and the "Loading" indicator stayed present in the UI. The HTTP request also never executed. I believe the error number indicates a NullPointerException in IE, but not sure.
I tracked the exception source down in swagger-js to: 
```js
export function applySecurities({ request, securities = {}, operation = {}, spec }) {
...
const accessToken = token && token.access_token
```
At this point `token` was defined but `token.access_token` access threw an error. The debugger value was hidden (not able to view the …
=> Fixes Execution error in IE11

src/core/components/parameter-row.jsx, src/core/json-schema-components.js, src/core/plugins/spec/reducers.js
This pull request modifies the J sonSchema display components to accept a new `errors` property from ParameterRow instead of reaching into `schema` for an errors property.
This is necessary for OAS3 to validate intelligently (i..e, provide user indications and messages), since which Swagger 2 has its schema properties spread at the parameter's top level, OpenAPI Specification 3.0 has a `schema` property _within_ a parameter.
Fixes #3747.
- Manually tested in 2.0 and 3.0 definitions.
- All existing tests continued to pass.
**Breaking private change**: JsonSchemaForm now needs a `errors` prop to display validation information; it no longer reaches into `schema` for the information.
Existing tests seem adequate.
=> fix(try-it-out): pass Parameter validation messages around in props for OAS3

src/core/components/providers/markdown.jsx, test/components/markdown.js
This PR adds `span` to the allowed tags, `colspan` attribute to the `td` and the `class` attribute to all
Fix issue #3225
My baby said: it looks good to me!
=> Add a couple of items to the sanitizeOptions

docs/usage/configuration.md, src/core/containers/OperationContainer.jsx, src/core/index.js
Restores the `supportedSubmitMethods` config option from Swagger UI 2.x
Default value is `["get", "put", "post", "delete", "options", "head", "patch", "trace"]` (all possible methods supported by OAS 2.x and 3.x), so there is no impact on existing Swagger UI 3.x instances.
As in Swagger UI 2.x, setting the value to an empty array effectively disables Try it Out for all operations.
`<OperationContainer>` now consults this config value when setting the (existing) `allowTryItOut` prop that is passed down to the `<Operation>` component.
`supportedSubmitMethods` was a config option available in Swagger UI 2.x, so the motivation is to bring this previously available feature to Swagger UI 3.x in a way that is compatible with the earlier feature.
Fixes #3314 
Manual testing of the following …
=> Return of supportedSubmitMethods config parameter (Fixes #3314)

dev-helpers/oauth2-redirect.html, dist/oauth2-redirect.html
As mentionned in #4048 oauth error message was hardcoded in oauth2-redirect.html
This PR show the original error provided by the oauth server and eventually an error message and a URI. see [RFC](https://tools.ietf.org/html/rfc6749#section-4.1.2.1)
Fixes #4048 
It is hard to automatically test it, I have run it against my oauth server and tried different possible errors (with or without message).
=> show oauth error callback message when auth fails

src/core/components/response-body.jsx
The error can be seen on this :
http://swashbuckletest.azurewebsites.net/swagger/ui/index#/Image/Image_Put
When opened with Internet explorer, clicking the link does nothing.
In internet explorer, the "Download File" button is shown as a link, but when clicked nothing happens.
Right clicking the link and selecting Save as... will ignore file name, and only display the blob name.
The file has the proper content though. 
Internet explorer uses window.navigator.msSaveOrOpenBlob to save files.
Branching in this file, will allow proper functionality to the link, while having no breaking changes.
This way, the internet explorer little window in the middle of the bottom of the screen will pop up, with the proper filename.
The download link is not working in IE
Fixes …
=> Fix "Download File" link in response-body in Internet Explorer

src/core/plugins/spec/selectors.js, test/core/plugins/spec/selectors.js
This PR fixes a selector bug that was causing incorrect defaulting to an `application/json` consumes value, and fixes some precision issues in the new `specJsonWithResolvedSubtrees` selector.
Fixes #4257.
New unit tests!
=> Try-It-Out `Consumes` value regression

src/core/components/online-validator-badge.jsx, src/style/_layout.scss
Fixes #4234
Tested with a custom css:
http://swagger-net-test.azurewebsites.net/swagger/ui/index
=> Hide missing validator image

docs/usage/configuration.md, package.json, src/core/plugins/on-complete/index.js, src/core/presets/base.js, test/e2e/helpers/index.html, test/e2e/scenarios/on-complete.js, webpack-hot-dev-server.config.js
This PR introduces an `onComplete` config option that fires one tick after `updateJsonSpec` is called following an `updateSpec` call.
In practice, this option should serve as a safe place to put code that touches Swagger-UI's DOM (though we continue encouraging users to instead use the plugin system to modify the UI).
Fixes #3028.
This change can not be easily unit tested. I've added integration tests that will become when #4090 is merged.
=> feat: `onComplete` config option

docs/usage/configuration.md, docs/usage/oauth2.md, src/core/plugins/auth/index.js, test/core/plugins/auth/preauthorize.js, test/core/system/system.js
This PR adds `preauthorizationApiKey` and `preauthorizationBasic` methods to Swagger-UI instances.
A successor ticket will be needed to track OAuth preauthorization, since it is not included in this PR.
Fixes #2915.
Unit tests have been added to test the new interfaces in conjunction with the `authorize` auth action creator.
Basic unit tests were also added for the `rootInjects` interface, which we use to add the methods to UI instances.
=> Preauthorization

src/core/components/models.jsx
Fixes swagger-api/swagger-ui#4291.
=> fix: default to empty ImmutableMap when schema is missing

Dockerfile
Should use LABEL now instead of MAINTAINER.
See: https://docs.docker.com/engine/reference/builder/#maintainer-deprecated
MAINTAINTER instruction set is deprecated and LABEL maintainer="" should be used now instead.
Follows the new standard 
N/A
Built the docker image locally using these changes.
Shouldn't cause any problems with the rest of the code base.
N/A
SEE: https://docs.docker.com/engine/reference/builder/#maintainer-deprecated
=> MAINTAINER deprecated. Use LABEL.

docs/customization/custom-layout.md
Operations is lowercase, without this fix the example doesn't work as a Copy/Paste
Just adjusted the code sample to make it work as-is
It allows somebody to read the documentation and use the example as a working example.
I've used the modified code sample with success.
=> Fixed typo

src/core/components/schemes.jsx
Fixes an issue uncovered in https://github.com/swagger-api/swagger-ui/issues/4435, wherein the application's current scheme state would update but the Schemes component would still display the last scheme selected through user interaction with itself.
=> control Schemes select with state

src/core/components/response-body.jsx, src/style/_layout.scss
Attempt to parse Blob response bodies to text and display the content, if no other content handler can use the data.
Fixes a case in #4406, where incorrect usage of `Content-Type: application/javascript` was precluding the user from viewing the response.
Manually. 😬
=> fix: attempt to display Blob response bodies as text

src/core/components/providers/markdown.jsx
markdown components has a default value for classname, so it isn't reuqired
warning message in developer mode, see #4363 
i tested the petstore and it is still working
=> markdown components classname isn't required

src/core/components/highlight-code.jsx, src/core/components/response-body.jsx
Fix #4446
Who needs to test when the fix is so simple
=> Improve downloadable HighlightCode filename

docs/usage/configuration.md
Updated 'urls' (An array of API definition objects) description to show an actual object array containing two (2) urls, clarifying this configuration-option.
Per-summary, straightforward, provided the configuration-option example in exactly the form it can be used to configure multiple urls in-conjunction with Topbar.
Current doc is not clear on how to use `urls` for multiple URLs, which is the exact driver of that configuration-option.
Tested with this config in my `swagger-ui` app deployment.
=> Updated 'urls' (An array of API definition objects) description.

src/core/components/response-body.jsx
fixes https://github.com/swagger-api/swagger-ui/issues/4398 🎉 
Safari 11 handles Blob URL downloads correctly.
=> fix: remove outdated Safari check for Blob downloads

src/core/components/array-model.jsx, src/core/components/model-wrapper.jsx, src/core/components/model.jsx, src/core/components/models.jsx, src/core/components/object-model.jsx, src/core/components/primitive-model.jsx, test/components/models.js, test/e2e/scenarios/bugs/4536.js, test/e2e/specs/bugs/4536.yaml
=> fix: always display locally-available `title` property as a model's name

src/plugins/topbar/topbar.jsx
Fixes #4527.
- this `href` didn't serve any visible or known purpose
- it was added before prior to 3.0.0 and has not been modified since
- see UX 8ab65d3b
- the `Link` was kept, since the anchor was needed to preserve the current layout.
=> fix(topbar): remove href from Swagger logo

package.json
**CHANGELOG**:
1. Added `start` command to `package.json`
2. Assign server port to `3002`.
Ref : Github issue #4551 
Added `npm run start` command identical to swagger-editor.
This is to make the swagger-ui identical to the swagger.
This PR fixes #4551 
@shockey
=> feat : Add the start command to package.json

src/core/components/online-validator-badge.jsx
Addresses an issue raised by @hkosova.
Not tested, since stubbing `window.location` isn't possible at this juncture. I left a `TODO` for a future test :)
=> fix(validator-badge): resolve definition URLs against browser location

src/core/json-schema-components.js, test/components/json-schema-form.js
followup for #4613 
test with this definition:
```yaml
openapi: 3.0.1
info:
version: 0.0.0
title: test
paths:
/ping:
get:
parameters:
- in: query
name: RequiredEnum
required: true
schema:
type: boolean
enum:
- true
- in: query
name: RequiredNoEnum
required: true
schema:
type: boolean
- in: query
name: OptionalEnum
schema:
type: boolean
enum:
- true
- in: query
name: OptionalNoEnum
schema:
type: boolean
responses:
"200":
description: OK
```
=> fix(tio-params): disable empty values for required+enum booleans

src/core/utils.js, test/core/plugins/samples/fn.js
=> fix: sample generation for nested object schemas

src/core/components/param-body.jsx, src/core/components/parameter-row.jsx, src/core/components/parameters.jsx, src/core/plugins/oas3/wrap-components/parameters.jsx, src/core/plugins/spec/actions.js, src/core/plugins/spec/reducers.js, src/core/plugins/spec/selectors.js, test/bugs/4557-default-parameter-values.js, test/core/plugins/spec/actions.js, test/core/plugins/spec/reducer.js, test/core/plugins/spec/selectors.js
Fixes https://github.com/swagger-api/swagger-editor/issues/1748.
This PR introduces the practice of storing parameter values based on the Immutable.js hashcode of the resolved Parameter Object, so that when the Parameter Object value changes (e.g., modifying the parameter's schema in Swagger Editor), a new example is created and stored as the value.
Essentially, parameters are now identified as unique by the hash of their definition in the document instead of path + method + name + in.
Video: http://recordit.co/Z0LaLs6fA5
=> Improvement: Hash-keyed Try-It-Out parameter value storage

src/core/components/models.jsx, src/style/_models.scss
Fixes https://github.com/swagger-api/swagger-editor/issues/1791.
This one took longer that it should have - I initially explored an implementation that sat between ModelWrapper and Model... it was not nearly as succinct.
The JumpToPath is prettier than before, IMO - it's in the top right corner of the Model container, instead of wedged next to the data itself:
=> improvement: re-enable and improve Models jump-to-path

package.json
for now!
reselect@3 has [a breaking change](https://github.com/reduxjs/reselect/releases/tag/v3.0.0) that impacts some of our use cases.
=> housekeeping: migrate back to reselect@2

package.json, src/core/plugins/oas3/helpers.js, test/core/plugins/oas3/helpers.js
This PR:
- Tightens our `isSwagger2` and `isOAS3` implementations to handle non-string values
- Fixes an edge case where `openapi: "3.0."` was being marked as valid OAS3
- Enables source maps in Mocha in order to get accurate stack trace line numbers
=>  improvement: handle more invalid Swagger/OpenAPI version values gracefully

docs/usage/configuration.md
This allows referencing a configuration parameter directly when responding to tickets or from within the documentation.
=> Added anchors to configuration parameters

src/core/components/online-validator-badge.jsx, test/components/online-validator-badge.js
Encode query string value for validator badge url; both link url and badge image url.
Fixes #4658 
All tests are passing.
=> Encode query string value for validator badge url

src/core/components/parameter-row.jsx, src/core/utils.js, test/e2e/scenarios/bugs/4756.js, test/e2e/specs/bugs/4756.yaml
This PR ensures that numerical initial values are always converted to strings, which brings the initial values that make it into state into line with the values resulting from user input.
Fixes #4756.
I added two new e2e tests.
=> fix(try-it-out): stringify numerical initial values in ParameterRow

src/core/plugins/spec/wrap-actions.js
=> fix: default to empty object for pathItems in `updateJsonSpec` wrap-action

src/core/plugins/auth/actions.js
- Inspect the error and error_description properties of the response, if available
In case an authorization request fails, the response code usually is (by RFC6479) a 400 or 401, and thus fn.fetch (from swagger-js) throws an error instead of returning the response body.
Swagger-js also returns the actual response in the error which is thrown, and by parsing that response and checking whether "error" and "error_description" are available, it's possible to help the user see why the Authorization Server rejected the authorization request (also by RFC).
This is an additional fix of #4048, in the Resource Owner Password Grant and Client Credentials flows, where the error message is returned as a JSON payload from the token POST request. See RFC 6479 for the spec: The return body is specified …
=> Additional fix of #4048, more error messages from authorization call

src/core/plugins/oas3/components/request-body.jsx
This PR improves the rendering and Try-It-Out UI for `application/x-www-form-urlencoded` and `multipart/*` object-schema Request Bodies.
Specifically:
- use a Media Type schema's `required` array for marking required properties
- don't use a generated schema value as a default
- improve the static/Try-It-Out layout to more closely mimic vanilla parameters
- use `property.default` and `property.example` as _initial_ values
Fixes #4643, and private issue ID `SWOS-39`.
Manually.
=> improvement: urlencoded Request Body rendering

src/core/plugins/samples/fn.js, test/core/plugins/samples/fn.js
Hide deprecated properties in schema examples
Showing deprecated properties in examples gives false impression that they are still current and should be used. This PR hides deprecated properties from examples shown in the UI, so new users are less likely to use deprecated properties by copy/pasting examples, or by using the examples as a form of ad-hoc documentation.
Deprecated a property, verified that it does not appear in the example section of a POST request body.
=> hide deprecated properties in examples

src/core/plugins/deep-linking/layout.js, test/e2e-cypress/tests/deep-linking.js
This PR adds logic to expand an Operation's containing tag when expanding the operation itself as a result of parsing a deep link fragment.
Fixes #4817.
This is a regression, if I had to guess, #4349 broke the functionality.
I added e2e tests!
=> fix(deeplinking): expand containing tag when expanding an operation

src/style/_layout.scss
Follow up to #4598
#4598 missed a reference to the `Titillium Web` font, which was previously provided by Google Web Fonts.
Clean up. We shouldn't reference this font anymore. It's not really urgent, as the font will only if there is a `@font-face` declaration for it somewhere. The `swagger-ui-express` project still does that in their template, which was how I noticed this: https://github.com/scottie1984/swagger-ui-express/blob/bef977310e04ea415d2510ce52ca2a923a038752/indexTemplate.html#L7
(~~~I'll make~~~ I have made a separate PR to that project to get that line removed: https://github.com/scottie1984/swagger-ui-express/pull/88)
Didn't test it to be honest.
=> Remove one remaining reference to Titillium (Google Web Fonts)

src/core/components/models.jsx, test/e2e-cypress/static/documents/bugs/editor-1868.yaml, test/e2e-cypress/tests/bugs/editor-1868.js
This PR uses Immutable's `size` property to detect invalidated subtree data, instead of checking for `undefined`.
#4542, which added the default `Im.Map()` fallback values, introduced this issue.
Fixes swagger-api/swagger-editor#1868.
I added an end-to-end test 😄
=> fix: resolved model data invalidation detection

src/core/plugins/oas3/components/request-body.jsx, src/core/plugins/oas3/wrap-components/parameters.jsx, test/e2e-cypress/static/documents/bugs/4838.yaml, test/e2e-cypress/tests/bugs/4838.js
This PR modifies OAS3 Parameters and OAS3 RequestBody to more kindly handle invalid request body values.
Fixes #4838.
Added a Cypress test case.
=> fix: gracefully handle empty request bodies

Dockerfile, docker-run.sh
- Adds `CONFIG_URL` to Dockerfile `ENV`
- Handles swapping `url` and `urls` with `configUrl` if specified
Fixes #4861
Built image locally:
```sh
docker build -t swaggerapi/swagger-ui:latest .
```
Run local image pointing `CONFIG_URL` to `http-server` containing `swagger-config.json`:
```sh
docker run -p 8080:8080 -e CONFIG_URL=http://localhost:8000/swagger-config.json swaggerapi/swagger-ui:latest
```
Open browser to localhost:8080
=> feat(docker): Allow configUrl to be used in Docker

src/core/components/layouts/base.jsx, src/core/containers/schemes.jsx, src/core/plugins/oas3/components/servers-container.jsx, src/style/_layout.scss, src/style/_servers.scss
Fixes #4857.
This PR:
- enables rendering for `SchemesContainer` children
- moves the `ServersContainer` within `SchemesContainer` for layout
=> improve: nest Servers within Schemes container

src/core/components/operation.jsx, src/core/plugins/deep-linking/layout.js, src/core/utils.js, test/core/utils.js, test/e2e-cypress/static/documents/features/deep-linking.openapi.yaml, test/e2e-cypress/static/documents/features/deep-linking.swagger.yaml, test/e2e-cypress/tests/deep-linking.js
This PR improves our Deep Linking implementation:
- Tags and operationIds that contain underscores and whitespace are now tested and working properly
- Operations lacking operationIds are now tested and working properly
- Tag and operationId whitespace is now escaped with `%20` instead of `_`
- Links relying on `_`-based escaping are still supported, but deprecated and tagged for removal in v4.0
Fixes #4895 and may also solve #4929.
I added new unit and integration tests, and modified a few existing ones.
There should be no breaking changes to overall functionality, as the new tests cover any gaps left by modifications to the existing tests.
=> bug(deeplinking): escaping is breaking whitespaces & underscored tags/ids

src/core/plugins/deep-linking/index.js, src/core/plugins/deep-linking/layout.js, test/e2e-cypress/static/documents/features/deep-linking.openapi.yaml, test/e2e-cypress/static/documents/features/deep-linking.swagger.yaml, test/e2e-cypress/tests/deep-linking.js
1. let `deep-link` plugin to support the UTF-16 fragments
`npm run e2e-cypress`
```
Deep linking feature
in Swagger 2
UTF16 fragments with `docExpansion: none` enabled
✓ should expand the tag(шеллы) (1164ms)
✓ should expand the operation(пошел) (1257ms)
in OpenAPI 3
UTF16 fragments with `docExpansion: none` enabled
✓ should expand the tag(шеллы) (1265ms)
✓ should expand the operation(пошел) (1143ms)
```
=> ref #3958, support utf16 fragments on the deeplink plugin

src/core/utils.js, test/core/utils.js
Implement an extractor for filenames encoded in RFC5987 style.
At current moment, it is not possible to download a file named in UTF-8 encoding.
Manually tested on follow strings:
`attachment; filename*=UTF-8''"%D1%81%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D1%8F.xlsx"`
`attachment; filename*=UTF-8''%D1%81%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D1%8F.xlsx`
`attachment; filename="details.xlsx"`
`attachment; filename=details.xlsx`
Also added new unit tests.
=> Add support of RFC5987 for Content-Disposition

src/core/plugins/deep-linking/layout.js, test/e2e-cypress/tests/deep-linking.js
This PR breaks rewriting of deprecated fragments (unreleased, introduced in #4953) in favor of retaining correct fragments.
Fixing both requires expanding the deep linking plugin to have knowledge of the document's contents: given `#/my_tag/my_operation`," is this a deprecated fragment referencing `my tag` + `my operation`, or a valid fragment referencing `my_tag` + `my_operation`" can only be answered by looking at the document itself.
I don't have time to do this before release, so I'm patching this in the most forward-friendly way until a full fix can be made. A successor ticket will be made to address these concerns.
=> improve: deeplinking behavior

package-lock.json, package.json, src/core/plugins/samples/fn.js
This PR migrates Swagger UI to using [my browser-compatible fork of `xml`](https://www.npmjs.com/package/@kyleshockey/xml).
Addresses (likely fixes) #4971.
_Bonus: this fixes a logical error I made in #4984 - `webpack-dev-server` is now actually in devDependencies._
=> housekeeping: `xml` -> `@kyleshockey/xml`

Dockerfile, docker/configurator/helpers.js, docker/configurator/index.js, docker/configurator/oauth.js, docker/configurator/translator.js, docker/run.sh, docs/usage/configuration.md, docs/usage/oauth2.md, test/docker/oauth.js, test/docker/translator.js
This PR extends the Docker configurator to create, when necessary, `ui.initOAuth` blocks so that Docker users can manage OAuth credentials more easily.
Fixes #4957.
Fixes #3467.
I added unit tests, and manually confirmed that the functionality is working as expected.
=> feature: Docker OAuth block support

src/core/plugins/oas3/spec-extensions/wrap-selectors.js, src/core/plugins/spec/wrap-actions.js
Fixes #4813 by resolving referenced security schemes.
securitySchemes were up till now not resolved.
The spec allows for them: https://swagger.io/specification/#componentsObject.
By providing a schema where this is the case.
I could not find how to make an automated test for this.  If this is needed, I will require some pointers on where to do it.
=> Fix #4813 resolve referenced securitySchemes

src/core/plugins/samples/fn.js, test/core/plugins/samples/fn.js
Adds an example value provider for "date" format strings.
Given:
```
"properties": {
"myDateField": {
"type":"string", 
"format":"date"
}
}
```
Should provide an example ISO-formatted date-only string, such as
```
"2018-11-13"
```
Previously, these fields would be represented in request/response "Example Value" payloads as simply "string". This change provides semantic context, similar to other primitive values (number, boolean, etc).
Added unit tests to cover sample values for both "date" and "date-time" formats.
=> add primitive factory method for string/date

src/core/plugins/samples/fn.js, test/core/plugins/samples/fn.js
=> fix: prevent object inheritance mutations in recursive sampleXmlFromSchema calls

src/plugins/topbar/topbar.jsx, src/style/_topbar.scss, test/e2e-cypress/static/configs/urls-primary-name.yaml, test/e2e-cypress/static/configs/urls.yaml, test/e2e-cypress/static/documents/features/urls/1.yaml, test/e2e-cypress/static/documents/features/urls/2.yaml, test/e2e-cypress/tests/features/urls.js
=> fix: `urls.primaryName` functionality regression

src/core/components/operation-tag.jsx, test/e2e-cypress/tests/features/deep-linking.js
This PR updates `operation-tag.jsx` to bring tag deep linking in line with the operation-level implementation's escaping and spacing.
Fixes #5047.
I added many new automated tests, plus manually tested against the deep linking definitions and the repro definition provided in #5047.
=> fix: tag deep link escaping inconsistencies

docs/usage/deep-linking.md
=> housekeeping: indicate index.html usage of deepLinking flag

src/core/components/info.jsx
This makes it easier to style them individually or retrieve the elements in user scripts. We’re not assigning any style to those CSS classes, just the classes to the elements; because some of them are optional, they cannot be retrieved by (or styled with) an nth-child scheme.
This makes user CSS like the following work better:
/* these will break once we use externalDocsUrl */
.info > :last-child:before {
content:"Licence: ";
}
.info > :nth-last-child(2) > div:before {
content:"Developer: ";
}
The goal behind this is to allow the user some minimal styling in the `index.htm` file that runs swagger-ui-dist, without having to learn just another programming language. This is the first half of this (being able to style the individual information items); the second half (being able to add a …
=> feature: add individual CSS classes to info items

src/core/plugins/oas3/spec-extensions/wrap-selectors.js, src/core/plugins/spec/selectors.js, test/core/plugins/oas3/wrap-spec-selectors.js, test/core/plugins/spec/selectors.js
=> fix: non-typesafe spec selector

docs/usage/oauth2.md
Fixed a tiny typo.
I stumbled across this while reading through the docs. It bothered me and I hope to fix this, so it shall never bother other people.
No PR to small I guess...
Eyeballs 👀 
No, you don't want me to, do you?
=> Tiny typo in oauth2.md

Dockerfile, docker/cors.conf, docker/nginx.conf, docker/run.sh
Prevent nginx from caching json/yml/yaml files so that you can see changes once you edit a Swagger/OpenAPI definition mounted into the container.
This required some *painful* refactoring to the nginx config. Due to hitting:
* https://www.nginx.com/resources/wiki/start/topics/depth/ifisevil/ &ndash; People just have to keep using that in samples around the internet do they... What an unfortunate name choice for that directive that makes people thinks it's sane...
* The sample using `map` for `expires` in this web page: http://nginx.org/en/docs/http/ngx_http_headers_module.html#expires is wrong since `sent_http_content_type` is *not* set for a "304 Not Modified" response. Hours wasted...
* `add_header` is annoying and removes all headers feom upper scopes when it's used in a lower one.
* …
=> Make json/yml/yaml files no-cache in Docker nginx config

src/core/index.js, test/e2e-cypress/static/pages/5138/api-with-examples.yaml, test/e2e-cypress/static/pages/5138/index.html, test/e2e-cypress/static/pages/5138/uspto.yaml, test/e2e-cypress/tests/bugs/5138.js
=> fix: don't trigger `url` remote document load if `urls` is provided

src/core/components/providers/markdown.jsx, test/e2e-cypress/static/documents/bugs/5060.yaml, test/e2e-cypress/tests/bugs/5060.js
=> fix: generate non-smart Markdown quotes

src/core/plugins/oas3/components/request-body.jsx, test/e2e-cypress/static/documents/bugs/5164.yaml, test/e2e-cypress/tests/bugs/5164.js
=> fix: coerce multipart initial property values to string

dev-helpers/doc.yaml, src/core/components/operation-summary-path.jsx, src/style/_layout.scss, test/e2e-cypress/tests/bugs/4867.js
Fixes https://github.com/swagger-api/swagger-ui/issues/5171.
- Balances the flex characteristics of the path and summary elements
- Adds kind word wrapping that preserves words if possible
- Injects zero-width spaces into paths for better line breaks; intercepts copy events to remove the ZWSPs from paths
=> improvement: operation path + summary overflow styling

Dockerfile, docker/nginx.conf
Similar to PR https://github.com/swagger-api/swagger-editor/pull/1953
The purpose is to reduce the loading time by reducing the amount of data transferred.
With a simulated 100 mbps internet connection :
* before :
* after :
`gzip_static` reduces the CPU used by nginx, by avoiding to gzip files for each request.
It reduces loading time by 700-800ms (and even more on a slow internet connection).
I compared network tab in Chrome Developer Tools with and without gzip.
=> Add gzip compression in nginx configuration to reduce file size

src/style/_information.scss, src/style/_markdown.scss, src/style/main.scss
Add a `.info pre` and `.info pre code` override to fix code block styling
Fixes #3117 
Code blocks are currently styled incorrectly as they do not have any styles associated with them, and instead use the inline code style which makes them look strange. 
Manually using Webpack dev server running locally. The screenshots are from that 
Before 
After
=> Fix pre styles for block code

flavors/swagger-ui-react/README.md, flavors/swagger-ui-react/index.js
Adds a `initialDocExpansion` prop to swagger-ui-react which acts a value for swagger-ui's docExpansion configuration setting.
I needed to be able to set docExpansion to "full" so that my APIs swagger-ui-react was fully expanded by default. This allows that through an `initialDocExpansion` prop. I've added the "initial" prefix to re-enforce that this prop is only applied on mount.
Manually added the same changes to the transpiled JS in the swagger-ui-react npm package. Correct behaviour observed.
> The new prop is not marked as required, if omitted `swagger-ui`'s default value (`list`) will kick in (as per current behaviour).
> Just the `swagger-ui-react` readme.
> There is no testing in place for `swagger-ui-react` yet.
=> improvement: expose docExpansion setting as a prop in swagger-ui-react

release/get-changelog.sh
I've been using a new style for release notes, this reflects that.
The new changelog generator now sorts items as we like them, and pulls in stray commits that may not be to the Angular convention's liking, but we may still want present.
=> housekeeping: make release note generator more flexible

src/core/components/providers/markdown.jsx, src/core/plugins/oas3/wrap-components/markdown.jsx
=> fix: refuse to render non-string Markdown field values

flavors/swagger-ui-react/release/create-manifest.js
...by setting the `REACT_FLAVOR_VERSION_IDENTIFIER` env var
=> housekeeping: allow overriding `swagger-ui-react` version

src/core/components/models.jsx
Added check `isShown` to <ModelCollapse />'s prop `expanded` logic
Amended prop `expanded` for ModelCollapse component in Models component
Need to expand a Model/Schema outside of component using `layoutActions.show()`
SwaggerUI was run locally and `layoutActions.show(["models", "ModelName"], true)` was triggered in console
None.
=> Added support to allow Models/Schemas to be expanded

src/core/components/layout-utils/drop-down.jsx, src/core/components/schemes.jsx
Dropdown bug fix and small enhancement
Update dropdown to:
- pass props into onChange function to accommodate parts of swagger-ui that need to access the attributes they passed in.
- to select default selectedKey in onComponentUpdate (fixes issue when values available on first render)
Replacing selects with the custom one shed light on issues.
Manually
=> Dropdown improvements

.github/lock.yml
a gesture of kindness towards @hkosova's inbox
(this will likely be reverted once the script finishes processing the backlog of issues)
=> housekeeping: silence lock bot for initial wave of actions

package.json, test/e2e-cypress/support/index.js, webpack-hot-dev-server.config.js
problem: sometimes, the JavaScript file for the Standalone plugin gets truncated, which breaks Cypress in mysterious ways:
I only know that it's the Standalone plugin because this happened on my local machine _once_ a week ago and took notes on the failure. Hasn't happened outside of CI since.
=> housekeeping: address inconsistently truncated Standalone Plugin responses within Cypress tests

src/core/components/response.jsx, test/e2e-cypress/static/documents/bugs/5458.yaml, test/e2e-cypress/tests/bugs/5458.js
=> fix: Swagger 2.0 `Response.examples`

src/core/components/response.jsx, test/e2e-cypress/static/documents/bugs/5458.yaml, test/e2e-cypress/tests/bugs/5458.js
Fixes #5458, avoids a mistake I made in 9749a4785.
=> fix: Swagger 2.0 `Response.examples`, again

flavors/swagger-ui-react/release/run.sh
[`swagger-ui-react@3.23.1`](https://unpkg.com/swagger-ui-react@3.23.1/) is broken because `index.js` is empty:
This is because Babel failed in the release job ([`oss-swagger-ui-release-react#10`](https://jenkins.swagger.io/view/OSS%20-%20JavaScript%20Releases/job/oss-swagger-ui-release-react/10/console)), but the job continued to run, release, and succeed:
It also starts using `mkdir -p` so that "already exists" errors from that command don't cause the job to fail.
=> housekeeping: fail React flavor release if a step fails

Dockerfile
Change file permissions so that a non root user can run the container.
Currently the container is built for running as root. However, in some circumstances it is desired to not run as root. Currently this simply fails (see log below). This change grants the necessary permission on the files, so that the server starts up, even when the effective user is not root.
Running the container with a non-root user simply fails:
~~~shell
$ docker run --rm -ti -u 1 docker.io/swaggerapi/swagger-ui:latest
fs.js:115
throw err;
^
Error: EACCES: permission denied, open '/usr/share/nginx/html/index.html'
at Object.openSync (fs.js:439:3)
at Object.writeFileSync (fs.js:1190:35)
at Object.<anonymous> (/usr/share/nginx/configurator/index.js:38:4)
at Module._compile (internal/modules/cjs/loader.js:689:30)
at …
=> Allow this to run in a non-root enviroment

src/core/plugins/oas3/components/request-body.jsx, test/e2e-cypress/static/documents/bugs/5455.yaml, test/e2e-cypress/tests/bugs/5455.js
=> fix: use `null` as a notSetValue for examplesForMediaType

src/core/components/response.jsx, test/e2e-cypress/static/documents/bugs/5453.yaml, test/e2e-cypress/tests/bugs/5453.js
=> fix: empty ModelExample rendering in a Response w/o `content` 

package-lock.json, package.json
=> fix: move `@babel/runtime-corejs2` to production dependencies

src/core/components/providers/markdown.jsx
This PR removes a regex-based optimization in the Markdown provider. It's overreaching a bit and doesn't give us any big known performance gains, so out it goes!
* Fixes https://github.com/swagger-api/swagger-ui/issues/5475.
* Fixes a bug weighing heavily on @webron's mind.
=> fix: remove problematic Markdown optimization

package-lock.json, package.json, src/core/components/parameter-row.jsx, src/core/json-schema-components.jsx, src/core/openapi-helpers.js, src/core/plugins/spec/actions.js, src/core/utils.js, src/helpers/get-parameter-schema.js, test/core/helpers/get-parameter-schema.js, test/core/utils.js, test/e2e-cypress/static/documents/bugs/4442.yaml, test/e2e-cypress/tests/bugs/4442.js
This PR:
* adds support for `Parameter.content.schema`
* always uses first media type defined in `content` as the parameter's `schema` for..
* documentation rendering
* sample generation
* runtime parameter validation
* adds support for `Parameter.content.example` for initial parameter values
Note that this PR is missing support for `Parameter.content.examples`, which was omitted in the interest of time. As far as I can tell, the spec doesn't disallow use of `Parameter.examples` in conjunction with `Parameter.content`, so this shouldn't block any functionality.
Likewise, no code was added for `MediaType.encoding` since the `encoding` field does not apply to `Parameter.content` Media Type Objects.
Fixes SWOS-35, fixes #4442.
Unit tests for helper functions were added. TODO: Cypress tests.
=> feature: support for `Parameter.content`

src/core/utils.js
Fixes #5581 .
Curiously, before #5571, runtime validation was failing open for all body parameters. Solving that issue in #5571 exposed a flaw in validating required `type: object` values in 2.0, which we deal with here.
=> fix: object parameter validation

src/core/json-schema-components.jsx, test/e2e-cypress/tests/bugs/5452.js, test/mocha/components/json-schema-form.jsx
=> fix: <Select disabled> for `type: string` + `enum` schemas

src/core/utils.js, test/mocha/core/utils.js
=> fix: accept string-represented values in required array runtime validation

README.md
HTTPS relevant links on README. Prevents redirects
Faster and safer.
the HTTPS links work.
=> HTTPS relevant links on README

src/core/components/parameter-row.jsx, src/core/utils.js, src/helpers/get-parameter-schema.js, test/mocha/core/helpers/get-parameter-schema.js, test/mocha/core/utils.js
=> fix(validateParam): validate JSON parameter values + support `Parameter.content`

docs/development/setting-up.md
Update prerequisites to recommend using latest version of Node.
Consistency of documentation between swagger-ui and swagger-editor.
Refs: [Required Fix for swagger-editor](https://github.com/swagger-api/swagger-editor/pull/2118)
I can confirm that node v6.17.1 still does work locally (MacOS Catalina), despite the documentation change.
v8.17.0, v10.10.0, v12.16.1, and v13.9.0 also still work
=> docs: update prerequisites for development

src/core/components/parameter-row.jsx
Swagger UI has the [`showCommonExtensions`](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#user-content-showcommonextensions) option that displays the `maximum`, `minimum`, `maxLength`, `minLength`, and `pattern` attributes for primitive parameters in OAS2 definitions. This PR makes this work for OAS3 parameters as well.
Fixes #5016.
Manually.
Here, Swagger UI is configured with `showCommonExtensions: true`.
=> improvement: showCommonExtensions support for OAS3 parameters

docs/development/setting-up.md, src/core/plugins/oas3/wrap-components/online-validator-badge.js
The `online-validator-badge.js` now returns `OnlineValidatorBadge` instead of `null`. 
- The 3.0 wrapper for `OnlineValidatorBadge` previously returned `null`. This was done because the external online validator tool previously did not support OAS3 specs.
- Instead of "unwrapping" as a possible solution, this fix maintains the 3.0 wrapper for `OnlineValidatorBadge`, in case the wrapper is needed again in the future.
- This fix is independent of the external online validator tool. It is simply a display fix (to always be visible).
On local, I had to manually input the url into the topBar, as provided by a comment in the ticket (https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml).
Pre-fix, the green validator badge was not be visible.
post- fix, …
=> Fix: #5669 online validator badge

src/core/json-schema-components.jsx, src/core/plugins/view/root-injects.jsx
~Add a `process.env.NODE_ENV` check before logging a warning of a missing getComponent~
New: getComponent has a config object as a third, optional parameter
using the config object requires the presence of the second parameter, container
e.g. getComponent("JsonSchema_string_whatever", false, { failSilently: true })
JsonSchemaForm specifically now optionally suppresses the warning.
extending #2931, where this is generally a safe warning and nothing needs to be done by the user. so we should silence the warning in production mode. 
tested manually using different NODE_ENV + CRA
dev mode, easiest to identify with query parameter, e.g. http://localhost:3200/?docExpansion=full
=> housekeeping: prevent log warning for missing getComponent in production

src/core/json-schema-components.jsx, src/core/plugins/view/root-injects.jsx
squash commits from review in PR #5919
have a clean commit history
N/A. already tested from PR #5919
=> housekeeping: prevent log warning for missing getComponent in production #5919

docs/customization/plugin-api.md
Add explanation and code example for `getComponent` with `failSilently` option
documentation to accompany merged #5919 and #5940 
n/a
=> docs: update plugin api component for failSilently

package.json, src/core/components/parameter-row.jsx, src/core/json-schema-components.jsx, src/core/plugins/oas3/wrap-components/json-schema-string.jsx, src/core/plugins/view/root-injects.jsx, test/e2e-cypress/static/documents/features/schema-form-core.yaml, test/e2e-cypress/static/documents/features/schema-form-missing-values.yaml, test/e2e-cypress/tests/features/schema-form.js, test/mocha/components/json-schema-form.jsx
issue #5951
- JsonSchema-based components are now ImmutableJS-compliant
- JsonSchemaForm now properly defaults to JsonSchema_string for invalid or unknown types, as well as unable to getComponent cases
- JsonSchema_array now uses a simplified JsonSchemaArrayItemText component
- JsonSchema_array handles its own subcomponent render logic, rather than recursing from its JsonSchemaForm parent
- Additional validation checks to confirm that "schema" keys, "schema" values, and ImmutableJS methods exist
- schema
- type
- format
- enum
- bug (separate pre-existing): Debounce error if string value is null
- Existing Mocha `json-schema-form` test now uses ImmutableJS parameters instead of plain objects
- New Cypress tests for `schema-form`
- Added new dev Cypress `open` scripts
- If an API …
=> ft: JsonSchema components are now ImmutableJS compliant (#5951)

src/core/components/execute.jsx, src/core/containers/OperationContainer.jsx, test/e2e-cypress/tests/bugs/5070.js
Remove clearValidation function from onClick of Try It Out. As a result, the red error field will remain red.
In addition, the input box will now also re-bounce on subsequent onClick of "Execute"
From #5070, Clicking on Try It Out button also calls a function that clears the validation errors that might be present. It can be confusing to the user that the error appears to have gone away when the red validation fields disappears. However, the error is actually still present, and Execute will not fire off an actual request (this part is ok and expected)
new cypress test included in this PR
=> bug: remove clearValidation from onTryoutClick (#5070)

src/core/curlify.js, src/core/utils.js, test/mocha/core/curlify.js
- Requires merging of PR from Swagger Client, https://github.com/swagger-api/swagger-js/pull/1527
1. SwaggerClient returned incorrect FormData object that did not support multiple key names. This is now fixed in SwaggerClient.
2. SwaggerUI utils.fromJSOrdered
a. Immutable's OrderedMap does not support duplicate keynames, and will overwrite with new value(s)
b. We now create an object, if multiple, where a hashIndex is appended to the original keyname, along with a counter
c. If multiple, the original key name (without hashIndex) is deleted
d. This object is returned and used to change state for spec.mutatedRequest
e. curlify.js is modified to check for presence of hashIndex, and is able to extract the original key name to push into its return array (to join into String)
3. Sidenote, …
=> fix: curl entries array support within multipart/form-data (#3838)

src/core/curlify.js, src/core/json-schema-components.jsx, src/core/utils.js, test/mocha/core/curlify.js
oas3 - files
oas2 - file
- Fixes OAS2 file upload regression where validation errors did not clear.
- Fixes OAS3 uploading array of files
Fixes #5997. Also related to #3838. Followup to https://github.com/swagger-api/swagger-ui/commit/5eb23cdd48542be8f4df0f6a4764135821eb7aa1
=> fix: jsonSchemaComponent file/files

package.json
fix the script name to open cypress
fix the script name to open cypress window. there was an incorrect name reference
run `npm run dev-e2e-cypress` should open the cypress window
=> housekeeping: update dev-e2e-cypress-open script name

src/core/utils.js, test/e2e-cypress/static/documents/bugs/6016-oas2.yaml, test/e2e-cypress/static/documents/bugs/6016-oas3.yaml, test/e2e-cypress/tests/bugs/6016.js
Add a `isFunction` check to determine how to handle `js.entries`. E.g. as plain property name vs. FormData instance
Fixes #6016 
New Cypress tests with OAS2 and OAS3.0 samples confirm proper rendering. Also confirmed multipart/form-data try-it-out still working.
=> fix: entries as property name

test/e2e-cypress/tests/bugs/4641.js
Ref #6001
Refactor existing tests that should avoid timeouts.
In Cypress, the `.should` command asserts an explicit argument against a single value. In this case, we want to be able to place multiple assertions. Therefore, this change utilizes the `.then` callback for `.its` command, to which we can inspect various elements and make multiple assertions. Using a callback also ensures that the request was completed before we make a set of assertions
Note, for 2 of the 3 tests, since the assertion is on a specific known argument and expected value, it is possible to utilize `.should`, albeit with structural change. e.g.
```
.its('some.very.specific.target)
.should('eq', value1)
.should('not.have.value', value2)
```
The existing test in /bugs/4641.js intermittently fails on CI.
Fixes #6001 …
=> test: improve reliability of /bugs/4641

src/core/utils.js, test/e2e-cypress/tests/bugs/6016.js
Ref: #6033
PR #6025 fix to `entries` was over-strict on handling `js.entries`. The extra handling for an `js` object that may have contained `.entries` as a key has been removed. The `js` object is now processed in its entirety without further modification.
Fixes #6033 
The render failure to expand `Models` was not previously covered in PR #6025.
Additional tests to expand both the `Operation` and `Models` have been added.
=> fix: remove special handling of non-FormData entries

src/core/plugins/auth/reducers.js, test/e2e-cypress/tests/bugs/4641.js
also... 
fix: apply isFunc check for security.getIn
For `bugs/4641` test, after `.get()` an operation ID, add a `.click()` to expand the model view. Now Cypress should be able to select and click on the "Try-It-Out" button (and then select and click on "Execute")
Also, using `opblock-summary` had 2 issues:
1. In an expanded model, `opblock-summary` appears in multiple cases, so Cypress is unable to determine which to use
2. In a closed model, `opblock-summary` still appears, and no "Try It Out" element exists
In addition, this PR applies a fix, to validate that `securities.getIn()` is a function. This console error would appear during the `bugs/4641` test, even though all tests still pass. Applying this fix also results in all existing tests passing.
Second attempt
fixes #6001 
Trying …
=> fix: bugs/4641 flaky test

test/e2e-cypress/tests/bugs/4641.js
Per [Cypress Docs](https://docs.cypress.io/api/commands/as.html#Route) example for `.as`, use `cy.wait('@routeAlias')` instead of `cy.get()`. Reason: `cy.get()` will retry until resolved or timeout, while `cy.wait()` will wait until resolved.
3rd effort...
Fixes #6001 
tests continue to pass locally
=> fix: bugs/4641 use wait on route alias

Dockerfile, docker/run.sh
This PR simply allows for an URL option to provide the initial json/yml for `swagger-ui`.
The `SWAGGER_JSON` parameter requires the provided path to be a local file, the new `SWAGGER_JSON_URL` parameter also allows URLs
This is a followup of https://github.com/swagger-api/swagger-ui/pull/5941 because someone force pushed master and I had to start from scratch
=> Allow Docker image to receive a URL

src/style/_form.scss
Unknown why it was added, but it makes swagger-ui look horrible on a
decent laptop in a tiling wm
Signed-off-by: Wesley Schwengle <wesley@opndev.io>
Before:
After:
=> Remove max-width for textarea media < 768px

docker/configurator/variables.js, docs/usage/configuration.md, src/core/components/array-model.jsx, src/core/components/auth/api-key-auth.jsx, src/core/components/auth/basic-auth.jsx, src/core/components/auth/oauth2.jsx, src/core/components/example.jsx, src/core/components/headers.jsx, src/core/components/info.jsx, src/core/components/object-model.jsx, src/core/components/operation-tag.jsx, src/core/components/operation.jsx, src/core/components/parameter-row.jsx, src/core/components/primitive-model.jsx, src/core/components/providers/markdown.jsx, src/core/components/response.jsx, src/core/plugins/oas3/components/callbacks.jsx, src/core/plugins/oas3/components/http-auth.jsx, src/core/plugins/oas3/components/operation-link.jsx, src/core/plugins/oas3/components/request-body.jsx, src/core/plugins/oas3/wrap-components/markdown.jsx, test/mocha/components/markdown.jsx
This commit changes markdown sanitization behaviour in following way:
class, style and data-* attributes are removed by default. These attributes
open possible vulnerability vectors to attackers.
The original behavior of sanitizer (before this commit) can be enabled by *useUnsafeMarkdown* configuration option.
Use this configuration option with caution and only in cases when you know
what you're doing.
=> fix(Markdown): render markdown in more secure way

src/core/curlify.js, test/mocha/core/curlify.js
In `curlify`, the `type` would overwrite the string value to the latest header value. In the case of using `requestInterceptor` that appends a header, the final string would be whatever was provided by the `requestInterceptor`.
This fix will try to update `isMultipartFormDataRequest` until it is `true`.
This change also reorganizes and fixes the linting in the `curlify` test file
Fixes #6082
New mocha tests that places leading/trailing custom header. There already exists a mocha test with no custom header. Note, although the term `custom` is used, any header and order should not impact the curlify result.
=> fix: curlify agnostic to order of header values

webpack/bundle.babel.js
As versions of libraries that are both used by swagger-js and swagger-ui
may diverge in time, we must use webpack resolve aliases to make sure
that only one version of these libraries gets bundled.
=> build(webpack): make sure we're not bundling same deps twice

webpack/_config-builder.js, webpack/bundle.babel.js
As resolving applies to everything and not just specific builds
the resolve.aliases have been moved to one common place.
=> build(webpack): move resolve alises to one common place

src/core/containers/OperationContainer.jsx, src/core/plugins/swagger-js/index.js
Import of helpers from swagger-client worked because of the fact
that commonjs exports are basically an objects that can be destructured.
Whenever swagger-client switches to ES6 imports as primary mechanism
of webpack consuptions imports like that will fail. This change makes
sure that import mechanism is both compatible with ES6 and commonjs
import systems.
Along with that rename default import of swagger-client
to more appropriate SwaggerClient.
=> refactor(swagger-client): fix import of helpers

package-lock.json, package.json, src/core/containers/OperationContainer.jsx, src/core/plugins/swagger-js/index.js
swagger-client in versions >3.10.9 exports it's build artifacts in multiple way.
One artifact is exposed as ES5 compatible code with ES6 imports.
We use this fact to utilize webpack tree shaking algorithm.
This commit decreases bundle size for around 10%.
We're now using undocumented symbols from swagger-client library so we have to
be really careful not to change how files and exports are organized in swagger-client.
Using proper build fragments for proper usecases and decreasing the bundle size.
Manually by testing resulting built bundle
=> build(bundle): use ES6 to import swagger-client symbols

src/core/components/parameter-include-empty.jsx, src/core/plugins/oas3/components/request-body.jsx, test/e2e-cypress/static/documents/features/petstore-only-pet.openapi.yaml, test/e2e-cypress/tests/features/oas3-request-body-allow-empty-values.js
- Change default behavior of #5830 to "allow empty values".
- Provides a hook for future implementation to assign a configuration variable
Fixes #6203
Changes default to "allow empty values", instead of "skip empty values"
new cypress tests
=> feat(RequestBody): set default true for 'send empty value'

webpack/_config-builder.js
Increase webpack `maxEntrypointSize` and `maxAssetSize` from 1000 KiB to 1024 KiB
Temporary build size increase. Plan for size audit, where we actually want to try to get down to <975KiB
=> config: increase max bundle size to 1024 KiB

webpack/_config-builder.js, webpack/bundle.babel.js
Enable webpack options for LodashModuleReplacementPlugin, and specifically enable `memoizing`.
There has been efforts to change memoizing libraries. `lodash.memoize` has been added/removed multiple times, and currently swagger-ui uses both `lodash.memoize` and `memoizee`. So webpack should not remove native `lodash.memoize` with its own alternative.
=> build(webpack): enable lodash options

flavors/swagger-ui-react/README.md, flavors/swagger-ui-react/index.js
fix merge conflicts and update docs from PR #5624
resolve #5624 
n/a
=> Svn1991 make show mutated request react prop available

flavors/swagger-ui-react/README.md, flavors/swagger-ui-react/index.js
Fix merge conflicts and update docs for PR https://github.com/swagger-api/swagger-ui/pull/5386
resolves #5386
=> Tmkasun ft/5367 support passing presets and default models expand depth

src/core/plugins/spec/actions.js, test/mocha/core/plugins/spec/actions.js
ref: #4778
* Use async/await to handle cases where requestInterceptor returns a Promise instead of a resolved value.
* Also add `setResponse: createSpy()` to test spec, to suppress pre-existing error report of a missing function (even though tests still passed).
Fixes #4778
replaces and resolves #5499, #5607
unit test updated, new test added
=> fix(requestInterceptor): use async/await to support return new Promise

src/core/plugins/oas3/components/servers.jsx, test/e2e-cypress/static/documents/features/oas3-multiple-servers-switch.yaml, test/e2e-cypress/static/documents/features/oas3-multiple-servers.yaml, test/e2e-cypress/tests/features/oas3-multiple-servers.js
* Implement fix from #5759
* Implement Cypress tests for selecting from multiple OAS3 servers from different api definitions
Resolves #5759 with tests
New Cypress tests added for UI.
=> fix(OAS3): servers component update on definition change

flavors/swagger-ui-react/release/run.sh, flavors/swagger-ui-react/release/template.json
* sync with `babel.config.js` and env
* commonjs module entry point moved from `index.js` -> `commonjs.js`
* es module entry point -> `index.js`
PR #6291 changed the babel config file to `babel.config.js`
This PR syncs to the change, and adds an es module output
run.sh runs without non-npm publish errors.
=> feat(swagger-ui-react): es module

src/core/components/model-collapse.jsx
ref #6305
add a check that method exists prior to call it.
Ref #6305
Cypress test of "model-collapse", with manual review of dev console.
Note:  there will be a separate followup PR that will remove the need for manual review
=> fix(Models): onLoad should check this.props.layoutSelectors method

test/e2e-cypress/support/index.js
* replace `throw err` with `return true` to make Cypress fail test in both headless and non-headless mode
* remove logging of unmodified error
* also remove broken file logging
Cypress was not failing tests on `uncaught exception` errors, even though they are visible when running in dev mode (console).
ref #6305, PR #6307 
manually toggle/revert PR #6307 will now fail the `model-collapse` test appropriately. In addition, when failing `model-collapse`, other related cypress tests also now fail (as expected).
=> fix(cypress): tests should fail on uncaught exception

test/e2e-cypress/tests/features/deep-linking.js
Use native `cy.location()` directly instead of inspecting the window object via `cy.window()`
Preparation to migrate to Cypress@4.x, as this is a breaking test file in Cypress@4.x
test file is updated
=> fix(cypress): deep-linking tests should use cy.location

package-lock.json, package.json, test/e2e-cypress/helpers/multiple-examples.js, test/e2e-cypress/tests/features/multiple-examples-core.js
* includes prismjs@1.21.0 security update
* fix(cypress): use less restrictive 'include.text' assertion
* update react-syntax-highlighter from 12.2.1 to 13.5.0
* update Cypress `multiple-examples` tests to use a less restrictive `include.text` assertion instead of `have.text`. This change is backwards compatible with `react-syntax-highlighter@12.2.1`.
Addresses security update fixed in `prismjs@1.21.0`. 
Note, `prismjs` is a dependency of `react-syntax-highlighter`, but swagger-ui does not use `prismjs` within `react-syntax-highlighter`
Also, `react-syntax-highlighter@13.x` also changes output from `react-syntax-highlighter@12.2.1`. Specifically adding leading and trailing double-quote to the `<code>` section. Cypress tests have been updated to reflect this change.
before (v12):
after …
=> chore(deps): update react-syntax-highlighter from 12.2.1 to 13.5.0

src/core/plugins/err/error-transformers/hook.js, src/core/plugins/err/reducers.js
* remove  use of `system.getSystem()` inside the `err` reducer
* assign empty `{}` to pass to one of the `err-transformer` methods as temporary solution. Note, `system.getSystem()` was used to retrieve the jsonSpec, but then not yet implemented.
This PR does NOT resolve a separate issue regarding migration to `redux@4` and `react-redux@5`
Swagger Editor render error when using various sample api definitions. Example from swagger-editor unit test:
```
swagger: '2.0'
securityDefinitions:
api_key:
type: apiKey
name: apikey
in: query
scopes:
asdf: blah blah
paths:
/:
get:
description: asdf
security:
- api_key:
- 'write:pets'
```
swagger-editor visual render without console errors
Note, existing swagger-ui tests do not catch this error
=> fix: remove unused non-compliant system method inside 'err' reducer

src/core/plugins/oas3/components/servers.jsx, test/e2e-cypress/static/documents/bugs/6351.yaml, test/e2e-cypress/tests/bugs/6351.js
This fix allows the current server to dictate the selected server option in the servers dropdown. This allows for programatic changing of the servers component via the `oas3Actions.setSelectedServer` method.
Fixes #6351 
Resolves issues where swagger-ui does not correctly update when the server is set programmatically.
Cypress automation tests
Swagger-ui tested and interacted via console
=> Fix 6351: Server select usable via oas3Actions

.gitignore, docs/development/setting-up.md
Add `dev-helopers/examples` directory to `.gitignore`. This directory is for dev use to test various local json/yaml files, and is convenient when frequently examining different json/yaml files.
Manual changes to `dev-helpers/index.html` is still required for testing, and should not be committed. A user still could use the `dev-helpers` "root" to place their sample api definition.
Also, although this PR doesn't require a change to documentation, I updated the documentation anyways. 😉 
Keep git clean
Manually changing the url in `dev-helpers/index.html` still works
=> chore: update .gitignore with dev-helpers/examples

src/core/curlify.js, test/unit/core/curlify.js
Call `replace` with a global regex argument so that all occurrences are replace.
In #6245 I forgot that calling `replace` with a string as the first
argument replaces only the first occurrence of the string. In order to
replace all occurrences, we need to use a regex with the global (g)
modifier.
Sorry. 😖 
Fixes escaping of curl requests that have two dollar signs (see the test for a complete example)
Added a unit test
=> fix(curlify): replace all occurrences of `$`

src/style/_markdown.scss
Adds `overflow-wrap: break-word` to `<pre>` blocks in markdown.
In Swagger UI version 3.24.1 (November 2019) a CSS change was made to `_layout.scss` that added the `.microlight` class to the `.opblock-body pre` selector. (#5673)
Prior to this change, a `<pre>` block in an operation description that contained long text content with no spaces or other natural break points would automatically wrap onto new lines, because the `.opblock-body pre` selector (now `.opblock-body pre.microlight`) includes `overflow-wrap: break-word`.
After the above change, this CSS selector no longer applies to `<pre>` blocks in the description, causing long unbroken text to overflow out of the right edge of the container.
(see screenshots below for before & after).
This change adds the `overflow-wrap: break-word` …
=> fix(styles) restore wrapping of long text in pre blocks

src/core/plugins/oas3/components/servers.jsx, test/e2e-cypress/tests/bugs/6351.js
This PR fixes the prop error generated by React introduced in #6358. Fixes #6372.
Changes the `currentServer` value to be assigned at the top of the select instead of as a selected prop on the option.
This fixes the React warning introduced in #6358.
Automation was tweaked to fix for this. Tested on local installation with multiple openapi 3 specs.
=> Fix 6372: Updating server select prop and test

webpack/_config-builder.js
Increase webpack maxEntrypointSize and maxAssetSize
Updating dependency to `core-js@3` in #6410 increased the bundle size by 47 KiB, triggering the 1MB error
PR #6410 was done in conjunction with SwaggerClient dependency update to `core-js@3` in https://github.com/swagger-api/swagger-js/pull/1716
I also tried to remove all dependency from `core-js@` and `core-js@2`. This includes removing `src/core/components/debug.jsx`, which appears to be unused, and the two dependencies it imports, which requires `core-js@2` (react-motion, react-inspector). Further, I updated to React 16, which although known to be breaking to swagger-ui, yielded a bundle size result of 997 KiB, which is still 34 KiB increase.
Choice is being made to stay updated with actively maintained `core-js@3` with the tradeoff …
=> refactor(build): increase maxEntrypointSize for core-js@3

src/core/utils.js, test/unit/core/utils.js
Sample for text/plain should not be stringified. Introduced with #6412 the json sample for type string will be stringified. This should only be the case if the content type is not text/plain.
Fixes #6430
in browser
by new tests
see #6430
=> it should not unnecessarily stringify string values for text/plain content type

src/core/json-schema-components.jsx, test/e2e-cypress/static/documents/features/schema-form-enum-boolean.yaml, test/e2e-cypress/tests/features/schema-form-enum-boolean.js
* Restored `allowedValue` to accept either `enumValue` or `booleanValue`.
This will allow a `boolean` to have an empty default value, regardless of the if the field is `required`. On load (operation expanded), a required boolean field no longer inaccurately displays as `true`. Therefore a user must select a valid boolean value in order to execute the request.
* Created new Cypress tests to test rendering and validation of `required` enum and boolean fields.
This also includes a test to validate that an optional empty value is NOT sent.
fixes #6429 
New Cypress tests.
=> fix(try-it-out): required boolean default value set to empty string

src/core/components/parameter-row.jsx, test/unit/components/parameter-row.jsx
Use ternary expressions to explicitly check for `undefined` values instead of "false-y" values.
Fixes #5573 
Jest unit tests adapted from PR #5666
=> fix(parameter-row): rendering of default/example values of 0

src/core/components/example.jsx, src/core/components/model-example.jsx, src/core/components/parameter-row.jsx, src/core/components/parameters/parameters.jsx, src/core/components/response.jsx, src/core/plugins/oas3/components/request-body.jsx
Complement #5259, getConfigs was not correctly forwarded to Examples 🖇️ 
As a result, [syntax highlight could not be disabled be disabled or configured in that element](https://github.com/swagger-api/swagger-ui/pull/5259#issuecomment-699515953) as was reported by @mariem-89
Achieve expected behavior introduced in  #5259
Ran the test locally and performed local acceptance tests (see screenshots)
>Before / After
=> Setting up syntax highlighting of code section - Configuration fix for Examples

src/core/components/operations.jsx, src/core/containers/filter.jsx, test/e2e-cypress/tests/bugs/6276.js
According to the [configuration documentation](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#display) filter "Can be Boolean to enable or disable, or a string, in which case filtering will be enabled using that string as the filter expression."
Since url parameters are string we should compare against strings instead of booleans to check if the value is `true` to show the bar without filtering by any value or `false` to hide the bar (although it is also hidden if no parameter is set).
Fixes #6276 
While testing I also realized that when `filter=false` instead of hiding the bar would filter by the word "false" https://petstore.swagger.io/?filter=false 
Locally I have tested by sending the value `true`, `false` and also other strings.
**filter=true** …
=> Fix so query parameter filter=true/false enables/disables the filter bar instead of filtering by that string

src/core/utils.js
Instead of using `new Buffer` we should use `Buffer.from` from [here](https://nodejs.org/api/buffer.html#buffer_static_method_buffer_from_string_encoding)
This code was introduced to fix #6366 so I tested the given user and password after the changes with a `swagger: 2.0` file that uses basic auth as explained [here](https://swagger.io/docs/specification/2-0/authentication/basic-authentication/):
```
securityDefinitions:
basicAuth:
type: basic
```
In this case it works as expected, preserving the original bug fix.
While testing I noted that this no longer works for swagger 3.0 where the basic auth is declared as explained [here](https://swagger.io/docs/specification/authentication/basic-authentication/):
```
securitySchemes:
basicAuth:     # <-- arbitrary name for the security scheme …
```
=> Change new Buffer to Buffer.from after deprecation

src/core/components/execute.jsx, src/core/components/parameters/parameters.jsx, src/core/plugins/oas3/actions.js, src/core/plugins/oas3/reducers.js, src/core/plugins/oas3/selectors.js, src/core/plugins/spec/selectors.js, test/e2e-cypress/static/documents/features/oas3-multiple-media-type.yaml, test/e2e-cypress/tests/features/oas3-multiple-media-type.js, test/unit/core/plugins/oas3/reducers.js
* When the media-type is changed, there is a new `onChangeMediaType` method to handle actions.
* If target schema properties key/value pairs does NOT `equals` current schema properties, clear the requestBodyValue, tyr-it-out request/response and validation params.
* If target schema properties key/value pairs DOES `equals` current schema properties, do not change or re-render schema properties
* oas3Selector `validateShallowRequired` now also validates required keys against target media-type
Each media-type can have its own schema.
Fixes #6201
Fixes #6250 
Fixes #6476
New Jest test for reducer `CLEAR_REQUEST_BODY_VALUE`
New Cypress tests includes checking for undesired artifacts in Try-It-Out cURL command, and implicitly confirms that existing validation rules still apply.
=> fix(oas3): switching media types should update schema properties

src/style/_markdown.scss
Fixed the bug for which the text was overflowing if it was containing a single very long string (see #5934).
The fix makes use of the `word-break`  CSS property and its recent option [`break-word`](https://caniuse.com/mdn-css_properties_word-break_break-word) and supports the option [`break-all`](https://caniuse.com/word-break) as a fallback solution on older browsers.
Fixes #5934.
Tested on Firefox and Chromium on Linux and Edge on windows.
=> Preventing long strings from overflowing (fix #5934)

src/core/index.js
I found that the problem was introduced in [this merge](https://github.com/swagger-api/swagger-ui/pull/4349/commits/c611381210dc7f294f7b684dc391a4c7c257b5f3).
Fixes #4825
Also I inverted the predicate for the sake of better maintenance. If any additional changes or tests required, please let me know.
I did manual testing, put the `configUrl` and a remote config and loaded the page. Everything looks good, config loaded only once.
=> Fix downloading remote config

.github/workflows/nodejs.yml
Initial github actions for CI. No changes to `package.json`
Migrate from Jenkins CI
=> ci(GA): use github actions as CI

test/e2e-cypress/tests/features/oas3-multiple-media-type.js
refs #6570
Combine multiple `cy.` chains into a single `cy.` chain. This matches the behavior of other Cypress tests with `execute`.
fixes #6570 
Hopefully resolves async issues.
=> fix(cypress): flakiness in oas3-multiple-media-types test

test/e2e-cypress/tests/features/oas3-request-body-required.js
Add missing `input` element for Cypress to test for `not.have.class`
flaky test
=> fix(cypress): oas3-request-body-required flakineess

README.md, docs/usage/installation.md
Update `README` and Installation instructions to better indicate how to use SwaggerUI without NPM.
Current documentation is a bit misleading, and seems to indicate that NPM is required to install and/or run Swagger. Users looking for plain old HTML files might have trouble figuring out how to install SwaggerUI.
Provided easy to follow steps.
=> Improve documentation for Standalone plain HTML installation

src/core/components/parameter-row.jsx, src/core/components/response.jsx
Parameters Extensions, Response Extensions and Response Links render the key in .map() in React 16.
To prevent this .entrySeq() is used 
Keys in .map() are getting rendered to DOM when using React 16
=> fix: Fixed keys rendering in React 16 using .entrySeq()

src/core/components/auth/oauth2.jsx, src/core/oauth2-authorize.js, src/core/plugins/oas3/auth-extensions/wrap-selectors.js, src/core/plugins/spec/actions.js, test/unit/core/plugins/oas3/wrap-auth-selectors.js
spec/actions.js: Add OIDC metadata fetching
components/auth/oauth2: Add OIDC URL to the Authorization popup
This implementation requires OIDC metadata field `grant_types_supported` to convert to existing oauth2 flows.
Current implementation does not look at OIDC metadata fields other than `grant_types_supported`, `scopes_supported`, `authorization_endpoint`, and `token_endpoint`. `response_type` is still hard-coded in oauth2-authorize.js.
There is currently no support for flows other than the existing oauth2 flows.
Note: CORS must be enabled at the well-known OIDC endpoint for the OIDC metadata to be fetched. A workaround is to download the OIDC metadata via other means and reference it in swagger-ui with a local file relative URL.
Fixes #3517, or at least the OIDC URL processing, not the …
=> feat(auth): Add OpenID Connect Discovery support (#3517)

.github/workflows/nodejs.yml
All PRs done by @dependabot should be merge automatically when CI passes.
match `swagger-js` implementation here: 
https://github.com/swagger-api/swagger-js/pull/1778
https://github.com/swagger-api/swagger-js/pull/1779
=> ci(GA): automerge dependabot PRs that passes CI

src/core/plugins/oas3/components/request-body.jsx, test/e2e-cypress/static/documents/bugs/6475.yaml, test/e2e-cypress/tests/bugs/6475.js
Request Body samples do not respect the media type selected.
It just stringifies the json representation of the sample provided via `examples` or `example` keyword.
It should use the `getSampleSchema` method, which does take care of the content-type // media-type.
Fixes #6475 
see #6475
=> Request Body examples should respect media-type

src/core/components/execute.jsx, src/core/components/operation.jsx
Avoid sending multiple request while old is in progress
Avoid sending multiple request while old is in progress.
Fixes #6771
Browser
=> feat(ux): Disabled Execute button while request is in progress

src/core/plugins/samples/fn.js, test/unit/core/plugins/samples/fn.js
A string example for an XML schema should be returned as provided.
In `sampleFromSchemaGeneric` added in case xml object schema the conditional return for the string example.
Added in `createXMLExample` the conditional return for the string example.
Fixes #6818
added unit test to ensure literal example is returned as is.
=> fix(sample-gen): should return xml literal example

docker/configurator/variables.js, docs/usage/configuration.md
After adding persistAuthorization configuration in #5939, there was a request to add it as a docker environment variable. This pull requests adds docker support for this variable as `PERSIST_AUTHORIZATION`.
It adds docker support to `persistAuthorization` configuration parameter.
All tests had been added in #5939. This one was only tested by building and running swagger's docker container and see if this functionality works correctly by running `docker run -e PERSIST_AUTHORIZATION=true swagger`.
=> feat(docker): add docker support for persist authorization variable

webpack/_config-builder.js
loading ` /\.(png|jpg|jpeg|gif|svg)$/` relied on the default options of `url-loader`.
In one of the latest releases they swiched the esModule default from false to true.
https://github.com/webpack-contrib/url-loader/releases/tag/v3.0.0
> switch to ES modules by default (the option `esModule` is `true` by default)
So in case of importing a asset with above stated types, it will be treated as esModule. This is why loading an svg resulted in  [object%20Module].
To fix this I have edited the baseRules set to treat  `/\.(png|jpg|jpeg|gif|svg)$/` as no esModule.
Fixes #6850 
browser
=> fix(webpack): assets should not be treaded as esModule

src/core/utils/url.js, test/unit/core/utils.js
* OAS3: relative url when no servers defined AND specUrl is invalid Url
* OAS2: specUrl is non-url string
Add support in the cases where `specUrl` is not part of a valid URL string. The URL() method was returning an "Invalid baseURL" response. If 'baseURL' is not a valid URL, substitute browser's own location instead.
OAS3: relative url is invalid URL, AND no servers defined. Config per reported issue
OAS2: Terms of Service is not required to be a URL.
Fixes #6863
Closes https://github.com/swagger-api/swagger-ui/pull/6788
Browser and Jest unit tests
=> fix(buildUrl): relative url is invalid URL (OAS3) or non-url (OAS2)

src/core/utils.js, test/unit/core/utils.js
if content / media type matches yaml or yml it will generate stringified sample like for json
in addition to that it will proccess the json sample vis js-yaml to the final yaml sample result
Fixes #6857
_Originally requested by @deltafsdevelopment in https://github.com/swagger-api/swagger-ui/issues/6470#issuecomment-763540384_
browser
Todo: cypress tests
=> feat(sample-gen): yaml sample generation

src/core/plugins/samples/fn.js, test/unit/core/utils.js
Fixes #6827:
https://gist.githubusercontent.com/mathis-m/6ccf292b5560fc09f50e52f2ad0f1e23/raw/f8b16efb750879d279e1c1fb3fffdb521b6dcad0/rxx6ldSupt.txt
_Originally posted by @smagafurov in https://github.com/swagger-api/swagger-ui/issues/6827#issuecomment-768512523_
=> fix(sample-gen): case yaml parsed example is number but string schema

dist/index.html
- use semicolons in js.
- closing the link tag.
=> use semicolons + closing link

src/core/components/auth/oauth2.jsx
Refactor `auth flow` constants with prefix: `AUTH_FLOW_xxxx`
Fixes #6705
=> refactor(auth): rename auth flow constants to be more descriptive

test/e2e-cypress/tests/features/oas3-request-body-required.js
Add a click action, which creates an element for Cypress to test (if class is invalid). Without the click action, there is no `input` field to test, just the button to `add items`. This is a stricter equality test, where the element itself must also exist.
The PR to update `cypress@5 to cypress@6` revealed this flaw that would fail the test.
Tested locally with both `cypress@5` and `cypress@6`
=> fix(cypress): tweak to ensure an element exists before test

src/core/components/layout-utils.jsx, src/core/index.js, src/core/plugins/download-url.js, src/core/plugins/samples/fn.js, src/core/utils.js
cumulative linting fixes, mostly around this rule: https://eslint.org/docs/rules/no-prototype-builtins
Major version update from eslint@4.x to eslint@7.x introduced new linting errors.
Closes #7071 , where the lint fixes are in this PR, with separate PR(s) for dependency updates
`npm run lint-errors` passes locally with current `eslint@4.x` as well as upcoming `eslint@7.x`
=> fix(lint): cumulative lint fixes prep for eslint@7

webpack/stylesheets.babel.js
For `postcss-loader` plugin, instead of using `autoprefixer`, use `postcss-preset-env plugin` which applies `autoprefixer`
Clarity of precedence of `postcss-loader` -> `postcss-preset-env` -> `autoprefixer`. All three dependencies have previously been required.
=> chore(webpack): use postcss-preset-env plugin

.github/workflows/dependabot-merge.yml
For a Dependabot PR, new GA workflow to wait [3 minutes] to check if all other GA are successful. If yes, merge the Dependabot PR.
Replaces old "Merge Me" GA.
This security change disabled auto-merging:
https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/
=> ci(GA): allow dependabot to merge PRs

src/core/components/providers/markdown.jsx, test/unit/xss/markdown-script-sanitization.jsx
Add `form` tag to list of forbidden tags. This will strip out html form actions from the markdown string.
Security to prevent html injection into an OpenAPI definition's description.
New Jest tests
=> feat: markdown sanitization of form tag

src/core/components/param-body.jsx, src/core/components/response-body.jsx, src/core/components/response.jsx, src/core/plugins/oas3/components/request-body.jsx, src/core/utils/jsonParse.js, test/e2e-cypress/static/documents/features/syntax-highlighting-json-oas2.yaml, test/e2e-cypress/static/documents/features/syntax-highlighting-json-oas3.yaml, test/e2e-cypress/tests/features/syntax-highlighting-json.js
* OAS 2 request and response examples
* OAS 3 request and response examples
* Check for json content across OAS2 and OAS3 request and response examples. If json, apply known "json" language to (syntax highlighter) `HighlightCode` props.
* New utils helper, `jsonParse.js`. Helps with `try/catch` boilerplate with use of `JSON.parse()`
Extends Fixes #6508 
If `json` language is not provided, react-syntax-highlighter may try to escape certain character and/or long strings into multiple string segments. This results in unexpected multi-color render within the desired string.
New Cypress tests with OAS2 and OAS3 samples. Note, the fail case would be instead of a single string within a single `<span>`, a broken example would have the string broken up into segments, each contained within its own …
=> fix(syntaxHighlighter): request and response examples for json cases

src/core/plugins/oas3/auth-extensions/wrap-selectors.js, test/unit/core/plugins/oas3/wrap-auth-selectors.js
Fixes #5230 
This will display the description of oauth endpoints in the authorize dialog.
It was just missing, probably a bug / never tested.
Tested against an OpenAPI definition created by spring + modified unit test to cover it.
=> Include description of oauth endpoints when parsing openapi

package-lock.json, package.json, src/core/utils.js, test/e2e-cypress/static/documents/features/try-it-out-schema-required-override-allowed.yaml, test/e2e-cypress/tests/features/try-it-out-schema-required-override-allowed.js
schema required properties should not be treated like required: true.
this lead to objects that requires properies beeing treated as required itself
Fixes #7205
Fixes #7086
browser
=> fix: required properties

src/core/plugins/oas3/components/request-body.jsx, test/e2e-cypress/static/documents/features/request-body/multipart/default-views.yaml, test/e2e-cypress/tests/features/oas3-request-body-default-views.js
Add a `type === object` check, to always return a `getSampleSchema`, which matches original behavior that got missed in https://github.com/swagger-api/swagger-ui/pull/6874
Fixes #7268 
new Cypress test that asserts that a string value exists and matches (instead of empty string)
=> fix(sample-gen): oas3 form-data object should generate example

.github/workflows/nodejs.yml
Add Cypress Binary Cache to Github Actions
Missing Cypress binary in cache noted in https://github.com/swagger-api/swagger-ui/pull/7376/checks?check_run_id=2909072275
```
The cypress npm package is installed, but the Cypress binary is missing.
We expected the binary to be installed here: /home/runner/.cache/Cypress/7.5.0/Cypress/Cypress
Reasons it may be missing:
- You're caching 'node_modules' but are not caching this path: /home/runner/.cache/Cypress
- You ran 'npm install' at an earlier build step but did not persist: /home/runner/.cache/Cypress
Properly caching the binary will fix this error and avoid downloading and unzipping Cypress.
```
github actions
=> chore(ga): cache cypress binary

src/core/plugins/samples/fn.js, test/e2e-cypress/static/documents/features/parameter-array-missing-items.yaml, test/e2e-cypress/tests/features/parameter-array-missing-items.js
* fixes #7375
Add a check that the expected array `items` exists before continuing sample generation.
Fixes #7375 
new cypress test
=> fix(sample-gen): parameter array missing items fallback

.github/workflows/nodejs.yml
Node.js version 16.9 relesed 3 days ago gives cryptic
errors. We'll wait untill this is fixed upstream.
=> ci: use max Node.js version of 16.8

src/style/_mixins.scss
Remove this [star property hack](https://stackoverflow.com/a/14927670/808699) that was targeting IE 5.5 to 7. 
It causes warnings during ESBuild's CSS minification and IE 7 is unsupported anyways.
```
warnings when minifying css:
> <stdin>:192:30201: warning: Expected identifier but found "*"
192 │ ...fter{clear:both}.swagger-ui .cf{*zoom:1}.swagger-ui .cl{clear:le...
```
Did not test, but risk is essentially zero because only IE 5.5 to 7 are supposed to recognize such properties. All other browsers will just fail to parse it and skip over the unknown property.
=> Remove IE7 CSS hack

src/core/components/deep-link.jsx, src/core/components/operation-summary-path.jsx
- Use <wbr> instead of ZERO-WIDTH SPACE (U+200B) to break segments in
operation-summary-path.jsx
- Remove no-longer-needed onCopyCapture listener which previously
stripped ZWSPs
Fixes #7513
Basic local test, HTML looks right and behaves the same as before, just without copying of ZWSPs.
N/A
=> fix: break path w/ <wbr>s to avoid copying ZWSPs

src/style/_layout.scss
Remove unnecessary padding inside box of http methods.
The box that contains methods DELETE and OPTIONS were too wide compared with others. see below:
- Copy petstore.json from `./test/e2e-selenium/static/test-specs` to `./dev-helpers/`
- In `./dev-helpers/index.html` change url parameter of `ui` variable to: `./dev-helpers/petstore.json` 
- modify petstore.json to get "OPTIONS", "DELETE" and "POST" right next to each other.
- run `npm run dev` in terminal
- Open http://localhost:3200/
- Compare width
=> fix: correct width of http request methods

src/core/components/info.jsx, src/core/components/operation-tag.jsx, src/core/components/operation.jsx, src/core/utils/url.js, test/unit/core/utils.js
Closes #7525
[buildUrl](https://github.com/swagger-api/swagger-ui/blob/07a88a59c4673585c477408b85f21a8bfd71fa9c/src/core/utils/url.js#L18) function used for URL resolution throws error on certain conditions. These conditions includes resolving against `Server.url` containing `ServerVariable`/s: https://api.example.com:{port}/{basePath}`
Safe version of `buildUrl` called `safeBuildUrl` has been created to swallow the URL resolution error and allow React rendering to continue uninterrupted.
New tests have been added.
=> fix(servers): prevent UI crash when chaning Server with variables

docs/usage/configuration.md
Along with that fix formatting of request snippet
value.
=> docs(configuration): document requestSnippetsEnabled config option

config/jest/jest.unit.config.js, src/core/components/layouts/base.jsx, src/core/plugins/view/error-boundary.jsx, src/core/plugins/view/fallback.jsx, src/core/plugins/view/index.js, src/core/plugins/view/root-injects.jsx, src/standalone/layout.jsx, test/unit/core/system/system.jsx
=> fix: error boundaries

docker/configurator/translator.js, docker/configurator/variables.js, docs/usage/configuration.md, flavors/swagger-ui-react/index.jsx, src/core/index.js, test/e2e-cypress/static/index.html, test/e2e-cypress/static/pages/5138/index.html, test/unit/docker/translator.js
=> fix(security): disable reading query config

flavors/swagger-ui-react/release/run.sh
The swagger-ui-react package includes the swagger-ui.js and swagger-ui.-es-bundle.js files, which references corresponding source map files that are already generated, but not included in the final npm package.
This is inconsistent and causes error message when building our application with CRA 5 (Webpack 5)
PR https://github.com/swagger-api/swagger-ui/pull/7601 has fixed the problem for the css map source file. This is the same fix but for the js files.
Tested manually by executing  `flavors/swagger-ui-react/release/run.sh`
```
❯  ./run.sh
+ mkdir -p ../dist
+ cp ../../../dist/swagger-ui.js ../dist
+ cp ../../../dist/swagger-ui.js.map ../dist
+ cp ../../../dist/swagger-ui-es-bundle.js ../dist
+ cp ../../../dist/swagger-ui-es-bundle.js.map ../dist
+ cp ../../../dist/swagger-ui.css ../dist …
```
=> Add source map of js files to swagger-ui-react

test/e2e-cypress/tests/bugs/5043.js
After loading initial page and `swagger.yaml`, add a 500ms wait to the `cy` chain. The hypothesis is that the intermittent failures are due to insufficient time from when Cypress loads the page successfully and begins its assertions, and when the definition finishes resolving the external reference file. E.g. hopefully this allows sufficient time for the external reference `status.yaml` to resolve within `swagger.yaml`.  
Also, without success, attempted to import yaml into Cypress test without webpack modification (loaders), as well as tried loading a file from the static directory (and non /fixture directory) to use with `cy.fixture`. 
hopefully fixes #7768
Cypress test still passes locally, albeit with extra delay time.
=> test(cypress): add wait time for bugs/5043 to resolve spec

package.json
This PR corrects the CSS export in `package.json` from `./swagger-ui.css` to `./dist/swagger-ui.css`.
v4.6.0 has an incorrect export in `package.json` for `./dist/swagger-ui.css` which causes the following error when importing the file:
```
Module not found: Error: Package path ./dist/swagger-ui.css is not exported from package
node_modules/swagger-ui (see exports field in node_modules/swagger-ui/package.json)
```
This was tested in our Vue SPA which imports swagger-ui by switching to our fork and changing the export to the correct path for the CSS file. With the path in v4.6.0, the application doesn't build at all, whereas with the corrected path, it all works again.
Changing the import from `import 'swagger-ui/dist/swagger-ui.css';` to `import 'swagger-ui/swagger-ui.css';` results in …
=> fix: Export ./dist/swagger-ui.css

flavors/swagger-ui-react/index.jsx
Plugins can be an array of functions and/or and array of objects. Prop type validation is failing for functions.
Functions are already supported by prop type validation is throwing a warning.
I did a create a package locally with the changes and tested it with an array of functions and objects.
=> fix(swagger-ui-react): fix prop type for plugins

test/e2e-cypress/static/documents/features/auth-bearer-flow.yaml, test/e2e-cypress/tests/features/auth-bearer-flow.js
Cypress E2E test for Oauth2 Authorization Bearer. Mocks Oauth2 server response.
This PR provides the supporting tests to PR #7926 . There was previously a lack of test(s) for a simple Authorization Bearer use case.
n/a
=> test(oath): for authorization bearer

src/core/components/curl.jsx, src/core/plugins/request-snippets/index.js, src/core/plugins/request-snippets/request-snippets.jsx, test/mocha/components/live-response.jsx
* Update `RequestSnippets` to functional component with React Hooks
* React Hooks allows us to implement `useRef` and `useEffect`, to localize adding/removing event listeners to `RequestSnippets`
* Update `LiveResponse` Mocha test with updated import of `RequestSnippets`
Fixes #7932
Followup to #7497 , where we still want to leverage `useRef`
Root cause is that #7497 removed the `preventYScrollingBeyondElement` from parent class, so this PR removes any additional references
all existing tests pass.
local testing to confirm console.errors no longer appear
=> fix(request-snippets): prevent scrolling errors from missing function

src/core/plugins/oas3/wrap-components/markdown.jsx
For OAS3, in the wrapped `Markdown` component, add a `breaks: true` override to the CommonMark preset.
fixes #7641 
local dev
_(ignore the actual text, which was pointing to when the newline did NOT occur)_
=> fix(oas3): set markdown line breaks to true

docker/nginx.conf
Instructs the browser to always request the swagger-initializer.js file from the server, which contains configuration data.
Fixes #7959 
I tested this by building the Docker image and verifying that the repro steps in #7959 now work as expected.
I was unable to add an e2e test because this was an nginx-related issue, and as far as I could tell we do not test the nginx server.
1. Run `docker build -t swagger .`
1. Run `docker run -p 8080:8080 -e URL=foo swagger`
1. Visit http://localhost:8080
<details>
<summary>Network Screenshot...</summary>
</detail>
1. Stop container. Run `docker run -p 8080:8080 -e URL=bar swagger`
1. Refresh page. The browser fetches the latest swagger-initializer.js file ✅
<details>
<summary>Network Screenshot...</summary>
</details>
1. Refresh page again. The …
=> Instruct browser not to cache swagger-initializer.js

src/core/plugins/oas3/wrap-components/markdown.jsx
Reverts swagger-api/swagger-ui#7942
Fixes #6849 
Per OpenAPI 3.0 spec [here](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.0.md#rich-text-formatting), 
> Throughout the specification description fields are noted as supporting CommonMark markdown formatting. Where OpenAPI tooling renders rich text it MUST support, at a minimum, markdown syntax as described by [CommonMark 0.27](http://spec.commonmark.org/0.27/).
If a 2-line rendering is desired, [hard-line breaks](https://spec.commonmark.org/0.27/#hard-line-break) should be used, e.g. 2 white spaces, or a "\\" char, at the end of the line.
Note, this means that rendering of the description fields are indeed specified differently between OpenAPI 2.0 and OpenAPI 3.0.
=> Revert "fix(oas3): set markdown line breaks to true"

flavors/swagger-ui-react/README.md, flavors/swagger-ui-react/index.jsx
Allow to pass withCredentials prop to react ui
=> Add `withCredentials` prop to swagger-ui-react

src/core/plugins/spec/actions.js, src/core/utils.js, test/e2e-cypress/static/documents/features/spec-parse-to-json.yaml, test/e2e-cypress/tests/features/spec-parse-to-json.js
Add a `JSON_SCHEMA` flag to `YAML.load()` to forcibly set a schema to use by `js-yaml@4`.
```
JSON_SCHEMA - all JSON-supported types: http://www.yaml.org/spec/1.2/spec.html#id2803231
```
fixes #8021 
New Cypress E2E tests
=> fix: set yaml parser load option to JSON_SCHEMA

docs/usage/installation.md
Document the existing `SWAGGER_JSON_URL` parameter [here](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/installation.md#docker).
Took me a little while to find the parameter, thought I'd be useful to document. See https://github.com/swagger-api/swagger-ui/issues/7951.
=> Documentation: add SWAGGER_JSON_URL section

src/core/components/copy-to-clipboard-btn.jsx, src/core/components/operation-summary.jsx, src/core/components/svg-assets.jsx, src/core/presets/base.js, src/style/_buttons.scss, src/style/_layout.scss
Add a copy to the clipboard button based on the discussion [here](https://github.com/swagger-api/swagger-ui/pull/7890)
You click on the button and it copies the path to the clipboard (e.g. /pet/{petId}/uploadImage).
Fixes #5799
1. Hover on any route path - this will make the button on the right (next to the authorize button) appear
2. Click on the button
3. Press ctrl + v anywhere to see what was copied
=> feat(ux): add copy to clipboard

src/style/_authorize.scss, src/style/_form.scss, src/style/_layout.scss, src/style/_servers.scss, src/style/_table.scss
Fixed link display on small screens
Also fixed the display issue of input element
Fixes  #6647  #7338
Only update the relevant CSS
**The display issue:**
**After fixed:**
=> fix(ux): responsive ui display

src/core/components/auth/oauth2.jsx
While using PKCE option (`usePkceWithAuthorizationCodeGrant` flag is set to true), client_secret field is hidden under non-auth_code authorization flows.
PKCE option hides client_secret field in every flow in auth component. In general PKCE should not be a replacement for a client secret (https://oauth.net/2/pkce/). So may be all the changes affecting client_secret should be reverted #7438? 
Made the flag `usePkceWithAuthorizationCodeGrant` affect only auth_code grant.
While using client credentials flow, I can't enter client secret into corresponding field (the field is hidden).
There is no client_secret option for client credentials flow when `usePkceWithAuthorizationCodeGrant` is set to true.
=> fix: client_secret doesn't appear in non-authcode flows while usnig PKCE

dev-helpers/oauth2-redirect.html, dist/oauth2-redirect.html
Given the following URL after user logged in using [casdoor](https://github.com/casdoor/casdoor), the UI app can not validate (checking the state param) the response bc an error parsing the params
```
redirect with hash
---
http://.../static/oauth2-redirect.html#token=eyJhbGci....?state=TW9....Sk=&token_type=bearer
```
before:
```js
if (/code|token|error/.test(window.location.hash)) {
qp = window.location.hash.substring(1);
} else {
qp = location.search.substring(1);
}
```
after:
```js
if (/code|token|error/.test(window.location.hash)) {
qp = window.location.hash.substring(1).replace('?', '&');
} else {
qp = location.search.substring(1);
}
```
btw, the default behavior on oauth2 would try to get the value for `access_token` property from the oauth response if you are using a different …
=> fix(oauth2): handle redirect params properly

Dockerfile
Refs https://github.com/swagger-api/swagger-ui/actions/runs/3224253196/jobs/5275194171
=> chore(security): use minimum 16.17.1-r0 in docker image

src/core/components/operation.jsx, src/core/plugins/spec/selectors.js, test/e2e-cypress/tests/features/multiple-examples-core.js
When using the "try it out" feature, the request is validated locally before being sent to the server. If the request fails validation, nothing happens. (The request is not sent.)
This pull request adds display of the validation errors so that the user can see why the request was not sent, and has an opportunity to resolve the problem(s) identified.
This fixes #6295
I have used the test case given in #6295.
=> Show validation errors

docs/usage/oauth2.md, src/core/components/auth/oauth2.jsx, test/e2e-cypress/tests/features/auth-code-flow-pkce-without-secret.js
Show the client secret input always (for the authorization code flow) regardless of the PKCE flag.
Closes #7913
PKCE and Client Secrets are allowed to coexist and neither is designed as a replacement for the other. [1] It is wrong to assume that a client secret must not or cannot be used in combination with PKCE. Quite the opposite, when possible both PKCE and client secret should be used. [2] So the premises of #6290 and #8146 are not correct.
Admittedly, for users of the PKCE mechanism WITHOUT a client secret it might be a minor nuisance to see the client secret input in the Swagger UI. But they can just leave it empty. On the other hand, for users of the PKCE mechanism WITH a client secret it is more than just a nuisance if the client secret input is not shown. The Swagger UI becomes …
=> fix: show client secret input for PKCE auth code flow

package.json
Temporarily remove the `postinstall` hook for `patch-package` so that downstream projects can still build with SwaggerUI.
There is a deployment regression introduced in PR #8266. Probably need to copy over patched files as part of webpack build workflow, or possibly moving `patch-package` to a production dependency. Further investigation required.
Visible in downstream SwaggerEditor failed release, logs [here](https://jenkins.swagger.io/view/OSS%20-%20JavaScript%20Releases/job/oss-swagger-editor-release/151/console)
=> revert(patch-package): temporarily remove postinstall hook

.whitesource, whitesource.config
We've stopped using Whitesource as of 1st January 2023.
=> chore(SCA): remove all whitesource configs

test/e2e-cypress/tests/bugs/6183.js, test/e2e-cypress/tests/features/oas3-multiple-media-type.js, test/e2e-cypress/tests/features/oas3-request-body-required.js
=> test(cypress): fix tests flakyness by stubbing httpbin.org responses

Dockerfile
Node.js@18.12.1-r0 got installed by default.
CVE-2023-24807 was manifesting in image security
scans.
Refs https://github.com/swagger-api/swagger-ui/actions/runs/4310624218/jobs/7519243077
=> fix(docker): use vulnerability free Node.js=>18.14.1-r0

docker/nginx.conf
Resolves https://github.com/swagger-api/swagger-ui/issues/8437
See the above linked issue and related Fly.io forum post for details.
=> fix(docker): add missing ipv6 all-interfaces binding

docker/docker-entrypoint.d/40-swagger-ui.sh, docker/nginx.conf
Enabling IPv6 address and port for IPv6 addresses
caused backward incompatible issues in the docker image.
Refs #8447
=> fix(docker): enable IPv6 explicitly by env variable

src/core/components/layouts/base.jsx, src/core/components/operations.jsx, src/core/containers/OperationContainer.jsx, src/core/plugins/oas3/selectors.js, src/core/plugins/oas3/spec-extensions/wrap-selectors.js, src/core/plugins/oas31/components/webhooks.jsx, src/core/plugins/oas31/helpers.js, src/core/plugins/oas31/index.js, src/core/plugins/oas31/spec-extensions/selectors.js, src/core/plugins/oas31/spec-extensions/wrap-selectors.js, src/core/plugins/spec/selectors.js, test/unit/components/operations.jsx
=> refactor(oas31): simplify Webhooks component by utilizing selectors

src/core/plugins/oas31/fn.js, src/core/plugins/oas31/oas3-extensions/wrap-selectors.js, src/core/plugins/oas31/spec-extensions/wrap-selectors.js
Affected wrapped selector was hasUserEditedBody.
This commit fixes the bug by calling the original
selector when path+method combination is not found in OpenAPI.webhooks field.
Refs #8498
=> fix(oas31): detect user request body edits in OpenAPI.paths

src/core/plugins/oas3/components/callbacks.jsx, src/core/plugins/oas3/spec-extensions/selectors.js, src/core/plugins/oas31/spec-extensions/selectors.js
Before this fix, other Path Item fields were
included into rendering as well (like servers).
Refs #8504
=> fix(oas31): display Callback operations only

src/core/plugins/json-schema-2020-12/hoc.jsx
Schema Object sub-trees are not renderer until
expanded.
Before the entire Scheam Object tree was rendered
and collapsed sub-trees here hidden by css.
Refs #8606
=> fix(json-schema-2020-12): enable sub-tree expansion optimization

package-lock.json, package.json, webpack/_config-builder.js
Webpack config need to be change to compensage. `ramda` and `ramda-adjunct` have beeen removed from webpack `resolve.alias` as they are now installed in the root of `node_modules` tree.
=> chore(deps): bump swagger-client from 3.19.6 to 3.19.7

src/core/plugins/json-schema-2020-12/components/JSONSchema/JSONSchema.jsx, src/core/plugins/json-schema-2020-12/components/keywords/$defs.jsx, src/core/plugins/json-schema-2020-12/components/keywords/AllOf.jsx, src/core/plugins/json-schema-2020-12/components/keywords/AnyOf.jsx, src/core/plugins/json-schema-2020-12/components/keywords/DependentSchemas.jsx, src/core/plugins/json-schema-2020-12/components/keywords/OneOf.jsx, src/core/plugins/json-schema-2020-12/components/keywords/PrefixItems.jsx, src/core/plugins/json-schema-2020-12/hoc.jsx
This option was removed and codebase has been
modified in a way as this option is always true.
Refs #8513
=> refactor(json-schema-2020-12): drop optimizeExpansion config option

src/core/plugins/json-schema-2020-12/index.js, src/core/plugins/oas31/index.js, src/core/plugins/oas31/json-schema-2020-12-extensions/components/keywords/Example.jsx, src/core/plugins/oas31/json-schema-2020-12-extensions/components/keywords/Xml.jsx, src/core/plugins/oas31/json-schema-2020-12-extensions/fn.js, src/core/plugins/oas31/json-schema-2020-12-extensions/wrap-components/keywords/Default.jsx
=> feat(oas31): add support for Schema Object xml keyword

src/core/plugins/oas31/json-schema-2020-12-extensions/components/keywords/Discriminator/Discriminator.jsx, src/core/plugins/oas31/json-schema-2020-12-extensions/components/keywords/ExternalDocs.jsx, src/core/plugins/oas31/json-schema-2020-12-extensions/components/keywords/Xml.jsx
This change is related to JSON Schema 2020-12.
Refs #8513
=> fix(oas31): fix extendable behavior in OpenAPI 3.1 base dialect keywords

src/core/plugins/oas31/index.js, src/core/plugins/oas31/json-schema-2020-12-extensions/components/keywords/Description.jsx, src/core/plugins/oas31/json-schema-2020-12-extensions/components/keywords/Discriminator/Discriminator.jsx, src/core/plugins/oas31/json-schema-2020-12-extensions/components/keywords/Example.jsx, src/core/plugins/oas31/json-schema-2020-12-extensions/components/keywords/ExternalDocs.jsx, src/core/plugins/oas31/json-schema-2020-12-extensions/components/keywords/Xml.jsx, src/core/plugins/oas31/wrap-components/operations.jsx, src/core/plugins/oas31/wrap-components/webhooks.jsx
=> feat(oas31): prepare code to render JSON Schema 2020-12 in Operations and Webhooks

src/core/plugins/json-schema-2020-12/components/keywords/Items.jsx, src/core/plugins/json-schema-2020-12/fn.js
As JSON Schema 2020-12 can be represented as
a Boolean Schema, different keyword detection
needs to be used.
Refs #8513
=> fix(json-schema-2020-12): fix rendering of items keywords

src/core/plugins/json-schema-2020-12/components/keywords/PatternProperties/PatternProperties.jsx, src/core/plugins/json-schema-2020-12/index.js, src/core/plugins/oas31/index.js, src/core/plugins/oas31/json-schema-2020-12-extensions/components/keywords/Properties.jsx, src/core/plugins/oas31/json-schema-2020-12-extensions/fn.js, src/core/plugins/oas31/json-schema-2020-12-extensions/wrap-components/keywords/Properties.jsx, src/core/plugins/oas31/wrap-components/model.jsx, src/core/plugins/oas31/wrap-components/models.jsx
This change is specific to JSON Schema 2020-12.
Refs #8513
=> feat(oas31): add support for properties keyword includeReadOnly/WriteOnly options

Dockerfile
Update nginx to fix CVEs
- CVE-2023-29469
- CVE-2023-28484⁠
There are 2 open CVEs for the `nginx:1.23.4-alpine` base Docker image. They are both fixed in v1.24.0
1. Opened a PR in my forked repo and observed that the Github Actions checks passed
2. Built the container locally and confirmed it started successfully
=> Update nginx base image to fix CVEs

flavors/swagger-ui-react/README.md
Hin on usage with nextjs
We had to dig deep until we found this issue: https://github.com/swagger-api/swagger-ui/issues/8245
no need
=> docs(swagger-ui-react): hint on usage with nextjs

src/core/plugins/json-schema-2020-12/samples-extensions/fn.js, test/unit/core/plugins/json-schema-2020-12/samples-extensions/fn.js
=> feat(samples): add support for const keyword

src/core/plugins/json-schema-2020-12/samples-extensions/fn.js, test/unit/core/plugins/json-schema-2020-12/samples-extensions/fn.js
=> feat(samples): support new semantics of exclusive number ranges

src/core/plugins/json-schema-2020-12/samples-extensions/fn.js, test/unit/core/plugins/json-schema-2020-12/samples-extensions/fn.js
=> feat(samples): add support for regex string format

src/core/plugins/json-schema-2020-12/samples-extensions/fn.js, test/unit/core/plugins/json-schema-2020-12/samples-extensions/fn.js
=> feat(samples): add support for uniqueItems keyword

src/core/plugins/json-schema-2020-12/samples-extensions/fn.js
=> refactor(samples): type check string constrains according to spec

src/core/plugins/json-schema-2020-12/samples-extensions/fn/core/example.js, src/core/plugins/json-schema-2020-12/samples-extensions/fn/core/fold-type.js, src/core/plugins/json-schema-2020-12/samples-extensions/fn/core/predicates.js, src/core/plugins/json-schema-2020-12/samples-extensions/fn/core/random.js, src/core/plugins/json-schema-2020-12/samples-extensions/fn/main.js, src/core/plugins/json-schema-2020-12/samples-extensions/fn/types/string.js, test/unit/core/plugins/json-schema-2020-12/samples-extensions/fn.js
=> feat(examples): add support for examples keyword

src/core/plugins/json-schema-2020-12/samples-extensions/fn/core/merge.js, src/core/plugins/json-schema-2020-12/samples-extensions/fn/main.js, test/unit/core/plugins/json-schema-2020-12/samples-extensions/fn.js
=> feat(samples): add support for proper schema merging

src/core/plugins/json-schema-2020-12/samples-extensions/fn/core/type.js, src/core/plugins/json-schema-2020-12/samples-extensions/fn/main.js
=> refactor(samples): do the general code cleanup

src/core/plugins/json-schema-2020-12/samples-extensions/fn/core/merge.js
=> feat(samples): add support for merging type keyword

src/core/plugins/err/error-transformers/hook.js, src/core/plugins/spec/actions.js, src/core/plugins/spec/selectors.js
This selector always returns the same JavaScript
object unless it really changes.
Before this change it customary to call
specJson().toJS() which always resulted
in transformation operation and new JavaScript
object.
Refs #8606
=> feat(spec): add new specJS selector

flavors/swagger-ui-react/index.jsx
Default value must be set to  (empty string) and
not to {} (empty object).
Refs #8976
=> fix(swagger-ui-react): fix default value for spec prop

src/core/plugins/json-schema-2020-12/fn.js
Refs #9013
Renders now as 
for following fixture:
```yaml
openapi: 3.1.0
info:
version: 1.2.3
title: title
components: 
schemas:
Location:
properties:
lat:
type: integer
```
=> fix(json-schema-2020-12): add rendering support for type='integer'

Dockerfile
We will keep the removal in the image untill
it's fixed in upstream nginx base image.
Ref CVE-2023-0801
=> fix(docker): remove vulnerable libtiff

package-lock.json, package.json, src/core/plugins/request-snippets/fn.js, src/core/window.js, test/unit/core/curlify.js
This change fixes both:
1. making multipart/form-data requests with content-type header for every individual boundary
2. generating correct CURL command for multipart/form-data request, allowing specifying content-type header for every individual boundary
Refs #4826
Refs #5356
---
**multipart/form-data boundaries now containing `Content-Type` headers**:
**CURL command correctly generated by assigning additional `type=`**:
=> feat: respect Encoding Object while building requests

src/core/plugins/oas3/components/request-body.jsx
Given following OpenAPI fixture:
```yaml
openapi: 3.1.0
info:
title: Swagger Petstore - OpenAPI 3.1
description: |-
This is a sample Pet Store Server based on the OpenAPI 3.1 specification.  You can find out more about
Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
You can now help us improve the API whether it's by making changes to the definition itself or to the code.
That way, with time, we can improve the API in general, and expose some of the new features in OAS3.
Some useful links:
- [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
- [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.y …
```
=> fix(request-body): access data of request body in safe way

.gitignore, .npmignore, package.json
This includes:
- ESM
- CommonJs
Refs #8311
=> fix: allow importing SwaggerUI in Node.js

package-lock.json, package.json
This release field to properly execute and we ended up with impartial release only. V5.4.1 will follow.
=> chore(release): cut the failed v5.4.0 release

babel.config.js, flavors/swagger-ui-react/release/run.sh
Refs https://github.com/swagger-api/swagger-ui/releases/tag/v5.6.0
=> fix(swagger-ui-react): fix build scripts and allow releasing

babel.config.js
Problem was resolved by turning babel debug off.
Refs #9192
=> fix(swagger-ui-react): avoid babel output in build fragments

src/core/index.js
We want to use `document.baseURI` as people can use [base HTML tag](https://www.tutorialspoint.com/html/html_base_tag.htm). In cases where base HTML tag is not used, `document.baseURI` uses value from `document.URL`.
=> refactor: use document.baseURI for URI Reference resolution

src/core/components/info.jsx, test/unit/xss/info-sanitization.jsx
=> feat: add wrapper for version labels

webpack/es-bundle-core.js
We were accidentally bundling `xml-but-prettier`
library which resulted in failed remix.run builds.
=> fix(build): add support for remix.run bundler

package-lock.json, package.json
v5.10.1 was a failed released, not all release
artifacts were published.
Refs https://github.com/swagger-api/swagger-ui/releases/tag/v5.10.1
=> chore(release): manual release bump to v5.10.1

src/core/components/response.jsx, src/core/plugins/json-schema-2020-12-samples/fn/main.js, src/core/plugins/oas31/after-load.js, test/e2e-cypress/e2e/features/plugins/oas31/oas31-response-empty-content.cy.js, test/e2e-cypress/e2e/features/plugins/oas31/oas31-response-empty-media-type.cy.js, test/e2e-cypress/e2e/features/plugins/oas31/oas31-response-no-content.cy.js, test/e2e-cypress/static/configs/oas31-response-no-content.yaml, test/e2e-cypress/static/documents/features/oas31-response-empty-content.yaml, test/e2e-cypress/static/documents/features/oas31-response-empty-media-type.yaml, test/e2e-cypress/static/documents/features/oas31-response-no-content.yaml
Refs #9199
Supersedes https://github.com/swagger-api/swagger-ui/pull/9636
=> fix(oas31): render responses that do not have content field

src/core/components/model-example.jsx, test/e2e-cypress/e2e/features/default-model-rendering.cy.js, test/e2e-cypress/static/documents/features/default-model-rendering.yaml
=> fix: avoid rendering empty response schemas

.github/workflows/codeql.yml
We don't want CodeQL to analyze the bundled JavaScript code.
=> ci: set ignore paths for CodeSQL SAST

src/core/plugins/json-schema-2020-12-samples/fn/index.js, src/core/plugins/json-schema-2020-12-samples/index.js, src/core/plugins/json-schema-5-samples/fn/index.js, src/core/plugins/json-schema-5-samples/index.js, src/core/plugins/oas31/after-load.js, test/unit/core/plugins/json-schema-2020-12-samples/fn.js, test/unit/core/plugins/json-schema-5-samples/fn/index.js
=> feat(plugins): expose JSON Schema merging mechanism from samples plugins

src/core/plugins/json-schema-2020-12/components/keywords/Title/Title.jsx, src/core/plugins/json-schema-2020-12/fn.js, src/core/plugins/oas31/components/models/models.jsx, test/e2e-cypress/e2e/features/plugins/json-schema-2020-12/schema-title.cy.js, test/e2e-cypress/static/documents/features/json-schema-2020-12-title.yaml
Refs #9713
---
This PR supersedes the https://github.com/swagger-api/swagger-ui/pull/9718
=> fix(oas31): allow override names of top level schemas

src/core/plugins/json-schema-2020-12-samples/fn/api/formatAPI.js, src/core/plugins/json-schema-2020-12-samples/fn/class/FormatRegistry.js, src/core/plugins/json-schema-2020-12-samples/fn/types/number.js, src/core/plugins/json-schema-2020-12-samples/fn/types/string.js
Refs #9739
Use API to generate format string, to match how it's done for mediatype, and avoid a lengthy case statement
Conversely also make mediatype return a random string if not known, to match how it's done for format
It doesn't change functionality so no new unit tests are added, but existing tests pass
=> refactor(json-schema-2020-12-samples): design formatAPI consistent with mediatypeAPI and encoderAPI

src/core/config/defaults.js, src/core/config/factorization/inline-plugin.js, src/core/config/factorization/store.js, src/core/config/index.js, src/core/config/merge.js, src/core/config/sources/query.js, src/core/config/sources/system.js, src/core/config/sources/url.js, src/core/config/sources/yaml-file.js, src/core/index.js
I've used your PR as a base of my further work. I've dissected & composed back the entire config and operations around it.
I've identified following components:
These are just default options
I've tried to use standard `lodash.merge`. But unless we do two small changes, we're stuck with `deep-extend`. Here are my notes:
```js
/**
* We're currently stuck with using deep-extend as it handles the following case:
*
* deepExtend({ a: 1 }, { a: undefined }) => { a: undefined }
*
* NOTE1: lodash.merge & lodash.mergeWith prefers to ignore undefined values
* NOTE2: special handling of `domNode` option is now required as `deep-extend` will corrupt it (lodash.merge handles it correctly)
* NOTE3: oauth2RedirectUrl and withCredentials options can be set to undefined. By expecting null instead of …
```
=> refactor(config): disect & compose

flavors/swagger-ui-react/index.jsx
Refs #9243
This is a rewrite of `swagger-ui-react` from class component into function component. Class components are starting to be completely unsupported by the modern browsers.
#9243
Using https://github.com/char0n/swagger-ui-nextjs
---
**Resources:**
- [use client](https://react.dev/reference/react/use-client#use-client) explanation
=> feat(swagger-ui-react): rewrite into SSR compatible function component

docs/customization/plugin-api.md, docs/usage/configuration.md, src/core/config/defaults.js, src/core/config/factorization/system.js, src/core/config/type-cast/mappings.js, src/core/system.js, test/unit/core/system/wrapComponent.jsx
Refs https://github.com/swagger-api/swagger-ui/issues/7232#issuecomment-2097751759
Refs https://github.com/swagger-api/swagger-ui/pull/7304
The expected behavior described in this issue has always been intended. It shouldn't matter if whether the plugins have been registered via `presets` or passed by the `plugins` option. Having said that, this is just a bug in the original behavior, and the expected  behavior (called chaining in this issue) should be the default one. Wrapping actions and selectors already works like that (ref https://github.com/swagger-api/swagger-ui/pull/7304).
In https://github.com/swagger-api/swagger-ui/pull/7236, the remediation was provided, but unfortunately  it also contains hidden bug, where the original components objects is being mutated by the combined …
=> fix(system): allow wrapping components both from presets and plugins

Dockerfile
Restore `apk --no-cache` flags after #10192 and #10198 as Dockerfile best practice.
Also replaced `apk update` by `--update-cache` flag.
=> chore(docker): disable apk cache

README.md, src/core/plugins/oas3/helpers.jsx, test/unit/core/plugins/oas3/helpers.js, test/unit/core/plugins/oas31/components/fn.js
adds version 3.0.4 to the list of supported versions
3.0.4 is a maintenance release of the specification that does not change any of the functional aspects.
https://www.openapis.org/blog/2024/10/25/announcing-openapi-specification-patch-releases
fixes https://github.com/microsoft/OpenAPI.NET/issues/2030
This has NOT been tested beyond the affected unit tests. However the changes are straightforward and minor, I do not expect any side effects.
I'd appreciate if anyone could take the time to pull and test this just for sanity.
=> fix: adds version 3.0.4 and 3.1.1 to supported versions

src/core/plugins/json-schema-2020-12-samples/fn/main.js, src/core/plugins/json-schema-5-samples/fn/index.js, test/unit/core/plugins/json-schema-2020-12-samples/fn.js, test/unit/core/plugins/json-schema-5-samples/fn/index.js
x-additionalPropertiesName is a Redocly extension to display more descriptive property names in objects with additionalProperties[1]. This allows generating nicer looking and more informative documentation and examples than Swagger UI's current "additionalProp" name.
[1] https://redocly.com/docs/api-reference-docs/specification-extensions/x-additional-properties-name/
I haven't found the right place to document the change, but happy to add documentation if such a place exists.
=> feat(json-schema): support x-additionalPropertiesName

src/core/components/responses.jsx, src/core/utils/index.js
This PR fixes a rendering bug in the Responses when using custom OpenAPI extensions (`x-*`) inside the responses object.
fixes #10561 
Swagger UI previously attempted to render all entries in the responses object, including custom extensions like `x-tenant` as actual HTTP responses.
Manually tested with an OpenAPI 3.1.0 spec containing `x-tenant` under responses
Verified that the Responses section renders correctly and without errors
Confirmed that valid responses (200, 500, etc.) still display as expected
Ran relevant tests, no regressions observed.
Environment:
OS: Linux
Browser: Chromium 139
Swagger UI: `master` Branch
Schema used for testing: 
```json
{
"openapi" : "3.1.0",
"paths" : {
"/hello" : {
"get" : {
"responses" : {
"200" : {
"description" : "The hello message",
"content" : { …
```
=> fix: ignore rendering responses with extensions in the schema
