package.json

Add ncp to npm dependencie

---

.dockerignore
Dockerfile
README.md

Add Dockerfile and notes to README.

---

README.md
gulpfile.js
package.json

Watch, live reload and connect 💥

Gulp watch

---

src/main/template/main.handlebars

Define default email subject in contact link

---

src/main/javascript/doc.js

Dnozay patch 2

---

src/main/html/index.html

decode encoded URLs

---

Dockerfile
README.md

Fixed Dockerfile so that the service can be immediately started with docker run.

fixes to docker installation

---

lib/swagger-oauth.js

Include redirect_uri in access token request for OAuth2 authentication.

---

README.md

Add a link to releases for CHANGELOG

---

src/main/coffeescript/view/OperationView.coffee

https://github.com/swagger-api/swagger-ui/pull/498 made to develop_2.0

Vincentjames501 master

---

test/e2e/servers.js

Lets see if increasing the server launch timeout fixes test fragility

Increase timeout for server launch in TravisCI

---

dist/css/print.css
dist/index.html
gulpfile.js
src/main/html/index.html
src/main/less/print.less

Added a simple print style sheet
Merge to develop_2.0, as requested in #909

add print style sheet

---

src/main/html/index.html

qOrphaner master

---

src/main/javascript/SwaggerUi.js

Fixes #1053 reported at https://github.com/swagger-api/swagger-js/issues/301

Fix typos in SwaggerUi.js

---

dist/index.html
src/main/html/index.html

fixes #1205, remove dead line

---

src/main/javascript/helpers/handlebars.js
src/main/javascript/view/ContentTypeView.js
src/main/javascript/view/ParameterContentTypeView.js
src/main/javascript/view/ParameterView.js
src/main/javascript/view/ResponseContentTypeView.js
src/main/template/apikey_button_view.handlebars
src/main/template/basic_auth_button_view.handlebars
src/main/template/content_type.handlebars
src/main/template/param.handlebars
src/main/template/param_list.handlebars
src/main/template/param_readonly.handlebars
src/main/template/param_readonly_required.handlebars
src/main/template/param_required.handlebars
src/main/template/parameter_content_type.handlebars
src/main/template/response_content_type.handlebars

Addresses #1021 mostly by adding label tags, generating unique element
ids as needed.
In the process, moved the label text that gets set in the
___ContentTypeView.js files to the respective handlebar templates; the
text was static as far as I could tell.
There are additional minor 508 improvements that can be made with the
tables (scope tags, header attributes)

508 Fixes (attempt 2)

---

bower.json

Per bower/bower.json-spec@a325da3

Remove moot `version` property from bower.json dev branch

---

lib/swagger-oauth.js

Need to clear out previous popupDialog nodes, so previous checkboxes won't be considered.

OAuth flow only selected scopes should be sent to Authorize endpoint #1388.

---

README.md

Reverts swagger-api/swagger-ui#1417

Revert "Updating documentation based on issue swagger-ui issue #1414"

---

lib/swagger-oauth.js

fix for issue #1516: OAuth logout doesn't work

fix for issue #1516: OAuth logout doesn't work

---

README.md

standard npm badges added to readme file

npm badges added

---

lib/swagger-oauth.js
src/main/html/index.html

Fixes break introduced in 1fd15c6. Targeted at master branch.

Make client secret optional, depending on grant type.

---

README.md

Add apostrophe to contraction in readme

---

src/main/less/auth.less
src/main/less/screen.less

This is one of many steps in improving the quality and maintainability of the Less files.
- Get rid of a lot of nesting
- Rewrite unnecessarily specific selectors
- Fix indentation

 refactor/less

---

src/main/template/operation.handlebars

#198 Fixed issue with no submission on enter key

Inconsistent enter key behaviour #198

---

dist/index.html
src/main/html/index.html

Reverts swagger-api/swagger-ui#1900

Revert "Issue 1899"

---

dist/lang/fr.js

French translation fixed

---

lang/translator.js

Fixed typo in translator.js docs

---

README.md

Updated badge to make prettier. [ci skip]

---

src/main/template/operation.handlebars

Didn't build the UI but I don't expect any problems, except the classes are already used.

#2187 added some classes to sandbox form tables

---

src/main/javascript/view/BasicAuthView.js

Don't require a password

---

src/main/javascript/helpers/handlebars.js
src/main/javascript/view/ParameterView.js

This fixes:
https://github.com/swagger-api/swagger-ui/issues/2381

fix params showing as undefined

---

src/main/javascript/helpers/handlebars.js

Extend list of allowed tags to fix Model rendering. 

---

src/main/javascript/view/partials/signature.js

Creating pull request for fix for [Swagger UI Issue 2577](https://github.com/swagger-api/swagger-ui/issues/2577)

Issue 2577

---

src/main/less/specs.less

Resizable container for "Model Schema"

---

src/main/html/index.html

Legacy corporate web applications....

Added meta tag to force IE11 to use edge document mode

---

README.md

There is a small verb tense error that needs fixing.
Cheers!

Fix grammar error in readme.md

---

Dockerfile

copy all files

---

src/standalone/layout.jsx

Fixed scheme div showing if no schemes are present in the spec.

Added conditional to hide schemes div if no schemes are with in the spec

---

Dockerfile
docker-run.sh

based on [feedback from @schickling](https://github.com/schickling/dockerfiles/issues/55#issuecomment-270072701), I've copied the logic into a v3.x swagger-ui docker setup.

added variables for docker

---

src/core/index.js
src/core/utils.js
src/plugins/configs/index.js

Move filterConfigs to core

---

dev-helpers/oauth2-redirect.html
src/core/oauth2-authorize.js
src/core/plugins/auth/actions.js

I've also fixed some indentations in the actions file
There are two separate commit, so you can easily check the changes.
Why I need redirect url to be sent?
That's because servers return 401 unless sending it.

Send redirect url for oauth2

---

swagger-ui-dist-package/README.md
swagger-ui-dist-package/deploy.sh
swagger-ui-dist-package/index.js
swagger-ui-dist-package/package.json

Gets https://github.com/swagger-api/swagger-ui/pull/3126 into master.

packaging: fix swagger-ui-dist entry point

---

.eslintrc
package.json
src/core/components/providers/markdown.jsx
test/bugs/3199-sanitization-escaping.js

Adds test for and fixes #3199.

Markdown quote double-escaping

---

src/core/plugins/spec/selectors.js

fixing tag order to be in the same order as definition file

---

swagger-ui-dist-package/index.js

Add try/catch for module asset require calls

---

postcss.config.js

Fixes #3334 - Add autoprefixer back to postcss plugins

Fixes #3334 - Add autoprefixer back to postcss plugins

---

make-webpack-config.js
src/core/index.js

Fixes #3300 
Ping @shockey - I wasn't sure if you wanted the build timestamp as a long or as a readable string.

Fixes #3300 - Updates to versions.swaggerUi information

---

src/core/components/layouts/base.jsx
src/plugins/topbar/topbar.jsx
src/style/_layout.scss
src/style/_topbar.scss

The operations filter looked out of place. So i moved it closer to operations

Moved filter search to within layout

---

README.md
docs/deep-linking.md
package.json
src/core/components/operation.jsx
src/core/components/operations.jsx
src/core/index.js
src/core/plugins/deep-linking/README.md
src/core/plugins/deep-linking/helpers.js
src/core/plugins/deep-linking/index.js
src/core/plugins/deep-linking/layout-wrap-actions.js
src/core/plugins/deep-linking/spec-wrap-actions.js
src/core/presets/base.js
src/style/_layout.scss

Fixes #2884.
CC @owenconti @webron: this PR starts a new convention of a `docs/` folder. I think it will be a good place to put things that are too in-depth for the README.

Operation & Tag deep linking

---

src/core/utils.js
test/core/utils.js

Fixes #3361 - Check for null and undefined values in validateParam

---

src/core/index.js
src/core/utils.js

Fix parseSearch typo

---

README.md

for https://github.com/swagger-api/swagger-editor/issues/1312

Add security contact to README

---

README.md

Not sure how I missed this one 
🤷‍♂️

Add deepLinking to README

---

package.json

Remove a duplicate package

---

src/core/components/parameter-row.jsx
src/style/_table.scss

Indicate parameter deprecation

---

src/core/curlify.js
test/core/curlify.js

Fix cURL outputs with formData

---

src/style/_topbar.scss

Changed radius on input in topbar

---

src/core/components/parameter-row.jsx

Fixes #3428 (I botched the branch name).

Display OAS3 parameter types

---

README.md
src/core/components/live-response.jsx
src/core/components/operation.jsx
src/core/components/responses.jsx
src/core/index.js
src/core/plugins/spec/actions.js
src/core/plugins/spec/reducers.js
src/core/plugins/spec/selectors.js
test/components/live-response.js
test/core/plugins/spec/actions.js

resolves #2872 - adds back support for requestInterceptor / responseInterceptor.

Add support for requestInterceptor / responseInterceptor.

---

.github/issue_template.md

Adds a helpful hint to the content added in #3600.

Update issue_template.md: Version detection hint

---

package.json
src/core/components/layouts/base.jsx
src/core/plugins/oas3/actions.js
src/core/plugins/oas3/components/index.js
src/core/plugins/oas3/components/request-body-editor.jsx
src/core/plugins/oas3/components/request-body.jsx
src/core/plugins/oas3/components/servers.jsx
src/core/plugins/oas3/index.js
src/core/plugins/oas3/reducers.js
src/core/plugins/oas3/selectors.js
src/core/plugins/oas3/spec-extensions/selectors.js
src/core/plugins/oas3/spec-extensions/wrap-selectors.js
src/core/plugins/oas3/wrap-components/index.js
src/core/plugins/oas3/wrap-components/parameters.jsx
src/core/plugins/oas3/wrap-components/try-it-out-button.jsx
src/core/plugins/spec/actions.js
src/core/utils.js
src/style/_layout.scss
test/core/plugins/spec/actions.js

Companion Client PR: https://github.com/swagger-api/swagger-js/pull/1127/

OAS3: Try-It-Out

---

README.md

addresses some questions raised in #3677 
cc: https://github.com/swagger-api/swagger-editor/issues/1490

README: npm module clarifications

---

src/core/components/operations.jsx

Display Tag descriptions as Markdown

---

src/core/components/response.jsx

Remove $$ref values from response examples

---

src/core/plugins/oas3/auth-extensions/wrap-selectors.js
src/core/plugins/oas3/index.js
src/core/plugins/oas3/spec-extensions/wrap-selectors.js

LESS version bleed
CC: https://github.com/swagger-api/swagger-ui/issues/3705

Disable Swagger2 auth features in OAS3

---

src/style/_layout.scss

Fix CSS selector for markdown content inside response component.

Fixes #3646

---

src/style/_layout.scss

Remove extra styles for .renderedMarkdown content.

Fixes #3783

---

src/plugins/add-plugin.md
src/plugins/topbar/topbar.jsx

Improve UX

---

src/core/utils.js
test/core/utils.js

Fixes #3851, and makes our URL sanitizer more robust in general.
-  I added unit tests for the `sanitizeUrl` function.
- I confirmed that `validatorUrl: null` works as before.

Check for input type and string length before sanitizing a URL

---

docs/version-detection.md

Not sure what's going on with line 54 though, never touched it.
I had to look up how to do this, now no on else should have too :)

Made it clearer how to get version from browser console

---

src/core/plugins/oas3/spec-extensions/wrap-selectors.js

add specSelectors.hasHost for OAS3

---

src/core/components/response-body.jsx

Indent XML with 2 spaces

---

src/core/components/model.jsx

This looks like a small change, and it is in terms of `wc -l` - but moving to `PureComponent` has behind-the-scenes implications. 
I've reviewed our usage of `Model`, and I didn't see anything that would cause a problem. Potential snags include:
- Parent render functions creating new functions/reference type values on each render
- Mutation of mutable types in component props or state
- 
Fixes at least one root cause of #3219.
Also....
- I ran JS CPU and ReactPerf performance tests before and after the change, and observed a 90% reduction in parameter value input latency.
- used @orbex's document provided in #3219: [Gist](https://gist.github.com/shockey/252cf408a153fb7248fff893c3a99a2f)
- I tested the change within Swagger-Editor to ensure there were no issues with Model value mutations …

Make `Model` a PureComponent

---

src/style/_models.scss

PR for #3882 to fix overlapping text
Text was overlapping

Removed set width from Model prop

---

package.json

Update dependency on react-split-pane to support React-16.
I missed this with my original work on #3714, and it didn't show up in my testing because another dependency in my project was including an updated version.
Tested using the PetStore API under React 16
- [x ] No code changes (changes to documentation, CI, metadata, etc)
- [x ] Dependency changes (any modification to dependencies in `package.json`)
- [ x] All new and existing tests passed.

Update react-split-pane for React-16 support

---

src/core/components/auth/auths.jsx

Added a Done button to the auth modal
for #3537

Auth modal close button addded

---

docs/customization/plugin-api.md

Finish sentence fragment in Plugin API documentation

---

README.md
dev-helpers/index.html
docs/SUMMARY.md
docs/development/scripts.md

Add script documentation to development docs

---

src/core/plugins/spec/actions.js
src/core/plugins/spec/reducers.js

Excuse me for trivial modifications

Fix case style

---

src/core/plugins/oas3/helpers.js

Accept OpenAPI 3.*

---

src/style/_servers.scss

 Add max-width to servers select element

---

src/core/components/errors.jsx

Style resolver error line jumps

---

src/core/plugins/oas3/spec-extensions/wrap-selectors.js
src/core/plugins/spec/actions.js

Fixes https://github.com/swagger-api/swagger-editor/issues/1596.

Prevent non-object values from being dispatched as new JSON content

---

src/core/system.js
test/core/system/system.js

Fixes https://github.com/swagger-api/swagger-editor/issues/1612, fixes https://github.com/swagger-api/swagger-ui/issues/3362.
Supersedes https://github.com/swagger-api/swagger-ui/pull/4067.
New unit tests were added.

Add try/catch protection for statePlugin interfaces

---

CONTRIBUTING.md

docs(contributing): add merging pull requests section

---

src/polyfills.js
webpack-hot-dev-server.config.js

IE11 fixes

---

src/core/components/model-collapse.jsx
src/core/components/object-model.jsx

Fixes https://github.com/swagger-api/swagger-ui/issues/4093.

fix(core-components): make `onToggle` a non-required prop in ModelCollapse

---

docs/usage/installation.md

Spelling error in file docs/usage/installation.md.
Change single occurrence of text "unkpg's" to "unpkg's" (quotes omitted) 
Trivial document change and my first ever PR.  Hoping to contribute more substantially in the future.
No testing.
n/a

bug(docs) correct typo in installation.md

---

docs/customization/plugin-api.md

Use computed key to demonstrate statePlugin namespacing

---

src/style/_buttons.scss

Removes pulsing keyframe animation from Execute button.
It's pretty.... but it also creates a lot of CPU cycles. 🌀 
Fixes https://github.com/swagger-api/swagger-ui/issues/4085.
Not required, CSS change is self-evident.

improve: remove CPU-taxing Execute button animation

---

docs/SUMMARY.md

Fixed the internal links in the Summary page, probably redundant now that README itself points to these.
When browsing from /docs, It was leading to 404s 
Wrote a quick script to visit all links and test for 404s.

Fix Summary links

---

package.json

Captures fix in https://github.com/zengabor/zenscroll/issues/50#issuecomment-369381764.
CC https://github.com/swagger-api/swagger-ui/issues/4038, https://github.com/swagger-api/swagger-ui/issues/4189.

Upgrade Zenscroll to `4.0.1`

---

src/core/components/parameter-row.jsx
test/e2e/scenarios/oas3/pet.js
test/e2e/specs/petstore.openapi.yaml

Modifies `<ParameterRow>` to send a `value` prop to `<JsonSchemaForm>` based on merged definition + metadata.
Fixes https://github.com/swagger-api/swagger-ui/issues/4269.
Manually tested; added an integration test.

Use `parameterWithMeta` to get parameter data in <ParameterRow>

---

.travis.yml

remove docker login email param

---

src/core/components/providers/markdown.jsx
test/components/markdown.js

Allow images with data scheme

---

src/core/components/info.jsx
src/core/presets/base.js

create `InfoUrl` and `InfoBasePath`

---

src/core/plugins/samples/fn.js

fix: remove $$ref key from example if it exists

---

docs/usage/configuration.md

docs: fix broken method table

---

src/core/containers/OperationContainer.jsx

fix: request resolution via OperationContainer on mount

---

src/core/plugins/samples/fn.js

fix: don't assign example if an example does not exist

---

src/core/components/live-response.jsx

Fixes #4337
Tested locally with Edge v41

Patch for Edge browser

---

package.json
src/core/components/operation.jsx
src/core/containers/OperationContainer.jsx
test/e2e/scenarios/bugs/4409.js
test/e2e/scenarios/informationContainer.js
test/e2e/scenarios/models.js
test/e2e/scenarios/oas3/callbacks.js
test/e2e/scenarios/oas3/pet.js
test/e2e/scenarios/on-complete.js
test/e2e/scenarios/operations/pet.js
test/e2e/scenarios/operations/store.js
test/e2e/scenarios/operations/user.js
test/e2e/scenarios/refs.js
test/e2e/scenarios/schemeContainer.js
test/e2e/scenarios/topbar.js
test/e2e/specs/bugs/4409.yaml

Use non-normalized operationId for layout management, if it is available

---

src/core/components/parameter-row.jsx
test/e2e/scenarios/bugs/4374.js
test/e2e/specs/bugs/4374.yaml

Fixes #4374.
Includes a new e2e test case to prevent regression.

pass meta error information to JsonSchemaForm correctly

---

src/core/plugins/auth/actions.js
test/core/plugins/auth/actions.js

fix: add additionalQueryStringParams to auth requests

---

src/core/plugins/ast/ast.js
src/core/plugins/ast/jump-to-path.jsx
src/core/utils.js
src/plugins/add-plugin.md
test/core/oauth2-authorize.js
test/e2e/scenarios/refs.js
test/e2e/specs/refs/api2.yaml

Spelling fixes

---

src/core/plugins/oas3/components/http-auth.jsx

Spec compliance and developer friendliness related improvements.
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#security-scheme-object
https://tools.ietf.org/html/rfc7235#section-2.1
Locally, using an openapi doc that defines a http security scheme, with scheme Bearer, Basic, bearer, and basic.

HTTP auth improvements

---

docs/customization/plugin-api.md

Change the 5# to 4#
The 5# do not show well on the wiki but 4# do and they were not used
Improve readability
Here is how it looks now:
https://github.com/swagger-api/swagger-ui/blob/master/docs/customization/plugin-api.md#interfaces
Here is how it will look:
https://github.com/heldersepu/swagger-ui/blob/d648555df6d9a5e75009f81fb124612facd908dc/docs/customization/plugin-api.md#interfaces

Change the 5# to 4#

---

src/core/plugins/oas3/components/callbacks.jsx
test/e2e/scenarios/bugs/4445.js
test/e2e/specs/bugs/4445.yaml

fix: Callback component $$ref handling

---

src/core/components/highlight-code.jsx

enhancement: don't block scrolling if HighlightCode is not scrollable

---

src/core/plugins/spec/reducers.js
test/e2e/scenarios/bugs/4485.js
test/e2e/specs/bugs/4485/book.yaml
test/e2e/specs/bugs/4485/main.yaml

fix: path-item $ref operation metadata storage

---

src/core/components/parameter-row.jsx
test/bugs/4557-default-parameter-values.js

Fixes #4557!
Includes unit tests.

fix: respect OAS3 parameter default values

---

package.json
src/core/json-schema-components.js
src/core/utils.js
src/style/_form.scss
test/components/json-schema-form.js
test/core/utils.js

Adds an object editor for JSON Schema structures.
For https://github.com/swagger-api/swagger-ui/issues/3641.

feature: OAS3 object parameter support

---

src/core/components/online-validator-badge.jsx
src/core/components/param-body.jsx
src/core/components/parameter-row.jsx
src/core/json-schema-components.js
src/core/plugins/oas3/components/request-body.jsx
src/core/plugins/oas3/wrap-components/index.js
src/core/plugins/oas3/wrap-components/json-schema-string.js
src/core/plugins/oas3/wrap-components/parameters.jsx
src/core/plugins/spec/actions.js

feat: OAS3 binary media type support

---

README.md

because sometimes we do judge a book by its cover

docs: README touchups

---

docs/development/scripts.md

escape `|`
Just fix docs.
Test by eye.
Before:
After:

Fix improper markdown

---

test/e2e/pages/main.js

Most likely introduced by the restructuring in #4349.

housekeeping: update e2e selectors

---

docs/usage/oauth2.md

Updating the OAuth2 docs to fix parameter names and resolve #3432.

Doc updates

---

.babelrc
make-webpack-config.js

housekeeping: remove extraneous `getbase` aliases

---

.eslintrc
package.json
src/.eslintrc

housekeeping: add extraneous module linting

---

src/core/json-schema-components.js
src/core/plugins/oas3/components/request-body.jsx
src/core/utils.js
test/.eslintrc
test/core/utils.js

This PR:
- fixes a urlencoded array data key bug
- fixes unnecessary escaping of string generated sample values

Patches for Rafael

---

src/core/plugins/oas3/components/request-body.jsx

fix: support multimedia media types for file upload

---

test/e2e/helpers/index.html
test/e2e/scenarios/bugs/4196.js
test/e2e/scenarios/bugs/4374.js
test/e2e/scenarios/bugs/4409.js
test/e2e/scenarios/bugs/4445.js
test/e2e/scenarios/bugs/4485.js
test/e2e/scenarios/bugs/4536.js
test/e2e/scenarios/informationContainer.js
test/e2e/scenarios/models.js
test/e2e/scenarios/oas3/callbacks.js
test/e2e/scenarios/oas3/pet.js
test/e2e/scenarios/on-complete.js
test/e2e/scenarios/operations/pet.js
test/e2e/scenarios/operations/store.js
test/e2e/scenarios/operations/user.js
test/e2e/scenarios/refs.js
test/e2e/scenarios/schemeContainer.js
test/e2e/scenarios/topbar.js

housekeeping: improve e2e stability

---

src/core/components/parameter-row.jsx
test/e2e/scenarios/bugs/frozen-array-input.js
test/e2e/specs/bugs/frozen-array-input.yaml

reported by @webron, squashed by me

fix: OAS3 array item value input

---

src/core/components/parameter-row.jsx
test/e2e-cypress/static/documents/bugs/4867.yaml
test/e2e-cypress/tests/bugs/4867.js

fix: tolerate callback parameter values in ParameterRow

---

Dockerfile

Docker image hangs when run. 
The shell script does not have execute permissions.

need to make shell script executable

---

src/core/components/auth/authorize-btn.jsx
src/core/components/layouts/base.jsx
src/core/containers/authorize-btn.jsx
src/core/containers/schemes.jsx
src/core/plugins/oas3/auth-extensions/wrap-selectors.js
src/core/presets/base.js
test/components/schemes-wrapper.js

fix: repair schemes servers rendering

---

package-lock.json
package.json

fix(packaging): move webpack-dev-server to devDependencies

---

test/e2e-cypress/tests/features/dynamic-default-oauth.js

a drive-by copy paste job gone wrong

housekeeping: change test name + comment

---

LICENSE
README.md

housekeeping: happy new year!

---

Dockerfile

Added `-no-cache` option to `apk add` which should result in smaller docker images.
See https://github.com/gliderlabs/docker-alpine/blob/master/docs/usage.md#disabling-cache for more info.
It is alos a recommendation from the https://www.fromlatest.io dockerfile linter.
Ran a docker build and stood up the container locally and everything seems to work ok.

add no-cache option for smaller docker images

---

src/core/plugins/oas3/components/request-body.jsx
src/core/plugins/oas3/wrap-components/parameters.jsx
test/e2e-cypress/static/documents/bugs/5072/additional.yaml
test/e2e-cypress/static/documents/bugs/5072/empty.yaml
test/e2e-cypress/tests/bugs/5072.js

fix: provide JSON editor for x-www-form-urlencoded bodies lacking `properties`

---

package-lock.json
src/core/components/operation-summary.jsx
test/e2e-cypress/static/documents/bugs/5188.yaml
test/e2e-cypress/tests/bugs/5188.js

fix: gracefully handle non-string operation summaries

---

src/core/plugins/spec/actions.js

improve: subtree resolver batch handling

---

src/core/plugins/oas3/components/request-body.jsx

improvement: gracefully render malformed and empty requestBodies

---

Dockerfile
docker/run.sh

fix: generate gzipped Docker assets at runtime

---

package-lock.json
package.json

This PR updates the minimum Cypress version in `devDependencies`.
https://github.com/cypress-io/cypress/issues/2861

housekeeping: bump minimum Cypress version

---

make-webpack-config.js
package-lock.json
package.json
src/core/components/debug.jsx
src/core/index.js

Removes the dependency between swagger-ui and react-addons-perf.
Facebook discontinued support for react-addons-perf in version 15.5 (https://reactjs.org/blog/2017/04/07/react-v15.5.0.html#discontinuing-support-for-react-addons). It wasn't included in the 15.6.2 release that switched from `BSD + Patents` to `MIT` license.  
Built and tested locally using `npm run dev` also ran `npm run test` and `npm run e2e-cypress`
- [x ] Dependency changes (any modification to dependencies in `package.json`)
- [ x] are not breaking changes.
- [x ] My changes do not require a change to the project documentation.
- [x ] My changes can and should be tested by unit and/or integration tests.

Remove react-addons-perf dependency

---

src/core/components/model.jsx

Schema name showed incorrectly for external $ref: it included the URL; only the fragment hash was removed. this fix correct the regex to remove the URL and hash so only name shows correctly
In `src/core/components/model.jsx` the function `getModelName()` was modified from:
`return ref.replace("#/components/schemas/", "")`
...to:
`return ref.replace(/^.*#\/components\/schemas\//, "")`
Currently OAS3 Schema names show incorrectly.
Swagger-UI was run locally and manual tests were made to observe change
**Actual**
**Expected**

Mofied regex in model.jsx OAS3 $refs

---

src/style/_colors.scss
src/style/_variables.scss
src/style/main.scss

Used this [app](http://chir.ag/projects/name-that-color/#6195ED) to generate unique color names for most colors in this file and defined them as variables (excluding theme colors). 
`$_color-post`, `$_color-get`, ..., `$_color-options`
Method appeared to be unused and variables already defined in `_variables.scss`. Please flag if there is reason for file presence.
(Let me know if this size of PR is small enough or if we can squeeze a little more into them.)
- Update theme colors, e.g. `$color-primary`
- Rename color variables e.g.
```scss
// Base Colours
$color-black: #000;
$color-white: #fff;
$color-gray-50: lighten($color-black, 92%); //ebebeb
...
```
...or a similar naming convention.
- Look into moving more specific color vars into their specific block selectors, e.g. …

Swagger redesign/update colors

---

src/core/components/object-model.jsx

Adjustments made to allow markdown styling to be displayed properly in model description field:
- Replaced italic in-line style with font-weight: normal to properly allow markdown styles for object models.
- Left Bold styling for description description key.
In Swagger-UI, Models can have a description field, which can be styled using Markdown. Currently though, this is overridden by italic bold style when model description is actually displayed. 
Motivation for this change is the fact that, since Markdown style is allowed, the choices of styling user makes should be reflected in model description thats is displayed in Swagger-ui
This change has been tested using local development environment.

Fix/Allow markdown styled text to display properly in model object description in swagger-ui

---

README.md

Adding Jenkins Build Badge to Master branch.
I want to improve the visibility of our build status in jenkins.
This was tested via the badge status message.
N/A

Adding Jenkins Build Badge to Master

---

.github/lock.yml

housekeeping: use double newline in lock message

---

docs/README.md
docs/book.json
docs/customization/custom-layout.md
docs/customization/overview.md
docs/customization/plug-points.md
docs/customization/plugin-api.md
docs/development/scripts.md
docs/development/setting-up.md
docs/usage/configuration.md
docs/usage/cors.md
docs/usage/deep-linking.md
docs/usage/installation.md
docs/usage/limitations.md
docs/usage/oauth2.md
docs/usage/version-detection.md

This PR fixes the product names and terms in the documentation:
* Swagger-UI -> Swagger UI
* Swagger-Editor -> Swagger Editor
* OAuth2 -> OAuth 2.0
* Try-It-Out -> "Try it out"
* etc.
Names and terms should be spelled correctly.
n/a
n/a

Change Swagger-UI -> Swagger UI in docs

---

package-lock.json
package.json
src/core/plugins/configs/helpers.js
src/core/plugins/spec/actions.js
webpack/_config-builder.js

coordinated with:
* https://github.com/swagger-api/swagger-js/pull/1459
* https://github.com/swagger-api/swagger-editor/pull/2025

housekeeping: `@kyleshockey/js-yaml` -> `js-yaml`

---

docs/usage/configuration.md

Updates documentation to indicate that #3280 is now supported.

housekeeping: document Docker `OAUTH2_REDIRECT_URL` option

---

dist/oauth2-redirect.html

Add <title> tag to page
Add <title> tag to page to comply with SonarAnalyzer rule.
The file in question flares up as having a major bug according to SonarQube scanning simply due to the lack of a title. Adding a title is an small effort to remove this bug.

Add <title> tag to oauth2-redirect.html

---

package.json

Add homepage URL to `package.json`
REF: https://docs.npmjs.com/files/package.json#homepage
can be useful for folks looking at the file after they've downloaded it.
locally yes, all good.

Add homepage URL to `package.json`

---

README.md

This PR fixes the skewed image on mobile / small viewports.
The logo is skewed on small viewports.
By testing https://github.com/DanielRuf/swagger-ui/tree/housekeeping/fix-logo-size in the device emulator of the browser.
Before:
After:

housekeeping: fix logo size

---

docs/usage/installation.md

It fix the unpkg example from the documentation
Otherwise is the example in the documentation useless (because it will not work by copy it)

HTTPS path for unpkg link

---

flavors/swagger-ui-react/README.md
flavors/swagger-ui-react/index.js
package-lock.json

This PR adds `defaultModelExpandDepth` and `plugins` as pass-through props available to `swagger-ui-react`. These values simple get passed into `SwaggerUI`.
These props that are being added to `swagger-ui-react` are part of the interface already available to `SwaggerUI`. `swagger-ui-react` simply didn't provide an interface to set these values for the underlying `SwaggerUI` constructor.
This change allows developers to use the `defaultModelExpandDepth` and `plugins` with the `swagger-ui-react` node module.
I have passed these values directly to `swagger-ui` and they have successfully taken effect. Passing them in is as props to `swagger-ui-react` to be sent to `swagger-ui` seems like a no-brainer.

Add More React Props for swagger-ui-react

---

LICENSE
README.md

2️⃣0️⃣2️⃣0️⃣

---

package-lock.json
package.json

housekeeping: add missing conventional-changelog devDeps

---

package-lock.json
package.json

housekeeping: revert @release-it/conventional-changelog version

---

package-lock.json
package.json

manual bump of SwaggerClient to most recent v3.10.3
also includes package-lock update due to SwaggerClient v3.10.3
build process update

housekeeping: bump swagger-client version

---

package-lock.json
package.json

package bump swagger-client to 3.10.5 version
package bump swagger-client to 3.10.5 version for release process

chore(package): bump swagger-client to 3.10.5 version

---

package-lock.json
package.json

* webpack-cli
* webpack-dev-server
non-breaking dependency updates to resolve npm audit "Low"
`npm audit` 
Tested on Node 10 and Node 8

housekeeping: npm audit fix

---

package-lock.json
package.json
src/core/components/providers/markdown.jsx
src/core/plugins/oas3/wrap-components/markdown.jsx

Refs: #6050
Dependency bump, and update imports per documentation https://github.com/jonschlinkert/remarkable/releases/tag/v2.0.0
Fixes #6050
Tests pass on Node 10 and Node 8

housekeeping: remarkable

---

package-lock.json
package.json

Bump SwaggerClient to v3.10.6
Swagger release workflow

housekeeping: swagger-client@3.10.6

---

package.json

add a `-V` verbose flag for release-it
Debug release-it on Jenkins

housekeeping: add verbose flag for release-it

---

package-lock.json
package.json

revert `json-server@0.16.0` to `json-server@0.15.0`. 
as a result, Node 10 no longer required for this dependency
Release process debug

housekeeping: revert to json-server@0.15.0

---

package.json

add `verbose: 2` flag
release-it debug

housekeeping: add verbose 2 for release-it

---

package-lock.json
package.json

change flag
force update package-lock
debugging release proces

housekeeping: force release-it reversion

---

package-lock.json
package.json

Old: core-js@2.5.1
new: core-js@2.6.11
minor dependency version bump. this is the last version available before next major version.

housekeeping: core-js@2.6.11

---

package-lock.json
package.json

release bump swagger-client@3.10.8

housekeeping: update swagger-client v3.10.8

---

test/e2e-selenium/scenarios/bugs/4196.js
test/e2e-selenium/scenarios/bugs/4374.js
test/e2e-selenium/scenarios/bugs/4409.js
test/e2e-selenium/scenarios/bugs/4445.js
test/e2e-selenium/scenarios/bugs/4485.js
test/e2e-selenium/scenarios/bugs/4536.js
test/e2e-selenium/scenarios/informationContainer.js
test/e2e-selenium/scenarios/models.js
test/e2e-selenium/scenarios/operations/pet.js
test/e2e-selenium/scenarios/operations/store.js
test/e2e-selenium/scenarios/operations/user.js
test/e2e-selenium/scenarios/schemeContainer.js
test/e2e-selenium/scenarios/topbar.js
test/mocha/components/markdown.jsx
test/mocha/components/primitive-model.jsx
test/mocha/components/response-body.jsx
test/mocha/components/response.jsx
test/mocha/core/curlify.js

For files in `/test`, change the indent-space from 4 to 2
eslint consistency

style: fix indent spaces from 4 to 2 in test files

---

test/e2e-cypress/helpers/oauth2-server/index.js
test/e2e-cypress/helpers/oauth2-server/model.js
test/mocha/core/curlify.js
test/mocha/core/plugins/samples/fn.js
test/mocha/core/system/system.jsx
test/mocha/core/system/wrapComponent.jsx

For files in `/test` replace 'var' with 'let'
eslint prefer let

style: replace var with let in /test files

---

src/core/components/parameter-include-empty.jsx
src/core/components/parameter-row.jsx
src/core/components/parameters/parameters.jsx
src/core/plugins/oas3/actions.js
src/core/plugins/oas3/components/request-body.jsx
src/core/plugins/oas3/reducers.js
src/core/plugins/oas3/selectors.js
src/core/plugins/spec/actions.js
src/core/utils.js
src/style/_table.scss

This reverts commit b9b32c9c93f712bdef6735a404f20481ec49ff45. 
Refs #6203 #5830
b9b32c9c93f712bdef6735a404f20481ec49ff45 introduced a regression and changed the default behavior of swagger-ui. The commit did not came with any tests either.
- [ x My changes do not require a change to the project documentation.

revert: feat: Allow to skip submitting empty values in form data (#5830)

---

docker/run.sh

Signed-off-by: Wesley Schwengle <wesley@opndev.io>

Fix(Docker) #6211: Bug where SWAGGER_JSON is used without mount

---

package-lock.json
package.json
webpack/_config-builder.js
webpack/bundle.babel.js

Remove Webpack LodashModuleReplacementPlugin. This will increase build size from 963KiB to 987KiB
Fixes #6249

build(webpack): remove LodashModuleReplacementPlugin

---

flavors/swagger-ui-react/release/run.sh

Change the target path for `swagger-ui-react` babel config, to use `babel.config.json`
`.babelrc` was replaced with `babel.config.json` in [f0208e](https://github.com/swagger-api/swagger-ui/commit/f0208e8f41f0336754c5652cc1867254ee2b55bd)

fix(swagger-ui-react): updated babel config file target

---

docs/development/scripts.md

Update documentation for "Helpful scripts" with additional scripts and their descriptions
add documentation to PR https://github.com/swagger-api/swagger-ui/pull/6291
n/a

docs(scripts):  update building and testing scripts

---

package.json

remove npm script references that were used in development but later removed.
Jenkins identified missing scripts

fix: remove missing script references

---

webpack/es-bundle-core.babel.js
webpack/es-bundle.babel.js

extend changes from PR #6287 to recently new webpack config files: `es-bundle` and `es-bundle-core`
ref: PR #6287

build: change globalObject to "this" for es bundles

---

package-lock.json
package.json

Migrate Cypress from 3.8.3 to 4.12.1
npm audit, and general updating of dependencies
all existing Cypress tests still pass.

chore(deps-dev): update cypress from 3.8.3 to 4.12.1

---

release/.release-it.json

use `${version}` to replace `%s`
`%s` is a deprecated command substitution in `release-it@13.x`.

refactor(release-it): update command substitution syntax

---

package-lock.json
package.json

remove unused `imports-loader`
cleanup dependencies

chore(deps): remove unused imports-loader

---

.npmignore

add !<filename> for swagger-ui-es* bundles
npm currently ignores recently introduced swagger-ui-es* bundles. As a result, projects looking for the `swagger-ui-es-bundle.js` won't find it via `npm i`

fix(build): add es-bundle to .npmignore non-exclusion list

---

package-lock.json
package.json

Jenkins currently runs on Node 10.13. This PR should enable the `test:artifact` script to work on Jenkins. A similar PR on https://github.com/swagger-api/swagger-editor/pull/2220 validates Jenkins success 
jest@26 requires Node >= 10.14.2
test:artifact script was working on local, but not on Jenkins

chore(deps-dev): downgrade jest@26 to jest@25 for node<10.14.2

---

src/core/curlify.js

for the `curl -d` case, in testing scenarios, it is possible that the `req.body` parameter sent to `curl` is a `String` vs `Immutable.Map`. In addition, if a file is included in req.body within the Immutable.Map, curlify does not return file name and file type.
Migrating to Jest revealed this issue. This issue is most likely not obfuscated due to Mocha. The likely cause is a change in versions with `jsdom` dependency, of which Jest is using a much newer version.
incoming Jest test pass
existing Mocha test pass

fix(curlify): for -d, handle Im vs non-Im cases

---

test/unit/setup.js

Add a url field to JSDOM constructor will resolve `SecurityError: localStorage is not available for opaque origins` error in Jest.
This change is compatible with remaining Mocha tests, as well as `jsdom@16` update, as well as `enzyme@2` and `enzyme@3`
Migrating to Jest unit tests, and migrate to enzyme@3.

refactor(enzyme): add url to jsdom constructor for unit test setup

---

package-lock.json
package.json

update `jsdom` to be in-line with `jest@25`.
Note, `jsdom@16` and `jest@26` required Node >= 10.14

chore(deps-dev): update jsdom from 11.10.0 to 15.2.1

---

babel.config.js
package-lock.json
package.json

Match swagger-client update to use actively maintained core-js@3. Note, SwaggerUI no longer uses polyfills, but maintains setup in `babel.config` in case needed in future.
This PR includes `swagger-client@3.11.0` as a required dependency.
core-js@2 is no longer maintained

feat(build): use core-js@3

---

package-lock.json

* resolves vulnerability in bl <1.2.3
update bl dependency

chore(deps-dev): update iltorb from 2.4.3 to 2.4.5, including bl@4.0.3

---

package-lock.json

* resolves vulnerability in node-forge < 0.10.0
update node-forge dependency

chore(deps-dev): update selfsigned from 1.10.7 to 1.10.8, including node-forge@0.10.0

---

package-lock.json

Reverts swagger-api/swagger-ui#6433

Revert "chore(deps-dev): update selfsigned from 1.10.7 to 1.10.8, including node-forge@0.10.0"

---

package-lock.json

* resolves vulnerability in node-forge < 0.10.0
update node-forge dependency
`npm run dev` still works.

chore(deps-dev): update selfsigned from 1.10.7 to 1.10.8 (fixed)

---

src/style/_variables.scss

Change gray used as the background color of not highlighted code in order to match the one used by the theme used for highlighting. 
As stated here we are using the theme `agate` for highlighting: https://github.com/swagger-api/swagger-ui/blob/master/src/core/components/highlight-code.jsx#L44
And the background color used by this theme is `#333` as declared here https://github.com/react-syntax-highlighter/react-syntax-highlighter/blob/3204faac105256f8369aa4c691d54d49573c3a7a/src/styles/hljs/agate.js#L6
I used `#333333` to make it more consistent to how the other colors are declared on the file.
Fixes #6241 
Tested locally by executing one of the examples on the petstore file.

Fix inconsistent background colors in code sections

---

src/core/components/initialized-input.jsx

**Description**
Specify initialValue as a variable to prevent passing it with otherProps into Input tag
**Motivation and Context**
Fixes #5989
**How Has This Been Tested?**
Successfully built and observed no console warnings or errors on Authorize button click
**Screenshots (if appropriate):**
For testing, the Authorize button is located on the right-hand side of this page
Checklist
---

Fixes #5989 Warning: Unknown prop `initialValue` on <input> tag.

---

src/core/plugins/oas3/components/http-auth.jsx

Addendum to https://github.com/swagger-api/swagger-ui/pull/6483 and https://github.com/swagger-api/swagger-ui/issues/6395

Add missing autoFocus

---

dist/oauth2-redirect.html

Title tags should be inside head tags.
See:
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/title
- https://www.w3schools.com/tags/tag_title.asp
The HTML title tag should be inside the body tag.
Context: I have added the swagger UI to a repository of mine then I submitted the project to SonarCloud, for static code analysis. SonarCloud reported the missing `<title>` tag in `dist/oauth2-redirect.html` as a bug. When I opened the file, it had `<title>`, but was incorrectly placed outside the `<head>` tag.
After I fixed it on my repo, I thought it would be even better to fix it on Swagger UI's project, too.
Community/formal references:
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/title
- https://www.w3schools.com/tags/tag_title.asp
- …

Fix HTML title tag

---

package-lock.json

* this is a security fix
security update

chore(deps): bump ua-parser-js to v0.7.22

---

src/core/components/auth/oauth2.jsx
src/core/oauth2-authorize.js
src/core/plugins/auth/actions.js
test/unit/core/oauth2-authorize.js

* fixes #5243, #3992
From PR #5244, migrate mocha tests to jest, and resolve merge conflicts
Merges PR #5244 
jest unit test

fix(auth): support for oauth2 relative url

---

test/components/response-body.jsx
test/unit/components/models.jsx
test/unit/components/primitive-model.jsx

* use dummyComponent when a component is expected, but not used by test
* remove console.warn debug
Note, there still exists console errors when running Jest. However, 
* some are actual expected errors, e.g. `test/unit/components/models.jsx`, 
* some are unknown if expected in test, or problem with test itself, or actual React component, e.g. `test/unit/components/operations.jsx`
Resolve console errors and warning that resulted from migration to Jest.

test(jest): cleanup console warnings/errors

---

.github/workflows/nodejs.yml

add release job for github actions
CI

ci(GA): add release job step

---

.github/workflows/nodejs.yml

* Add an independent job to build and run artifact tests.
* parallel job reduces net time to complete CI. e2e and building bundles for artifact tests each take some time.
* parallel job enables targeting different Node versions per job
add test:artifact to CI. Previously not included.

ci(GA): add test:artifact job

---

.github/workflows/nodejs.yml

Add `lint-errors` step to build job.
part of extracting `lint-errors` from `npm test`, to control tests more explicitly in GA.

ci(GA): add lint-errors step

---

package-lock.json
package.json

Remove standard@11
remove unused dev dependencies

chore(deps-dev): remove standard

---

package.json

remove unused core-js@2 from swagger-ui dependencies. note, no change to `package-lock.json`. Any other references are
remove unused dependencies

chore(deps): remove core-js2

---

src/core/plugins/samples/fn.js
test/e2e-cypress/static/documents/bugs/6627.yaml
test/e2e-cypress/tests/bugs/6627.js

ref: #6627
Fix logic case if `example` or `example[propName]` is `undefined`, in which case code will assign the value from `sample[propName]` instead of `example[propName]`.
Fixes #6627 
new cypress test

fix(xml): example generation if an array has an example

---

package-lock.json
package.json

dompurify@2.0.7 -> dompurify@2.0.7
security update

chore(deps): dompurify@2.2.2

---

package.json

Minor and patch are allowed to implicitly change.
Release process updates swagger-client before release. With using the caret symbol `^` in front of swagger-client version, auto-update will not be possible.

chore(package): allow auto-update of swagger-client

---

.github/workflows/nodejs.yml

fix the name of the required test to `merge-me` job

ci(GA): fix merge-me required artifact-bundle

---

package-lock.json
package.json

resolve vulnerabilities fixed in highlight.js@10.4.1

chore(deps): react-syntax-highlighter@15.4.3

---

package-lock.json
package.json

bump json-server@0.16.3
dot-prop prototype pollution as reported by `npm audit`
However, note that `swagger-ui` no longer runs Selenium as part of PR process. So this change probably doesn't fix Selenium, but does resolve `npm audit`

chore(deps-dev): json-server@0.16.3

---

.github/dependabot.yaml

Daily dependabot check.
Intending to migrate from Renovate-bot to Dependabot.
Github Action to auto-merge passing dependabot PRs.

ci: dependabot yaml config

---

.github/workflows/nodejs.yml

Moved "Merge Me" GA job to end of file, per recommendation of [docs](https://github.com/ridedott/merge-me-action)

refactor(GA): move merge-me to eof

---

src/style/_layout.scss

Response data no longer wraps text and flows off the screen.
Fixed it by changing:
```css
code {
background-color: #dedede;
padding: 4px 4px 2px;
white-space: pre;
}
```
To:
```css
code {
background-color: #dedede;
padding: 4px 4px 2px;
white-space: pre-wrap;
word-break: break-all;
}
```
Fixes #6749
browser
Before:
After:

fix(style): response data flows off the screen

---

package-lock.json
package.json

Remove `bundlesize` dev dependency
remove unused dependencies. for swagger-ui, webpack is configured to perform size checkes.

chore(deps-dev): remove unused bundlesize

---

src/style/_layout.scss

this time in correct place
Fixes #6825

fix(style): code should should wrap line

---

flavors/swagger-ui-react/release/run.sh

change the src path extension from `.js` to `.jsx`.
With [swagger-ui@3.41.0](https://github.com/swagger-api/swagger-ui/releases/tag/v3.41.0), the build process to release `swagger-ui-react` failed during the transpile step:
```
+ cd ./flavors/swagger-ui-react/release
+ mkdir -p ../dist
+ cp ../../../dist/swagger-ui.js ../dist
+ cp ../../../dist/swagger-ui-es-bundle.js ../dist
+ cp ../../../dist/swagger-ui.css ../dist
+ node create-manifest.js
+ ../../../node_modules/.bin/cross-env BABEL_ENV=commonjs ../../../node_modules/.bin/babel --config-file ../../../babel.config.js ../index.js
babel:
../index.js does not exist
Build step 'Execute shell' marked build as failure
```
This is due to a filename change in commit 265bdc0, from `index.js` -> `index.jsx`, which was trying to fix to an eslint …

fix(swagger-ui-react): src filename extension to transpile

---

src/core/utils.js

respect nullable keyword
If value === null and nullable then no validation error.
```yaml
openapi: 3.0.1
info:
title: v1
version: v1
servers:
- url: 'http://localhost:62242'
paths:
/nullable:
get:
parameters:
- name: "someNull"
in: query
required: false
schema:
type: number
format: Int32
nullable: true
example: null
responses:
'200':
description: Success
content:
text/json:
schema:
type: string
example: "123"
application/json:
schema:
type: string
examples: 
x:
value: "132"
```
Fixes #6927
browser

feat: validate nullable

---

src/core/components/info.jsx

* fixes screen reader accessibility issue
refer to PR #6981 for details and completed PR form
Fixes #6975
Resolves unable to merge issue in PR #6981

fix(info): use externalDocsUrl check to render Link

---

package-lock.json

bump prismjs@1.23.0 and refactor@3.3.1
`npm audit`

chore(deps): bump prismjs@1.23.0 and refactor@3.3.1

---

package-lock.json
package.json

remove `copy-webpack-plugin`
remove an unused dependency. This dependency is mentioned in documentation and a sample webpack file.

chore(deps-dev): remove unused copy-webpack-plugin

---

.github/dependabot.yaml

Reduce open Dependabot PR count from 10 to 6.
Due to the CI time, the high PR count can be a blocker to other PRs.

chore(GA): reduce open dependabot pr count

---

package-lock.json
package.json

bump less from 3.11.2 to 4.1.1
update dependencies
`npm run dev` continues to build stylesheets

chore(deps-dev): bump less from 3.11.2 to 4.1.1

---

package-lock.json
package.json

bump sass-loader from 7.3.1 to 9.0.3
note: sass-loader@10.x requires webpack@5
note: requires #7089 to be (already) merged.
update dependencies

chore(deps-dev): bump sass-loader from 7.3.1 to 9.0.3

---

package-lock.json
package.json

bump cypress from 5.6.0 to 6.7.1
update dependencies.
closes #7083

chore(deps-dev): bump cypress from 5.6.0 to 6.7.1

---

.github/workflows/nodejs.yml

remove dependabot auto-merge action
This security change disabled auto-merging:
https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/

ci(GA): remove dependabot auto-merge action

---

package-lock.json
package.json

bump terser-webpack-plugin from 4.0.0 to 4.2.3
update dependencies

chore(deps-dev): bump terser-webpack-plugin from 4.0.0 to 4.2.3

---

package-lock.json
package.json

bump nightwatch from 1.6.1 to 1.6.2
update dependencies

chore(deps-dev): bump nightwatch from 1.6.1 to 1.6.2

---

package-lock.json
package.json

Replace `http-server` with `local-web-server`. This is a dev-only feature change, to serve a static instance of `swagger-ui`.
`http-server` relies on a deprecated and unmaintained package, `ecstatic`. `http-server` also has not been updated since 4/27/2020, and does not include the last security patch provided by `ecstatic`.
Though `local-web-server` hasn't been updated since 5/23/2020, it does not appear to have dependencies with current security advisories.
reference on `ecstatic` deprecation, with suggestions/comments to try `local-web-server`
[ecstatic's Past, Present and Future](https://github.com/jfhbrook/node-ecstatic/issues/259)
local dev via `npm start` works as intended

feat(dev): migrate to local-web-server

---

package-lock.json
package.json

bump eslint-plugin-jest from 24.18 to 24.3.5
Dependabot PR #7161 unable to  kick off Jenkins job. GA CI jobs pass.
existing tests pass

chore(deps-dev): bump eslint-plugin-jest from 24.18 to 24.3.5

---

package-lock.json
package.json
src/core/plugins/err/actions.js
src/core/plugins/spec/actions.js
src/core/system.js

* apply named imports, per v5.x breaking changes
bump serialize-errror from 2.1.0 to 8.1.0
also, update code to use named imports, per breaking release notes in 5.0.0
update dependencies. 
all existing tests pass locally.

chore(deps): bump serialize-errror from 2.1.0 to 8.1.0

---

package-lock.json
package.json

bump cssnano from 4.1.11 to 5.0.2
dependency update, which includes `npm audit` fixes
local build ok

chore(deps-dev): bump cssnano from 4.1.11 to 5.0.2

---

package-lock.json
package.json

bump eslint-plugin-jest from 24.3.5 to 24.3.6
update dependency.

chore(deps-dev): bump eslint-plugin-jest from 24.3.5 to 24.3.6

---

package-lock.json

update caniuse-lite to 1.0.30001230
update db for `browserslist`

chore(deps-dev): update caniuse-lite to 1.0.30001230

---

src/style/_layout.scss

Try It Out buttons, in the case that sample generation examples are available, 'cancel' and 'reset' should have spacing in between the two buttons. In addition, after clicking 'cancel', the new button text, 'try it out', should remain on a single line.
Make things more visually pleasing.
visual testing
**BEFORE:**
**AFTER:**

fix(try-it-out): button and inner text spacing

---

docs/development/setting-up.md
package-lock.json
package.json

Refs https://github.com/swagger-api/swagger-ui/issues/7436

chore(deps): bump swagger-client to v3.14.1

---

package-lock.json
package.json
src/core/plugins/configs/helpers.js
src/core/plugins/spec/actions.js
src/core/utils.js

Closes #6804
Updates js-yaml library to 4.1 version.
We're using relatively old version of js-yaml. 4.x branch is a new one with huge amount of fixes.

feat(js-yaml): update our main YAML parser to v4.1.0

---

package-lock.json
package.json

fix(security): bump swagger-client to v3.16.1

---

src/core/index.js
webpack/_config-builder.js

fix(build-security): do not expose hostname to build framents

---

package-lock.json
package.json

Refs https://github.com/swagger-api/swagger-ui/issues/7492
`react-syntax-highlighter@15.4.3 requires prismjs@~1.23.0 via refractor@3.3.1`
Upgrade prismjs to version 1.24.0 or later due to security issues in earlier versions

fix(security): fix security issue in prismjs dep

---

Dockerfile

fix(Dockerfile): fix security issue in docker image

---

src/style/_layout.scss

https://github.com/swagger-api/swagger-ui/pull/7464 changed the tabs in the example section from links to buttons to improve the accessibility. This PR changes the styles of the buttons so they look like the old links:

fix(style): update the buttons of the example tabs to be displayed as links

---

src/core/components/highlight-code.jsx

refactor(highlight-code): declare properties explicitly

---

.npmignore
LICENSE
NOTICE
flavors/swagger-ui-react/release/run.sh
swagger-ui-dist-package/deploy.sh

docs(LICENSE): apply Apache 2.0 License correctly

---

src/core/components/highlight-code.jsx

fix(highlight-code): fix regression code highlight behavior

---

flavors/swagger-ui-react/index.jsx

fix(swagger-ui-react): add showExtension propType

---

package-lock.json
src/core/components/models.jsx

Refs https://github.com/swagger-api/swagger-editor/issues/2099

fix: request JumpToPath components always as container

---

package-lock.json
package.json

bump sass from 1.35.1 to 1.48.0
Fixes #7363

chore(deps-dev): bump sass from 1.35.1 to 1.48.0

---

package-lock.json
package.json

Refs #7771
Closes #7766
Closes #7770

chore(deps): update swagger-client to v3.18.2

---

test/e2e-cypress/tests/bugs/5043.js

Refs affd4b9
---
Assuming this was introduced to compensate for https://github.com/swagger-api/swagger-ui/issues/7771 and it's no longer needed.

revert: add wait time for bugs/5043 to resolve spec (#7769)

---

flavors/swagger-ui-react/index.jsx

fix(swagger-ui-react): fix prop type for defaultModelRendering

---

package-lock.json
package.json

Refs https://github.com/advisories/GHSA-r683-j2x4-v87g

fix(security): update swagger-client to v3.18.3

---

package-lock.json
package.json
src/core/plugins/samples/fn.js
src/core/utils.js
src/helpers/memoizeN.js

refactor(memoize): get rid of memoizee prod dependency

---

src/core/plugins/view/index.js

fix(view-plugin): provide resolvers for memoized functions

---

src/helpers/memoizeN.js

refactor(memoizeN): extract support code out of closure

---

src/core/components/auth/oauth2.jsx

fix(auth): compensate for uninitialized config

---

docs/usage/installation.md

docs(installation): provide full example of unpkg usage

---

src/core/syntax-highlighting.js

fix(build): do not pull whole highlight.js and refractor libs

---

flavors/swagger-ui-react/index.jsx

fix(swagger-ui-react): load spec on initial render

---

package-lock.json

* chore(deps): bump vm2 from 3.9.5 to 3.9.9 
* chore(deps): bump refractor from 3.5.0 to 3.6.0
* chore(deps-dev): bump follow-redirects from 1.14.7 to 1.14.9
security fixes

chore(deps): fix security vulnerabilities

---

dist/oauth2-redirect.html

apply changes from #7828 (for dev-helpers) to the dist version of `./dist/oauth2-redirect.html`
followup to #7828

fix(oauth2): addEventListener only if document state is not 'loading'

---

flavors/swagger-ui-react/index.jsx

plugins prop can be defined as list of function as well.

fix(swagger-ui-react): amend prop validation for plugins

---

package-lock.json
package.json

bump `@braintree/sanitize-url` from `5.0.2` to `6.0.0`
security fix

chore(deps): bump @braintree/sanitize-url from 5.0.2 to 6.0.0

---

Dockerfile
docker/docker-entrypoint.d/40-swagger-ui.sh

improvement(docker): migrate run.sh to docker-entrypoint.d-script

---

flavors/swagger-ui-react/index.jsx

feat(swagger-ui-react): export presets and plugins as static props

---

src/core/plugins/oas3/components/http-auth.jsx

Referencing Bitwarden's doc for [custom fields](https://bitwarden.com/help/custom-fields/#more-about-custom-field-names), as cited in #7743, use `aria-label` instead of `name`.
Also add `aria-label` to the Auth-Basic input fields as well for consistency.
fixes #7926 
replacement for #7743 
manual local test. A new Cypress E2E test(s) will come in separate PR.

fix(auth): use aria-label instead of name field

---

docs/development/setting-up.md

Update installation docs for development, specifically point to `dev-helpers/swagger-initializer.js`
fixes #7943 
n/a

docs(dev): update dev-helpers installation

---

src/core/components/live-response.jsx

move the `h4` block from outside to inside of the related `request-url` block
fixes #7312 
n/a. visual change

refactor(live-response): move h4 to inside div class request-url

---

src/style/_buttons.scss

removed `padding-right` from the `authorization__btn` css style
fixes #7291 
n/a. visual change

refactor(css): alignment of authorization btn

---

dev-helpers/dev-helper-initializer.js

Restore the `url` setting, and remove the accidentally added dev paths to codebase
Keep `dev-helpers` clean
local testing

fix(dev-helpers): restore default url setting

---

docs/usage/installation.md

Existing instruction tells a user to edit `index.html` to replace a URL, but the file to edit is actually `swagger-initializer.js`.
At step 3, replace `index.html` with `swagger-initializer.js`, and "HTML editor" with "text editor".
Fixes #7974
`index.html` does not contain the URL "https://petstore.swagger.io/v2/swagger.json". This fix points the user to the correct file to edit.
- Replace the URL in `swagger-initializer.js`, and open `index.html` in a browser. It loads Swagger UI as expected.

docs: update standalone installation instruction

---

docs/usage/installation.md

fix IU -> UI typo

---

src/core/plugins/request-snippets/request-snippets.jsx

remove leftover text
fixes #8010 
n/a

fix: remove leftover text in request snippets

---

flavors/swagger-ui-react/README.md
flavors/swagger-ui-react/index.jsx

Added oauth2RedirectUrl to swagger-ui-react. 
It's need now the default behavior for redirect url changed to now containing path to Swagger UI
https://github.com/swagger-api/swagger-ui/issues/8027
Fixes #8027

feat(swagger-ui-react): Add oauth2RedirectUrl prop

---

docs/usage/version-detection.md

Docs incorrectly mentions 3.x under the 2.x section
Just a small typo I noticed

Fix small typo in documentation

---

src/core/components/primitive-model.jsx

Remove dead code and format document
The dead was removed and the document was formatted.
To have a cleaner and more readable code.
https://github.com/swagger-api/swagger-ui/issues/8047
Nothing to test.
Not applicable

fix: remove dead code and format document

---

package-lock.json

Npm audit fixes
security updates

fix(deps-dev): cumulative security updates

---

docs/usage/oauth2.md

Fix some typo
For better documentation
No need
- [] Dependency changes (any modification to dependencies in `package.json`)
- [] Bug fixes (non-breaking change which fixes an issue)

Fix some typo

---

babel.config.js
package-lock.json
package.json

Refs #8136
Manually integrating into  SwaggerEditor

fix(build): mitigate regressions to build framents in v4.13.1

---

docs/customization/overview.md
docs/customization/plugin-api.md
docs/usage/configuration.md
docs/usage/cors.md
docs/usage/version-detection.md
src/core/components/object-model.jsx
src/core/plugins/oas3/helpers.jsx
src/plugins/add-plugin.md
test/e2e-cypress/static/documents/features/parameter-array-missing-items.yaml
test/e2e-cypress/tests/bugs/5660.js
test/e2e-cypress/tests/features/oas3-multiple-servers.js
test/e2e-cypress/tests/features/oas3-user-edit-request-body-flows.js
test/e2e-cypress/tests/features/schema-form.js
test/e2e-cypress/tests/features/try-it-out-schema-required-override-allowed.js
test/e2e-selenium/scenarios/features/allow-empty-value.openapi.js
test/e2e-selenium/static/test-specs/bugs/4196.yaml
test/e2e-selenium/static/test-specs/refs/api1.yaml
test/e2e-selenium/static/test-specs/refs/api2.yaml
test/unit/core/curlify.js

This PR
* fixes typos in various files
* changes http to https for various links in the documentation

Fixing typos, change http:// to https:// for various links

---

src/core/components/array-model.jsx
src/core/components/object-model.jsx
src/core/components/operation-tag.jsx
src/core/components/operation.jsx
src/core/components/primitive-model.jsx
src/style/_layout.scss
src/style/_models.scss
test/e2e-cypress/static/documents/features/external-docs.openapi.yaml
test/e2e-cypress/static/documents/features/external-docs.swagger.yaml
test/e2e-cypress/tests/features/external-docs.js

Renders links to external docs in all locations where external docs can be used:
- Tag Object *(modified for consistency)*
- Schema Object
- Object *(added*)
- Array *(added)*
- Primitive *(added)*
- OpenAPI Object / Swagger Object *(not changed)*
- Operation *(not changed)*
Fixes #1545
*TODO*

Render links to external docs

---

package-lock.json
package.json

bump `release-it` from 15.3.0 to 15.4.2
security update

chore(deps-dev): bump release-it from 15.3.0 to 15.4.2

---

package-lock.json
package.json
webpack/stylesheets.babel.js

* bump `sass-loader` from 9.0.3 to 12.6.0
* update `stylesheets.babel.js`
Note, unable to bump all the way to 13.0.2. Fails Cypress CI in both node.js@14.17.0 and node.js@16.16.0
update dependencies.
Ref: #8119 
locally

chore(deps-dev): bump sass-loader from 9.0.3 to 12.6.0

---

src/style/_markdown.scss
src/style/_table.scss

As mentionned by @boudhayan-dev there is an aligment issue between name and description column.
Fixes #8207 
Manually, checking where the markdown class appears and checked if looked ok everywhere.
- [ X] Bug fixes (non-breaking change which fixes an issue)
- [X ] are not breaking changes.
- [X ] My changes do not require a change to the project documentation.
- [X ] My changes can not or do not need to be tested.

bug: fix aligment issue between name and desc

---

package-lock.json
package.json

Manually bump package version.
There was a failed release for v4.15.4, but it still appears on npm [here](https://www.npmjs.com/package/swagger-ui/v/4.15.4). The intended release was for #8288 
This will hopefully allow a new release to 4.15.5.

chore: manually bump version from failed release

---

.github/workflows/dependabot-merge.yml

Refs https://github.com/ahmadnassri/action-dependabot-auto-merge/issues/166

ci(dependabot-merge): replace non-functioning merge action

---

.github/workflows/release-swagger-ui-react.yml
.github/workflows/release-swagger-ui.yml
.gitignore
.releaserc

* swagger-ui
* swagger-ui-react
Github actions to release `next` version of SwaggerUI. Applies to:
- `swagger-ui`
- `swagger-ui-react`
This first iteration expects separate manual user activation to release `swagger-ui` then `swagger-ui-react`.
CI automation to release from `next` branch.
Testing locally using https://github.com/nektos/act

ci(release): github actions to release `next` branch

---

.github/workflows/release-swagger-ui-react.yml
.github/workflows/release-swagger-ui.yml
.gitignore
.releaserc
.whitesource
package-lock.json
whitesource.config

- Empty commit to trigger a MAJOR release from `next` branch
- merge latest updates from `master` branch
Use new github actions to release `swagger-ui` and `swagger-ui-react` from `next` branch.

BREAKING CHANGE: trigger major semver release from 'next' branch

---

.github/workflows/release-swagger-ui-react.yml

update step from `npm pack .` to `npm publish .`

ci(release): update ga for swagger-ui-react to npm publish

---

.github/workflows/release-swagger-ui.yml

ci(release): update github action for npm package

---

.github/workflows/release-swagger-ui.yml

ci(release): update npm token

---

.github/workflows/release-swagger-ui-react.yml

Update github actions workflow. Based on latest updates to the related `release-swagger-ui` workflow file

ci(release): update ga workflow to release swagger-ui-react

---

.github/workflows/release-swagger-ui.yml

add missing build step.
prior release package did not include updated build files.

fix(ci): add build files step

---

.github/workflows/release-swagger-ui-react.yml

try adding `--tag alpha` to the Release SwaggerUI-React@next workflow
hopefully NPM package gets the `alpha` tag instead of `latest`

fix(ci): add ga --tag alpha for swagger-ui-react next

---

.github/workflows/release-swagger-ui-react.yml

Add build step to build (base) SwaggerUI, so that updated build files are used.
GA to release SwaggerUI currently does not check-in latest dist files as part of the workflow.
local testing to verify addition to GA workflow works.

fix(ci-react): add ga build step

---

.github/workflows/release-swagger-ui-react.yml
.github/workflows/release-swagger-ui.yml

copy ga workflows from `next` branch. Note that the workflows already reference the `next` branch, and should not be run from other branches.
The `next` branch has the working Github Actions workflows to release `swagger-ui` and `swagger-ui-react`

ci(ga): copy ga workflows from next

---

.github/workflows/dependabot-merge.yml
.github/workflows/nodejs.yml

PRs to `next` branch should run build tests.
dependabot should update `next` branch, alongside `master` branch

ci(ga): add next branch to build and dependabot workflows

---

package-lock.json
package.json

feat: integrate swagger-client@3.19.0-beta.6

---

package-lock.json
package.json

feat: integrate swagger-client@3.19.0-beta.7

---

package-lock.json
package.json

swagger-client has been reverted back to ^3.18.5,
becase it introduces backward incompatible behavior for yarn@2 package manager.
Refs 61642927b627dfe53b4403f8f28dbf355f64ddb4
Refs d293555a8f7760479a8a85bd996d4664e5f56f6c
Refs #8418

revert: integrate swagger-client@3.19.0-beta.7

---

package-lock.json
package.json

feat: integrate swagger-client@3.19.0-beta.8

---

package-lock.json
package.json

chore(deps): update swagger-client to v3.19.0

---

package-lock.json

Forgot to regenerate package-lock.json in https://github.com/swagger-api/swagger-ui/pull/8453

chore(deps): update swagger-client from v3.19.0 to v3.19.1

---

.github/workflows/nodejs.yml

ci(nodejs): run workflow on next branch

---

test/unit/core/utils.js

test(core): fix unit test assertion

---

package-lock.json
package.json
webpack/_config-builder.js

build(webpack): amend build configs to compensate for ApiDOM

---

package.json

ci(release): prepare configs for v5 alpha pre-releases

---

src/core/plugins/oas3/spec-extensions/selectors.js
src/core/plugins/oas3/spec-extensions/wrap-selectors.js
src/core/plugins/oas31/components/license.jsx
src/core/plugins/oas31/index.js
src/core/plugins/oas31/selectors.js
src/core/plugins/oas31/spec-extensions/selectors.js
src/core/plugins/oas31/wrap-components/license.jsx

refactor(oas31): change License component into smart

---

src/core/plugins/oas31/components/contact.jsx
src/core/plugins/oas31/index.js
src/core/plugins/oas31/spec-extensions/selectors.js
src/core/plugins/oas31/wrap-components/contact.jsx

refactor(oas31): change Contact component to be smart

---

src/core/plugins/oas31/components/info.jsx
src/core/plugins/oas31/index.js
src/core/plugins/oas31/spec-extensions/selectors.js
src/core/plugins/oas31/wrap-components/info.jsx

refactor(oas31): change Info compnent to be smart

---

src/core/plugins/oas3/components/request-body.jsx
src/core/plugins/oas31/fn.js
src/core/plugins/oas31/index.js
src/core/plugins/oas31/oas3-extensions/wrap-selectors.js
src/core/plugins/oas31/spec-extensions/wrap-selectors.js

refactor(oas31): disable try it out mechanism explicitly for webhooks

---

src/core/plugins/oas31/components/info.jsx
src/core/plugins/oas31/components/json-schema-dialect.jsx
src/core/plugins/oas31/index.js
src/core/plugins/oas31/spec-extensions/selectors.js

feat(oas31): add support for rendering OpenAPI.jsonSchemaDialect field

---

src/core/plugins/oas31/fn.js
src/core/plugins/oas31/oas3-extensions/wrap-selectors.js

fix(oas31): fix recursive bug in hasUserEditedBody selector wrapper

---

flavors/swagger-ui-react/release/run.sh
swagger-ui-dist-package/deploy.sh

chore(dist-tags): use alpha npm dist tags for 5.x.y-alpha.* releases

---

package-lock.json
package.json

This support comes with swagger-client@3.19.4 update.
Refs #8525

fix: add relative reference support for baseDoc option

---

package-lock.json
package.json

This bug fix comes via swagger-client@3.19.5.
Refs #8532

fix(oas31): fix resolver error about immutable Headers

---

package-lock.json
package.json

The fix comes from updating the swagger-client
to v3.19.6.
Refs #8537

fix(oas31): fix rendering Path Items containing schemas with cycles

---

src/core/plugins/json-schema-2020-12/components/JSONSchema/JSONSchema.jsx
src/core/plugins/oas31/components/models.jsx

fix(oas31): resolve schemas in 'Schemas section' only if expanded

---

src/core/plugins/json-schema-2020-12/components/JSONSchema/JSONSchema.jsx
src/core/plugins/json-schema-2020-12/components/keywords/Const.jsx
src/core/plugins/json-schema-2020-12/components/keywords/_all.scss
src/core/plugins/json-schema-2020-12/fn.js
src/core/plugins/json-schema-2020-12/hoc.jsx
src/core/plugins/json-schema-2020-12/index.js
src/core/plugins/oas31/wrap-components/models.jsx

feat(json-schema-2020-12): add support for const keyword

---

src/core/plugins/json-schema-2020-12/components/JSONSchema/JSONSchema.jsx
src/core/plugins/json-schema-2020-12/components/keywords/Enum/Enum.jsx
src/core/plugins/json-schema-2020-12/components/keywords/Enum/_enum.scss
src/core/plugins/json-schema-2020-12/components/keywords/_all.scss
src/core/plugins/json-schema-2020-12/fn.js
src/core/plugins/json-schema-2020-12/hoc.jsx
src/core/plugins/json-schema-2020-12/index.js
src/core/plugins/oas31/wrap-components/models.jsx

feat(json-schema-2020-12): add support for enum keyword

---

src/core/plugins/json-schema-2020-12/components/keywords/Constraint/Constraint.jsx
src/core/plugins/json-schema-2020-12/components/keywords/Constraint/_constraint.scss
src/core/plugins/json-schema-2020-12/fn.js

Includes following keywords:
- minLength
- maxLength
- pattern
Refs #8513

feat(json-schema-2020-12): add support for validation Keywords for Strings

---

src/core/plugins/json-schema-2020-12/components/keywords/Contains.jsx
src/core/plugins/json-schema-2020-12/fn.js

feat(json-schema-2020-12): support validation keywords for arrays

---

src/core/plugins/json-schema-2020-12/components/keywords/Properties/Properties.jsx
src/core/plugins/json-schema-2020-12/components/keywords/Properties/_properties.scss

feat(json-schema-2020-12): add support for required keyword

---

src/core/plugins/json-schema-2020-12/components/JSONSchema/JSONSchema.jsx
src/core/plugins/json-schema-2020-12/components/keywords/DependentRequired/DependentRequired.jsx
src/core/plugins/json-schema-2020-12/components/keywords/DependentRequired/_dependent-required.scss
src/core/plugins/json-schema-2020-12/components/keywords/Properties/Properties.jsx
src/core/plugins/json-schema-2020-12/components/keywords/Properties/_properties.scss
src/core/plugins/json-schema-2020-12/components/keywords/_all.scss
src/core/plugins/json-schema-2020-12/fn.js
src/core/plugins/json-schema-2020-12/hoc.jsx
src/core/plugins/json-schema-2020-12/index.js
src/core/plugins/oas31/wrap-components/models.jsx

feat(json-schema-2020-12): add support for dependentRequired keyword

---

src/core/plugins/json-schema-2020-12/components/keywords/Constraint/Constraint.jsx
src/core/plugins/json-schema-2020-12/fn.js

feat(json-schema-2020-12): add support for contentMediaType keyword

---

src/core/plugins/json-schema-2020-12/components/JSONSchema/JSONSchema.jsx
src/core/plugins/json-schema-2020-12/components/keywords/ContentSchema.jsx
src/core/plugins/json-schema-2020-12/fn.js
src/core/plugins/json-schema-2020-12/hoc.jsx
src/core/plugins/json-schema-2020-12/index.js
src/core/plugins/oas31/wrap-components/models.jsx

feat(json-schema-2020-12): add support for contentSchema keyword

---

src/core/plugins/json-schema-2020-12/components/JSONSchema/JSONSchema.jsx
src/core/plugins/json-schema-2020-12/components/keywords/Default.jsx
src/core/plugins/json-schema-2020-12/fn.js
src/core/plugins/json-schema-2020-12/hoc.jsx
src/core/plugins/json-schema-2020-12/index.js
src/core/plugins/oas31/wrap-components/models.jsx

feat(json-schema-2020-12): add support for default keyword

---

src/core/plugins/json-schema-2020-12/components/JSONSchema/JSONSchema.jsx
src/core/plugins/json-schema-2020-12/components/keywords/Deprecated/Deprecated.jsx
src/core/plugins/json-schema-2020-12/components/keywords/Deprecated/_deprecated.scss
src/core/plugins/json-schema-2020-12/components/keywords/_all.scss
src/core/plugins/json-schema-2020-12/hoc.jsx
src/core/plugins/json-schema-2020-12/index.js
src/core/plugins/oas31/wrap-components/models.jsx

feat(json-schema-2020-12): add support for deprecated keyword

---

src/core/plugins/json-schema-2020-12/components/JSONSchema/JSONSchema.jsx
src/core/plugins/json-schema-2020-12/components/keywords/ReadOnly/ReadOnly.jsx
src/core/plugins/json-schema-2020-12/components/keywords/ReadOnly/_read-only.scss
src/core/plugins/json-schema-2020-12/components/keywords/_all.scss
src/core/plugins/json-schema-2020-12/hoc.jsx
src/core/plugins/json-schema-2020-12/index.js
src/core/plugins/oas31/wrap-components/models.jsx

feat(json-schema-2020-12): add support for readOnly keyword

---

src/core/plugins/json-schema-2020-12/components/JSONSchema/JSONSchema.jsx
src/core/plugins/json-schema-2020-12/components/keywords/ReadOnly/ReadOnly.jsx
src/core/plugins/json-schema-2020-12/components/keywords/ReadOnly/_read-only.scss
src/core/plugins/json-schema-2020-12/components/keywords/WriteOnly/WriteOnly.jsx
src/core/plugins/json-schema-2020-12/components/keywords/WriteOnly/_write-only.scss
src/core/plugins/json-schema-2020-12/components/keywords/_all.scss
src/core/plugins/json-schema-2020-12/hoc.jsx
src/core/plugins/json-schema-2020-12/index.js
src/core/plugins/oas31/wrap-components/models.jsx

feat(json-schema-2020-12): add support for writeOnly keyword

---

src/core/plugins/oas31/index.js
src/core/plugins/oas31/json-schema-2020-12-extensions/wrap-components/keywords/Description.jsx

refactor(oas31): standardize JSON Schema 2020-12 plugin extensions

---

src/core/plugins/json-schema-2020-12/index.js
src/core/plugins/oas31/index.js
src/core/plugins/oas31/json-schema-2020-12-extensions/components/keywords/Description.jsx
src/core/plugins/oas31/json-schema-2020-12-extensions/components/keywords/Example.jsx
src/core/plugins/oas31/json-schema-2020-12-extensions/fn.js
src/core/plugins/oas31/json-schema-2020-12-extensions/wrap-components/keywords/Default.jsx
src/core/plugins/oas31/json-schema-2020-12-extensions/wrap-components/keywords/Description.jsx
src/core/plugins/oas31/wrap-components/models.jsx

feat(oas31): add support for JSON Schema 2020-12 example keyword

---

src/core/plugins/oas31/index.js
src/core/plugins/oas31/json-schema-2020-12-extensions/components/keywords/Discriminator/Discriminator.jsx
src/core/plugins/oas31/json-schema-2020-12-extensions/components/keywords/Discriminator/DiscriminatorMapping.jsx
src/core/plugins/oas31/json-schema-2020-12-extensions/components/keywords/Example.jsx
src/core/plugins/oas31/json-schema-2020-12-extensions/components/keywords/Xml.jsx
src/core/plugins/oas31/json-schema-2020-12-extensions/wrap-components/keywords/Default.jsx

feat(oas31): add support for Schema Object discriminator keyword

---

src/core/plugins/oas3/components/callbacks.jsx
src/core/plugins/oas31/components/webhooks.jsx
test/e2e-cypress/tests/features/webhooks.js

fix(oas31): fix deep linking for Webhooks and Callbacks

---

src/core/plugins/json-schema-2020-12/fn.js

fix(json-schema-2020-12): fix predicate in hasKeyword function

---

package-lock.json
package.json

Refs https://github.com/swagger-api/swagger-js/releases/tag/v3.19.8

chore(deps): bump swagger-client to v3.19.8

---

src/core/plugins/json-schema-2020-12/fn.js
src/core/plugins/oas31/components/models/models.jsx

fix(oas31): avoid capitalizing first character of components.schemas

---

Dockerfile

chore(docker): update Dockerfile base image to nginx:1.25.0-alpine

---

src/core/plugins/json-schema-2020-12/samples-extensions/fn.js
src/core/plugins/oas31/after-load.js
src/core/plugins/oas31/fn.js
src/core/plugins/oas31/index.js
src/core/plugins/oas31/json-schema-2020-12-extensions/fn.js
src/core/plugins/oas31/wrap-components/models.jsx

These overrides are specific to OpenAPI 3.1.0
and JSON Schema 2020-12.
Refs #8577

feat(oas31): enable overrides for samples plugin

---

.github/workflows/docker-build-push.yml

ci(docker): add initial workflow for creating multi platform Docker images

---

.github/workflows/docker-build-push.yml

ci(docker): distinguish docker_ref and git_ref inputs

---

.github/workflows/docker-build-push.yml

ci(docker): add support for `repository_dispatch` event type

---

src/core/plugins/json-schema-2020-12/samples-extensions/fn.js
test/unit/core/plugins/json-schema-2020-12/samples-extensions/fn.js

feat(samples): add support for type keyword defined as list of types

---

src/core/plugins/json-schema-2020-12/samples-extensions/fn.js

This change is specific ot  JSON Schema 2020-12
Refs #8577

refactor(samples): add better support for exclusive number ranges

---

src/core/plugins/json-schema-2020-12/samples-extensions/fn.js
test/unit/core/plugins/json-schema-2020-12/samples-extensions/fn.js

This change is specific ti JSON Schema 2020-12
Refs #8577

feat(samples): support multipleOf keyword

---

src/core/plugins/json-schema-2020-12/samples-extensions/fn.js
test/unit/core/plugins/json-schema-2020-12/samples-extensions/fn.js

feat(samples): add support for contains, minContains, maxContains keywords

---

src/core/plugins/json-schema-2020-12/samples-extensions/fn.js

refactor(samples): type check object constraints acording to spec

---

src/core/plugins/json-schema-2020-12/samples-extensions/fn.js
test/unit/core/plugins/json-schema-2020-12/samples-extensions/fn.js

feat(samples): add support for contentEncoding keyword

---

src/core/plugins/json-schema-2020-12/samples-extensions/fn.js

refactor(samples): extract number and string constrains applicators

---

src/core/plugins/json-schema-2020-12/samples-extensions/fn.js
test/unit/core/plugins/json-schema-2020-12/samples-extensions/fn.js

feat(samples): add support for contentMediaType keyword

---

src/core/plugins/json-schema-2020-12/samples-extensions/fn/core/constants.js
src/core/plugins/json-schema-2020-12/samples-extensions/fn/core/fold-type.js
src/core/plugins/json-schema-2020-12/samples-extensions/fn/core/predicates.js
src/core/plugins/json-schema-2020-12/samples-extensions/fn/core/utils.js
src/core/plugins/json-schema-2020-12/samples-extensions/fn/main.js
src/core/plugins/json-schema-2020-12/samples-extensions/fn/types/array.js
src/core/plugins/json-schema-2020-12/samples-extensions/fn/types/index.js
src/core/plugins/json-schema-2020-12/samples-extensions/fn/types/string.js
test/unit/core/plugins/json-schema-2020-12/samples-extensions/fn.js

feat(samples): add support for contentSchema keyword

---

flavors/swagger-ui-react/release/run.sh
package.json
swagger-ui-dist-package/deploy.sh

chore(release): prepare configuration for switching to beta channel

---

package.json

close https://github.com/swagger-api/swagger-ui/issues/8163
This issue requires client side to use patch-package or other workarounds. It'll be great if this can be fixed officially.
given `test.ts`
```ts
import 'swagger-ui/dist/swagger-ui-standalone-preset'
```
before
```sh
$ esbuild test.ts --bundle
> test.ts:1:7: error: Could not resolve "swagger-ui/dist/swagger-ui-standalone-preset" (mark it as external to exclude it from the bundle)
1 │ import 'swagger-ui/dist/swagger-ui-standalone-preset'
╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/swagger-ui/package.json:6:13: note: The path "./dist/swagger-ui-standalone-preset" is not exported by package "swagger-ui"
6 │   "exports": {
╵              ^
1 error
```
after
```sh
$ esbuild test.ts --bundle
```

fix: Add missing swagger-ui-standalone-preset export

---

package-lock.json
package.json
test/unit/core/utils.js

chore(deps): bump @babel/runtime-corejs3 from 7.21.5 to 7.22.5

---

package-lock.json
package.json

chore(package-lock): regenerate package-lock.json file

---

package-lock.json
package.json
src/core/plugins/spec/actions.js

perf(spec): increase performance of operation expansion

---

flavors/swagger-ui-react/README.md

Correct a spelling mistake in README.
N/a
N/a

docs(swagger-ui-react): fix a typo in README

---

package-lock.json
package.json

Refs https://github.com/swagger-api/apidom/issues/2934
The fix comes from updating the upstream swagger-client version to latest one.

fix: fix critical bug in OpenAPI 3.1.0 resolution

---

config/jest/jest.unit.config.js
package-lock.json
package.json

chore(deps-dev): bump sinon from 15.1.0 to 15.2.0

---

src/core/plugins/json-schema-2020-12/fn.js

fix(json-schema-2020-12): fix rendering of exclusiveMin|Max keywords

---

Dockerfile

Refs https://security.snyk.io/vuln/SNYK-ALPINE317-TIFF-5747689

fix(docker): fix libtiff NULL Pointer dereference issue

---

package-lock.json

This was done to pickup ApiDOM@0.74.0

chore(deps): regenerate package-lock.json

---

test/unit/core/curlify.js

test(curlify): add test for multipart request quotes handling

---

flavors/swagger-ui-react/index.jsx
flavors/swagger-ui-react/release/create-manifest.js
flavors/swagger-ui-react/release/run.sh
flavors/swagger-ui-react/release/template.json

fix(swagger-ui-react): fix corrupted exports field from package.json

---

flavors/swagger-ui-react/README.md

Refs https://github.com/swagger-api/swagger-ui/wiki/Seamless-Integration-with-Bundlers-&-Test-Tools

docs(README): remove mention about Next.js workaround

---

src/core/plugins/oas3/index.js
src/core/plugins/oas31/auth-extensions/wrap-selectors.js

refactor: reuse selector logic

---

dev-helpers/index.html
package-lock.json
package.json
src/core/components/model.jsx
src/core/components/operation.jsx
src/standalone/plugins/top-bar/components/Logo.jsx
webpack/_config-builder.js
webpack/dev.js

fix(security): allow more strict CSP for SVG assets

---

src/core/plugins/oas3/spec-extensions/selectors.js
test/e2e-cypress/e2e/features/oas3-callbacks.cy.js
test/e2e-cypress/static/documents/features/oas3-callbacks.yaml

Refs #9222
**Displaying all defined callbacks:**

fix(callbacks): display all defined callbacks

---

package-lock.json
package.json

fix: display defined OpenAPI Parameter Objects

---

package-lock.json
package.json
src/core/plugins/oas3/selectors.js
src/core/plugins/oas3/spec-extensions/wrap-selectors.js
src/core/plugins/oas31/selectors.js
src/core/plugins/oas31/spec-extensions/selectors.js
src/core/plugins/spec/selectors.js

chore(deps): bump reselect from 4.1.8 to 5.0.1

---

src/core/plugins/oas31/spec-extensions/selectors.js

fix(oas31): make selectors always return expected shapes

---

src/core/components/schemes.jsx
src/core/plugins/oas3/components/servers.jsx
src/standalone/plugins/top-bar/components/TopBar.jsx

Refs #9523
Supersedes https://github.com/swagger-api/swagger-ui/pull/9524

fix: add missing HTML id attributes

---

src/core/plugins/spec/reducers.js
test/unit/core/plugins/spec/reducer.js

fix(spec): set multi-value parameters as an immutable list

---

package-lock.json
package.json

chore(deps-dev): bump webpack-dev-server from 4.15.1 to 5.0.1

---

Dockerfile

Refs https://github.com/swagger-api/swagger-ui/actions/runs/7911140707/job/21594844531

fix(docker): fix libexpat vulnerability

---

docs/usage/configuration.md

chore: remove repetitive word in docs

---

src/core/plugins/oas3/components/request-body.jsx
test/e2e-cypress/e2e/features/plugins/oas3/one-of-any-of-example.cy.js
test/e2e-cypress/static/documents/features/oas3-one-of-any-of-example.yaml

fix(oas3): add support for oneOf/anyOf JSON Schema keywords in request-body rendering

---

Dockerfile

fix(docker): fix CVE-2024-27983 related to Node.js

---

src/core/plugins/json-schema-2020-12-samples/fn/api/optionAPI.js
src/core/plugins/json-schema-2020-12-samples/fn/class/OptionRegistry.js
src/core/plugins/json-schema-2020-12-samples/fn/index.js
src/core/plugins/json-schema-2020-12-samples/index.js

feat(json-schema-2020-12-sample): introduce option API

---

src/core/plugins/json-schema-2020-12-samples/fn/types/string.js

fix(json-schema-2020-12-samples): apply string constraints sensibly

---

src/core/components/model.jsx
test/e2e-cypress/e2e/features/plugins/oas3/all-of-circular-ref.cy.js
test/e2e-cypress/static/documents/features/oas3-all-of-circular-ref.yaml

fix(oas3): merge schema with schema unresolved by swagger-client

---

test/unit/core/plugins/err/transformers/not-of-type.js
test/unit/core/plugins/err/transformers/parameter-oneof.js

chore: fix some typos in comments

---

src/core/config/defaults.js
src/core/config/sources/query.js
src/core/config/type-cast/mappings.js
src/core/index.js

fix(config): address getting configUrl from options

---

flavors/swagger-ui-react/index.jsx

fix(swagger-ui-react): avoid triggering implicit system rendering

---

flavors/swagger-ui-react/index.jsx

fix(swagger-ui-react): call onComplete hook with system instance

---

docs/development/setting-up.md

While setting up the project for development I noticed that `npm install` is missing in the steps.

docs: Add missing `npm install` in the development docs

---

package-lock.json
package.json

fix(deps): allow to consolidate deps in downstream projects

---

README.md

chore: added a link to the contributors badge
